import {
  Download,
  Image as ImageIcon,
  FileText,
  Scissors,
  FileType,
  Combine,
  Minimize2,
  FileImage,
  QrCode,
  ScanLine,
  ScanText,
  Sparkles,
  Volume2,
  Mic,
  Film,
  Lock,
  Code2,
  Type,
  Braces,
  Palette,
  Wand2,
  Stamp,
  Pencil,
  FileCode,
  Monitor,
  Music,
  Video,
  AudioLines,
  Aperture,
  ScanFace,
  Hand,
  Boxes,
  Brain,
  Maximize2,
  Crop,
  LayoutGrid,
  Laugh,
  CreditCard,
  Captions,
  FileMinus,
  Layers,
  RotateCw,
  ScanSearch,
  FileSearch,
  FilePen,
  FileX,
  Shield,
  FileOutput,
  Link,
  Clock,
  Moon,
  Calculator,
  Activity,
  CalendarDays,
  Link2,
  AlignLeft,
  Fingerprint,
  Hash,
  Shuffle,
  Users,
  Gamepad2,
  Flame,
  Dices,
  Joystick,
  Grid2x2,
  X,
  Crosshair,
  BookOpen,
  Bomb,
  Search,
  Keyboard,
  Bird,
  Crown,
  Circle,
  CircleDot,
  Hammer,
  Target,
  Rows3,
  Ghost,
  Spade,
  Puzzle,
  Pickaxe,
  Zap,
  Gauge,
  Globe,
  Network,
  Wifi,
  KeyRound,
  Radio,
  MessageSquare,
  CloudSun,
  Calendar,
  ArrowLeftRight,
  Rocket,
  FlaskConical,
  FolderOpen,
  Pipette,
  Bitcoin,
  Ruler,
} from "lucide-react";
// Layers already imported above — reused for Tetris.

export type ToolCategory = "video" | "image" | "pdf" | "text" | "audio" | "ai" | "utility" | "games" | "minigames";

export const categoryMeta: Record<ToolCategory, { label: string; color: string; icon: string }> = {
  video: { label: "Video Tools", color: "var(--cyan-brand)", icon: "🎬" },
  image: { label: "Image Tools", color: "var(--violet-brand)", icon: "🖼️" },
  audio: { label: "Audio Tools", color: "var(--violet-brand)", icon: "🎙️" },
  pdf: { label: "PDF & Documents", color: "var(--orange-brand)", icon: "📄" },
  text: { label: "Text Tools", color: "var(--green-brand)", icon: "✍️" },
  ai: { label: "AI Tools", color: "var(--violet-brand)", icon: "🤖" },
  utility: { label: "Utility Tools", color: "var(--green-brand)", icon: "🛠️" },
  games: { label: "Game Tools", color: "var(--violet-brand)", icon: "🎲" },
  minigames: { label: "Mini Games", color: "var(--cyan-brand)", icon: "🕹️" },
};

export interface Tool {
  slug: string;
  name: string;
  description: string;
  category: ToolCategory;
  categories?: ToolCategory[];
  icon: typeof Download;
  path: string;
  hidden?: boolean;
}

export const toolInCategory = (t: Tool, c: ToolCategory) => t.category === c || (t.categories?.includes(c) ?? false);

export const tools: Tool[] = [
  {
    slug: "video-downloader",
    name: "Video Downloader",
    description: "Download videos from TikTok, Instagram, YouTube and more.",
    category: "video",
    icon: Download,
    path: "/tools/video-downloader",
    hidden: true,
  },
  {
    slug: "video-to-gif",
    name: "Video to GIF",
    description: "Convert any video clip to a high-quality animated GIF.",
    category: "video",
    icon: Film,
    path: "/tools/video-to-gif",
  },
  {
    slug: "video-trimmer",
    name: "Video Trimmer",
    description: "Cut and trim video clips instantly in your browser.",
    category: "video",
    icon: Scissors,
    path: "/tools/video-trimmer",
  },
  {
    slug: "video-merger",
    name: "Video Merger",
    description: "Combine multiple videos into one — no uploads needed.",
    category: "video",
    icon: Combine,
    path: "/tools/video-merger",
  },
  {
    slug: "add-subtitles",
    name: "Add Subtitles to Video",
    description: "Burn subtitles into any video right in your browser.",
    category: "video",
    icon: Captions,
    path: "/tools/add-subtitles",
  },
  {
    slug: "image-converter",
    name: "Image Converter",
    description: "Convert PNG, JPG, WebP and AVIF in seconds.",
    category: "image",
    icon: FileImage,
    path: "/tools/image-converter",
  },
  {
    slug: "image-compressor",
    name: "Image Compressor",
    description: "Shrink images without losing quality.",
    category: "image",
    icon: Minimize2,
    path: "/tools/image-compressor",
  },
  {
    slug: "image-upscaler",
    name: "Image Upscaler",
    description: "Upscale images 2x or 4x with Real-ESRGAN AI.",
    category: "image",
    icon: Sparkles,
    path: "/tools/image-upscaler",
  },
  {
    slug: "remove-bg",
    name: "Remove Background",
    description: "Erase image backgrounds with one click.",
    category: "image",
    icon: Scissors,
    path: "/tools/remove-bg",
  },
  {
    slug: "pdf-text-extractor",
    name: "Extract Text from PDF",
    description: "Extract all text from any PDF instantly.",
    category: "pdf",
    icon: FileText,
    path: "/tools/pdf-text-extractor",
  },
  {
    slug: "word-to-pdf",
    name: "Word to PDF",
    description: "Turn Word documents into polished PDFs.",
    category: "pdf",
    icon: FileType,
    path: "/tools/word-to-pdf",
  },
  {
    slug: "merge-pdf",
    name: "Merge PDF",
    description: "Combine multiple PDFs into a single file.",
    category: "pdf",
    icon: Combine,
    path: "/tools/merge-pdf",
  },
  {
    slug: "qr-generator",
    name: "QR Code Generator",
    description: "Create custom QR codes from any URL or text.",
    category: "utility",
    icon: QrCode,
    path: "/tools/qr-generator",
  },
  {
    slug: "qr-reader",
    name: "QR Code Reader",
    description: "Decode QR codes from images or your camera.",
    category: "utility",
    icon: ScanLine,
    path: "/tools/qr-reader",
  },
  {
    slug: "image-to-text",
    name: "Image to Text (OCR)",
    description: "Extract text from images in multiple languages.",
    category: "image",
    icon: ScanText,
    path: "/tools/image-to-text",
  },
  {
    slug: "text-to-speech",
    name: "Text to Speech",
    description: "Convert text to natural speech in multiple languages.",
    category: "audio",
    icon: Volume2,
    path: "/tools/text-to-speech",
  },
  {
    slug: "speech-to-text",
    name: "Speech to Text",
    description: "Transcribe your voice to text in real-time.",
    category: "audio",
    icon: Mic,
    path: "/tools/speech-to-text",
  },
  {
    slug: "password-generator",
    name: "Password Generator",
    description: "Generate strong, secure passwords instantly.",
    category: "utility",
    icon: Lock,
    path: "/tools/password-generator",
  },
  {
    slug: "base64",
    name: "Base64 Encoder / Decoder",
    description: "Encode plain text to Base64 or decode Base64 strings instantly.",
    category: "text",
    icon: Code2,
    path: "/tools/base64",
  },
  {
    slug: "word-counter",
    name: "Word Counter",
    description: "Count words, characters, sentences and estimate reading time.",
    category: "text",
    icon: Type,
    path: "/tools/word-counter",
  },
  {
    slug: "json-formatter",
    name: "JSON Formatter",
    description: "Format, prettify and minify JSON instantly.",
    category: "text",
    icon: Braces,
    path: "/tools/json-formatter",
  },
  {
    slug: "color-palette",
    name: "Color Palette Extractor",
    description: "Extract the dominant colors from any image instantly.",
    category: "image",
    icon: Palette,
    path: "/tools/color-palette",
  },
  {
    slug: "image-filters",
    name: "Image Filters",
    description: "Apply beautiful filters to your images instantly in the browser.",
    category: "image",
    icon: Wand2,
    path: "/tools/image-filters",
  },
  {
    slug: "add-watermark",
    name: "Add Watermark",
    description: "Add custom text watermarks to your images in seconds.",
    category: "image",
    icon: Stamp,
    path: "/tools/add-watermark",
  },
  {
    slug: "image-to-sketch",
    name: "Image to Sketch",
    description: "Transform any photo into a pencil or charcoal sketch instantly.",
    category: "image",
    icon: Pencil,
    path: "/tools/image-to-sketch",
  },
  {
    slug: "markdown-to-html",
    name: "Markdown to HTML",
    description: "Convert Markdown to clean HTML with live preview instantly.",
    category: "text",
    icon: FileCode,
    path: "/tools/markdown-to-html",
  },
  {
    slug: "screen-recorder",
    name: "Screen Recorder",
    description: "Record your screen with audio directly in the browser — no installs needed.",
    category: "video",
    icon: Monitor,
    path: "/tools/screen-recorder",
  },
  {
    slug: "split-pdf",
    name: "Split PDF",
    description: "Extract specific pages from any PDF file instantly.",
    category: "pdf",
    icon: Scissors,
    path: "/tools/split-pdf",
  },
  {
    slug: "audio-converter",
    name: "Audio Converter",
    description: "Convert audio files between MP3, WAV, OGG, AAC and FLAC instantly.",
    category: "audio",
    icon: Music,
    path: "/tools/audio-converter",
  },
  {
    slug: "video-compressor",
    name: "Video Compressor",
    description: "Reduce video file size without losing quality.",
    category: "video",
    icon: Video,
    path: "/tools/video-compressor",
  },
  {
    slug: "extract-audio",
    name: "Extract Audio from Video",
    description: "Extract MP3, AAC or WAV audio from any video file.",
    category: "video",
    icon: AudioLines,
    path: "/tools/extract-audio",
  },
  {
    slug: "background-blur",
    name: "AI Background Blur",
    description: "Blur photo or webcam backgrounds in real time with AI.",
    category: "ai",
    icon: Aperture,
    path: "/tools/background-blur",
  },
  {
    slug: "face-landmarks",
    name: "Face Landmarks",
    description: "Detect 468 facial landmarks on photos or live camera.",
    category: "ai",
    icon: ScanFace,
    path: "/tools/face-landmarks",
    hidden: true,
  },
  {
    slug: "hand-gesture",
    name: "Hand Gesture Recognition",
    description: "Recognize hand gestures in real time from your webcam.",
    category: "ai",
    icon: Hand,
    path: "/tools/hand-gesture",
    hidden: true,
  },
  {
    slug: "object-detection",
    name: "Object Detection",
    description: "Detect 80+ object classes in images or live video with COCO-SSD.",
    category: "ai",
    icon: Boxes,
    path: "/tools/object-detection",
    hidden: true,
  },
  {
    slug: "sentiment-analysis",
    name: "AI Sentiment Analysis",
    description: "Analyze the sentiment of any text — positive, negative or neutral.",
    category: "ai",
    icon: Brain,
    path: "/tools/sentiment-analysis",
  },
  {
    slug: "image-resizer",
    name: "Image Resizer",
    description: "Resize images by pixels or percentage with quality control.",
    category: "image",
    icon: Maximize2,
    path: "/tools/image-resizer",
  },
  {
    slug: "image-cropper",
    name: "Image Cropper",
    description: "Crop, rotate and flip images with aspect-ratio presets.",
    category: "image",
    icon: Crop,
    path: "/tools/image-cropper",
  },
  {
    slug: "add-text-to-image",
    name: "Add Text to Image",
    description: "Add custom, draggable text layers to any image.",
    category: "image",
    icon: Type,
    path: "/tools/add-text-to-image",
  },
  {
    slug: "image-to-pdf",
    name: "Image to PDF",
    description: "Convert one or many images into a single PDF document.",
    category: "pdf",
    categories: ["image", "pdf"],
    icon: FileImage,
    path: "/tools/image-to-pdf",
  },
  {
    slug: "collage-maker",
    name: "Photo Collage Maker",
    description: "Combine 2–9 photos into a beautiful grid collage.",
    category: "image",
    icon: LayoutGrid,
    path: "/tools/collage-maker",
  },
  {
    slug: "meme-generator",
    name: "Meme Generator",
    description: "Create classic memes from popular templates or your own image.",
    category: "image",
    icon: Laugh,
    path: "/tools/meme-generator",
  },
  {
    slug: "business-card-generator",
    name: "Business Card Generator",
    description: "Design print-ready business cards with QR codes.",
    category: "image",
    icon: CreditCard,
    path: "/tools/business-card-generator",
  },
  {
    slug: "compress-pdf",
    name: "Compress PDF",
    description: "Reduce PDF file size while keeping quality.",
    category: "pdf",
    icon: FileMinus,
    path: "/tools/compress-pdf",
  },
  {
    slug: "pdf-to-images",
    name: "PDF to Images",
    description: "Convert every PDF page into a high-quality PNG image.",
    category: "pdf",
    icon: Layers,
    path: "/tools/pdf-to-images",
  },
  {
    slug: "rotate-pdf",
    name: "Rotate PDF",
    description: "Rotate one or all pages in your PDF to the correct orientation.",
    category: "pdf",
    icon: RotateCw,
    path: "/tools/rotate-pdf",
  },
  {
    slug: "document-scanner",
    name: "Document Scanner",
    description: "Scan documents with camera, auto-crop, enhance and export to PDF.",
    category: "pdf",
    icon: ScanSearch,
    path: "/tools/document-scanner",
  },
  {
    slug: "pdf-to-word",
    name: "PDF to Word",
    description: "Convert PDF files to editable Word documents instantly.",
    category: "pdf",
    icon: FileOutput,
    path: "/tools/pdf-to-word",
  },
  {
    slug: "delete-pdf-pages",
    name: "Delete PDF Pages",
    description: "Remove unwanted pages from any PDF file.",
    category: "pdf",
    icon: FileX,
    path: "/tools/delete-pdf-pages",
  },
  {
    slug: "pdf-page-numbers",
    name: "Add Page Numbers to PDF",
    description: "Add page numbers to any PDF with custom position and style.",
    category: "pdf",
    icon: FilePen,
    path: "/tools/pdf-page-numbers",
  },
  {
    slug: "protect-pdf",
    name: "Protect PDF",
    description: "Add a password to your PDF to prevent unauthorized access.",
    category: "pdf",
    icon: Shield,
    path: "/tools/protect-pdf",
    hidden: true,
  },
  {
    slug: "pdf-reader",
    name: "PDF Reader",
    description: "View and read PDF files directly in your browser.",
    category: "pdf",
    icon: FileSearch,
    path: "/tools/pdf-reader",
  },
  {
    slug: "file-viewer",
    name: "File Viewer",
    description:
      "Open and view Word, Excel, PDF, TXT, Markdown and CSV files instantly in your browser. No upload, no account, no download required.",
    category: "utility",
    categories: ["utility", "pdf", "text"],
    icon: FolderOpen,
    path: "/tools/file-viewer",
  },
  {
    slug: "spinning-wheel",
    name: "Spinning Wheel",
    description: "Spin a customizable wheel to make random decisions. Add your own options.",
    category: "games",
    icon: RotateCw,
    path: "/tools/spinning-wheel",
  },

  {
    slug: "link-shortener",
    name: "Link Shortener",
    description: "Shorten any URL and generate a QR code for it instantly.",
    category: "utility",
    icon: Link,
    path: "/tools/link-shortener",
  },
  {
    slug: "free-time-fixer",
    name: "Free Time Fixer",
    description: "Tell us how many minutes you have free — we'll tell you exactly what to do.",
    category: "utility",
    icon: Clock,
    path: "/tools/free-time-fixer",
  },
  {
    slug: "sleep-calculator",
    name: "Sleep Calculator",
    description: "Find the best time to wake up or go to sleep based on sleep cycles.",
    category: "utility",
    icon: Moon,
    path: "/tools/sleep-calculator",
  },
  {
    slug: "tip-calculator",
    name: "Tip Calculator",
    description: "Calculate tips and split bills instantly.",
    category: "utility",
    icon: Calculator,
    path: "/tools/tip-calculator",
  },
  {
    slug: "bmi-calculator",
    name: "BMI Calculator",
    description: "Calculate your Body Mass Index and healthy weight range.",
    category: "utility",
    icon: Activity,
    path: "/tools/bmi-calculator",
  },
  {
    slug: "age-calculator",
    name: "Age Calculator",
    description: "Calculate your exact age in years, months and days.",
    category: "utility",
    icon: CalendarDays,
    path: "/tools/age-calculator",
  },
  {
    slug: "world-radio",
    name: "World Radio",
    description: "Explore and listen to live radio stations from around the world on an interactive map.",
    category: "utility",
    icon: Radio,
    path: "/tools/world-radio",
  },
  {
    slug: "url-encoder",
    name: "URL Encoder / Decoder",
    description: "Encode or decode URL-safe strings using percent-encoding instantly.",
    category: "text",
    icon: Link2,
    path: "/tools/url-encoder",
  },
  {
    slug: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    description: "Generate placeholder Lorem Ipsum text with custom length and format.",
    category: "text",
    icon: AlignLeft,
    path: "/tools/lorem-ipsum",
  },
  {
    slug: "uuid-generator",
    name: "UUID Generator",
    description: "Generate random UUID v4 identifiers — single or in bulk.",
    category: "text",
    icon: Fingerprint,
    path: "/tools/uuid-generator",
  },
  {
    slug: "hash-generator",
    name: "Hash Generator",
    description: "Compute MD5, SHA-1, SHA-256 and SHA-512 hashes from any text.",
    category: "text",
    icon: Hash,
    path: "/tools/hash-generator",
  },
  {
    slug: "pdf-watermark-remover",
    name: "PDF Watermark Remover",
    description: "Remove watermarks from PDF files entirely in your browser.",
    category: "pdf",
    icon: Stamp,
    path: "/tools/pdf-watermark-remover",
  },
  {
    slug: "role-spinner",
    name: "Role Spinner",
    description: "Randomly assign roles to players. Perfect for Mafia, party games and team activities.",
    category: "games",
    icon: Shuffle,
    path: "/tools/role-spinner",
  },
  {
    slug: "random-team-maker",
    name: "Random Team Maker",
    description: "Split any group of players into balanced random teams instantly.",
    category: "games",
    icon: Users,
    path: "/tools/random-team-maker",
  },
  {
    slug: "truth-or-dare",
    name: "Truth or Dare",
    description: "Spin the bottle and get random Truth or Dare challenges. Perfect for parties and friend groups.",
    category: "games",
    icon: Flame,
    path: "/tools/truth-or-dare",
  },
  {
    slug: "dice-roller",
    name: "Dice Roller",
    description: "Roll multiple dice of any type — D4, D6, D8, D10, D12, D20. Perfect for board games and RPGs.",
    category: "games",
    icon: Dices,
    path: "/tools/dice-roller",
  },
  {
    slug: "wordle",
    name: "Wordle",
    description: "Guess the hidden 5-letter word in 6 tries. A new word every day!",
    category: "minigames",
    icon: Grid2x2,
    path: "/tools/wordle",
  },
  {
    slug: "2048",
    name: "2048",
    description: "Slide tiles and merge numbers to reach 2048. Simple rules, endless challenge.",
    category: "minigames",
    icon: Joystick,
    path: "/tools/2048",
  },
  {
    slug: "tic-tac-toe",
    name: "Tic Tac Toe",
    description: "Classic X and O game. Play against a friend or challenge the AI.",
    category: "minigames",
    icon: X,
    path: "/tools/tic-tac-toe",
  },
  {
    slug: "snake",
    name: "Snake",
    description: "Eat the food, grow longer, don't hit the walls. The classic arcade game!",
    category: "minigames",
    icon: Crosshair,
    path: "/tools/snake",
  },
  {
    slug: "memory-match",
    name: "Memory Match",
    description: "Flip cards and find matching pairs. Train your memory with increasing difficulty!",
    category: "minigames",
    icon: LayoutGrid,
    path: "/tools/memory-match",
  },
  {
    slug: "hangman",
    name: "Hangman",
    description: "Guess the hidden word letter by letter before the hangman is complete!",
    category: "minigames",
    icon: BookOpen,
    path: "/tools/hangman",
  },
  {
    slug: "minesweeper",
    name: "Minesweeper",
    description: "Classic Minesweeper — uncover all safe cells without hitting a mine!",
    category: "minigames",
    icon: Bomb,
    path: "/tools/minesweeper",
  },
  {
    slug: "sudoku",
    name: "Sudoku",
    description: "Fill the 9×9 grid so every row, column and box contains digits 1–9.",
    category: "minigames",
    icon: Hash,
    path: "/tools/sudoku",
  },
  {
    slug: "tetris",
    name: "Tetris",
    description: "Stack falling blocks and clear lines in the ultimate classic arcade game!",
    category: "minigames",
    icon: Layers,
    path: "/tools/tetris",
  },
  {
    slug: "word-search",
    name: "Word Search",
    description: "Find hidden words in the letter grid — horizontally, vertically and diagonally!",
    category: "minigames",
    icon: Search,
    path: "/tools/word-search",
  },
  {
    slug: "typing-speed",
    name: "Typing Speed Test",
    description: "Test your typing speed and accuracy! How many words per minute can you type?",
    category: "minigames",
    icon: Keyboard,
    path: "/tools/typing-speed",
  },
  {
    slug: "flappy-bird",
    name: "Flappy Bird",
    description: "Tap to flap and fly through the pipes! How far can you go?",
    category: "minigames",
    icon: Bird,
    path: "/tools/flappy-bird",
  },
  {
    slug: "chess",
    name: "Chess",
    description: "Play chess against a smart AI opponent. Classic strategy game with full rules support!",
    category: "minigames",
    icon: Crown,
    path: "/tools/chess",
  },
  {
    slug: "connect-four",
    name: "Connect Four",
    description: "Drop discs and connect four in a row before the AI does. Classic strategy game!",
    category: "minigames",
    icon: Circle,
    path: "/tools/connect-four",
  },
  {
    slug: "sliding-puzzle",
    name: "Sliding Puzzle",
    description: "Slide numbered tiles into order in the fewest moves. 3×3, 4×4, or 5×5.",
    category: "minigames",
    icon: Grid2x2,
    path: "/tools/sliding-puzzle",
  },
  {
    slug: "whack-a-mole",
    name: "Whack-a-Mole",
    description: "Tap the moles before they disappear! Classic arcade reaction game.",
    category: "minigames",
    icon: Hammer,
    path: "/tools/whack-a-mole",
  },
  {
    slug: "bubble-shooter",
    name: "Bubble Shooter",
    description: "Aim, shoot, and pop colored bubbles. Match 3 or more before they reach the bottom!",
    category: "minigames",
    icon: Target,
    path: "/tools/bubble-shooter",
  },
  {
    slug: "breakout",
    name: "Breakout",
    description: "Classic brick breaker — bounce the ball and clear all the bricks!",
    category: "minigames",
    icon: Rows3,
    path: "/tools/breakout",
  },
  {
    slug: "pac-man",
    name: "Pac-Man",
    description: "Eat all the dots and avoid the ghosts in this classic arcade maze game!",
    category: "minigames",
    icon: Ghost,
    path: "/tools/pac-man",
  },
  {
    slug: "solitaire",
    name: "Solitaire",
    description: "Classic Klondike Solitaire — move all cards to the foundations to win!",
    category: "minigames",
    icon: Spade,
    path: "/tools/solitaire",
  },
  {
    slug: "mahjong",
    name: "Mahjong Solitaire",
    description: "Classic Mahjong Solitaire — match identical free tiles to clear the board!",
    category: "minigames",
    icon: Puzzle,
    path: "/tools/mahjong",
  },
  {
    slug: "tunnel-dash",
    name: "Tunnel Dash",
    description: "Dig tunnels, collect gems and drop rocks on enemies in this classic arcade digger!",
    category: "minigames",
    icon: Pickaxe,
    path: "/tools/tunnel-dash",
  },
  {
    slug: "pinball",
    name: "Pinball",
    description: "Classic arcade pinball with 3 tables, realistic physics, and full sound effects!",
    category: "minigames",
    icon: Zap,
    path: "/tools/pinball",
  },
  {
    slug: "space-shooter",
    name: "Space Shooter",
    description: "Destroy alien ships and survive the galaxy!",
    category: "minigames",
    icon: Rocket,
    path: "/tools/space-shooter",
  },
  {
    slug: "network-speed-test",
    name: "Network Speed Test",
    description: "Test your internet download, upload, ping and jitter speeds instantly.",
    category: "utility",
    icon: Gauge,
    path: "/tools/network-speed-test",
  },
  {
    slug: "ip-address-lookup",
    name: "IP Address Lookup",
    description: "Look up any IP address to see its country, city, ISP, timezone and coordinates.",
    category: "utility",
    icon: Globe,
    path: "/tools/ip-address-lookup",
  },
  {
    slug: "port-checker",
    name: "Port Checker",
    description: "Check whether a port is open on any host. Quick test for common ports right in your browser.",
    category: "utility",
    icon: Network,
    path: "/tools/port-checker",
  },
  {
    slug: "webrtc-leak-test",
    name: "WebRTC Leak Test",
    description: "Check if WebRTC is leaking your real IP address behind a VPN.",
    category: "utility",
    icon: Wifi,
    path: "/tools/webrtc-leak-test",
  },
  {
    slug: "dns-leak-test",
    name: "DNS & IP Leak Check",
    description: "Check your public IP, detected country and ISP — and compare with your expected VPN location.",
    category: "utility",
    icon: Shield,
    path: "/tools/dns-leak-test",
  },
  {
    slug: "ssh-key-generator",
    name: "SSH Key Generator",
    description: "Generate Ed25519 or RSA SSH key pairs entirely in your browser — no backend, no uploads.",
    category: "utility",
    icon: KeyRound,
    path: "/tools/ssh-key-generator",
  },
  {
    slug: "timetable-generator",
    name: "School Timetable Generator",
    description: "Build school timetables in 10 languages, with logo, classes, teachers, and PDF/Excel export.",
    category: "utility",
    icon: CalendarDays,
    path: "/tools/timetable-generator",
  },
  {
    slug: "youtube-comment-analyzer",
    name: "YouTube Comment Analyzer",
    description: "Fetch and analyze YouTube comments — sentiment, top comments, word cloud.",
    category: "ai",
    icon: MessageSquare,
    path: "/tools/youtube-comment-analyzer",
  },
  {
    slug: "weather-checker",
    name: "Weather Checker",
    description:
      "Check live weather for any city — current conditions, 24-hour forecast, 7-day outlook, UV index, air quality, sunrise and sunset times. Free, no signup.",
    category: "utility",
    icon: CloudSun,
    path: "/tools/weather-checker",
  },
  {
    slug: "holiday-checker",
    name: "Holiday Checker",
    description: "Find public holidays for any country instantly.",
    category: "utility",
    icon: Calendar,
    path: "/tools/holiday-checker",
  },
  {
    slug: "country-info",
    name: "Country Info",
    description: "Explore facts and data for every country in the world.",
    category: "utility",
    icon: Globe,
    path: "/tools/country-info",
  },
  {
    slug: "currency-converter",
    name: "Currency Converter",
    description: "Convert between 170+ currencies with live exchange rates.",
    category: "utility",
    icon: ArrowLeftRight,
    path: "/tools/currency-converter",
  },
  {
    slug: "word-processor",
    name: "Word Processor",
    description:
      "Write and format documents free in your browser. No Google account, no Microsoft account needed. Supports Arabic RTL, exports to PDF and Word.",
    category: "text",
    categories: ["text", "pdf"],
    icon: FileText,
    path: "/tools/word-processor",
  },
  {
    slug: "element-mixer",
    name: "Element Mixer",
    description: "Mix chemical elements and discover real or imaginary compounds in your personal virtual lab.",
    category: "utility",
    icon: FlaskConical,
    path: "/tools/element-mixer",
  },
  {
    slug: "loan-calculator",
    name: "Loan Calculator",
    description: "Calculate monthly payments, total interest and amortization for any loan.",
    category: "utility",
    icon: Calculator,
    path: "/tools/loan-calculator",
  },
  {
    slug: "emi-calculator",
    name: "EMI Calculator",
    description: "Calculate Equated Monthly Installment for personal, home and vehicle loans.",
    category: "utility",
    icon: Calculator,
    path: "/tools/emi-calculator",
  },
  {
    slug: "mortgage-calculator",
    name: "Mortgage Calculator",
    description: "Calculate mortgage payments with PITI: principal, interest, tax, insurance and PMI.",
    category: "utility",
    icon: Calculator,
    path: "/tools/mortgage-calculator",
  },
  {
    slug: "car-loan-calculator",
    name: "Car Loan Calculator",
    description: "Calculate auto loan payments including sales tax, down payment and trade-in value.",
    category: "utility",
    icon: Calculator,
    path: "/tools/car-loan-calculator",
  },
  {
    slug: "compound-interest",
    name: "Compound Interest Calculator",
    description: "Calculate how your investment grows over time with compound interest and monthly contributions.",
    category: "utility",
    icon: Calculator,
    path: "/tools/compound-interest",
  },
  {
    slug: "color-picker",
    name: "Color Picker",
    description:
      "Pick, convert, and generate color palettes. Supports HEX, RGB, HSL, HSB, CMYK. Includes harmony generator, contrast checker, gradient builder, and image color extractor.",
    category: "utility",
    icon: Pipette,
    path: "/tools/color-picker",
  },
  {
    slug: "satoshi-converter",
    name: "Satoshi Converter",
    description:
      "Convert between Bitcoin, Satoshi, mBTC, bits, USD, EUR and MAD instantly. Live BTC price updated every 60 seconds.",
    category: "utility",
    icon: Bitcoin,
    path: "/tools/satoshi-converter",
  },
  {
    slug: "unit-converter",
    name: "Unit Converter",
    description:
      "Convert length, weight, temperature, area, volume, speed, time, data, pressure and energy units instantly.",
    category: "utility",
    icon: Ruler,
    path: "/tools/unit-converter",
  },
  {
    slug: "calorie-calculator",
    name: "Calorie Calculator",
    description: "Calculate your daily calorie needs and macros based on your age, weight, height, and activity level.",
    category: "utility",
    icon: Flame,
    path: "/tools/calorie-calculator",
  },
  {
    slug: "invoice-generator",
    name: "Invoice Generator",
    description:
      "Create professional invoices in seconds. Live preview, 3 templates, multi-currency, logo upload, and instant PDF download. 100% free and private.",
    category: "utility",
    icon: FileText,
    path: "/tools/invoice-generator",
  },
  {
    slug: "ball-sort",
    name: "Ball Sort Puzzle",
    description: "Sort colored balls into matching tubes. 30 free levels, mobile and desktop, no download.",
    category: "minigames",
    icon: CircleDot,
    path: "/tools/ball-sort",
  },
];
