import {
  Download,
  Image as ImageIcon,
  FileText,
  Scissors,
  FileType,
  Combine,
  Minimize2,
  FileImage,
  QrCode,
  ScanLine,
  ScanText,
  Sparkles,
  Volume2,
  Mic,
  Film,
  Lock,
  Code2,
  Type,
  Braces,
  Palette,
  Wand2,
  Stamp,
  Pencil,
  FileCode,
  Monitor,
  Music,
  Video,
  AudioLines,
  Aperture,
  ScanFace,
  Hand,
  Boxes,
  Brain,
  Maximize2,
  Crop,
  LayoutGrid,
  Laugh,
  CreditCard,
  Captions,
  FileMinus,
  Layers,
  RotateCw,
  ScanSearch,
  FileSearch,
  FilePen,
  FileX,
  Shield,
  FileOutput,
  Link,
  Clock,
  Moon,
  Calculator,
  Percent,
  IdCard,
  Landmark,
  Activity,
  CalendarDays,
  Link2,
  AlignLeft,
  Fingerprint,
  Hash,
  Shuffle,
  Scale,
  Users,
  Gamepad2,
  Flame,
  Dices,
  Joystick,
  Grid2x2,
  X,
  Crosshair,
  BookOpen,
  Bomb,
  Search,
  Keyboard,
  Bird,
  Crown,
  Circle,
  CircleDot,
  Hammer,
  Target,
  Rows3,
  Ghost,
  Spade,
  Puzzle,
  Pickaxe,
  Zap,
  Gauge,
  Globe,
  Network,
  Wifi,
  KeyRound,
  Radio,
  MessageSquare,
  CloudSun,
  Calendar,
  ArrowLeftRight,
  Rocket,
  FlaskConical,
  FolderOpen,
  Pipette,
  Bitcoin,
  Ruler,
  Droplets,
  HeartPulse,
  HeartHandshake,
  FileSignature,
  Timer,
  Mail,
  PenLine,
  UserRound,
  Clapperboard,
  Baby,
  Wallet,
  TrendingDown,
  PiggyBank,
  Home,
  BrainCircuit,
  PieChart,
} from "lucide-react";
// Layers already imported above — reused for Tetris.

export type ToolCategory =
  | "video"
  | "image"
  | "pdf"
  | "text"
  | "audio"
  | "ai"
  | "utility"
  | "seo"
  | "games"
  | "minigames";

export const categoryMeta: Record<ToolCategory, { label: string; color: string; icon: string }> = {
  video: { label: "Video Tools", color: "var(--cyan-brand)", icon: "🎬" },
  image: { label: "Image Tools", color: "var(--violet-brand)", icon: "🖼️" },
  audio: { label: "Audio Tools", color: "var(--violet-brand)", icon: "🎙️" },
  pdf: { label: "PDF & Documents", color: "var(--orange-brand)", icon: "📄" },
  text: { label: "Text Tools", color: "var(--green-brand)", icon: "✍️" },
  ai: { label: "AI Tools", color: "var(--violet-brand)", icon: "🤖" },
  utility: { label: "Utility Tools", color: "var(--green-brand)", icon: "🛠️" },
  seo: { label: "SEO Tools", color: "var(--cyan-brand)", icon: "🔎" },
  games: { label: "Game Tools", color: "var(--violet-brand)", icon: "🎲" },
  minigames: { label: "Mini Games", color: "var(--cyan-brand)", icon: "🕹️" },
};

export interface Tool {
  slug: string;
  name: string;
  description: string;
  category: ToolCategory;
  categories?: ToolCategory[];
  icon: typeof Download;
  path: string;
  hidden?: boolean;
  /** ISO date ("YYYY-MM-DD") the tool shipped. Drives the "New" badge via
   *  isNewTool() below — no manual boolean to remember to unset later. */
  dateAdded?: string;
  /** Tool-specific JSON-LD featureList. If omitted, buildToolMeta() falls
   *  back to a generic 4-item list — set this to give the tool its own
   *  accurate structured-data signal instead of duplicate boilerplate. */
  featureList?: string[];
  /** schema.org applicationCategory override (defaults to "WebApplication"
   *  in buildToolMeta() if omitted). */
  schemaCategory?: string;
  /** schema.org @type override — use "VideoGame" for Games/Mini Games tools
   *  that don't already have their own hand-written JSON-LD block; defaults
   *  to "SoftwareApplication". */
  schemaType?: "SoftwareApplication" | "VideoGame";
}

export const toolInCategory = (t: Tool, c: ToolCategory) => t.category === c || (t.categories?.includes(c) ?? false);

/** How long a tool shows a "New" badge after its dateAdded. */
export const NEW_TOOL_WINDOW_DAYS = 45;

export function isNewTool(t: Tool): boolean {
  if (!t.dateAdded) return false;
  const added = new Date(`${t.dateAdded}T00:00:00Z`).getTime();
  if (Number.isNaN(added)) return false;
  const days = (Date.now() - added) / 86_400_000;
  return days >= 0 && days <= NEW_TOOL_WINDOW_DAYS;
}

export const tools: Tool[] = [
  {
    slug: "video-downloader",
    name: "Video Downloader",
    description: "Download videos from TikTok, Instagram, YouTube and more.",
    category: "video",
    icon: Download,
    path: "/tools/video-downloader",
    hidden: true,
  },
  {
    slug: "video-to-gif",
    name: "Video to GIF",
    description: "Convert any video clip to a high-quality animated GIF.",
    category: "video",
    icon: Film,
    path: "/tools/video-to-gif",
    featureList: [
      "Converts MP4, MOV, WebM and more to animated GIF",
      "Adjustable frame rate and output size",
      "No file size limits",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "MultimediaApplication",
  },
  {
    slug: "video-trimmer",
    name: "Video Trimmer",
    description: "Cut and trim video clips instantly in your browser.",
    category: "video",
    icon: Scissors,
    path: "/tools/video-trimmer",
    featureList: [
      "Cut and trim clips by exact start/end time",
      "No re-upload needed to preview changes",
      "Exports in the original video format",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "MultimediaApplication",
  },
  {
    slug: "video-merger",
    name: "Video Merger",
    description: "Combine multiple videos into one — no uploads needed.",
    category: "video",
    icon: Combine,
    path: "/tools/video-merger",
    featureList: [
      "Combine multiple video clips into one file",
      "Reorder clips before merging",
      "No upload to a server required",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "MultimediaApplication",
  },
  {
    slug: "add-subtitles",
    name: "Add Subtitles to Video",
    description: "Burn subtitles into any video right in your browser.",
    category: "video",
    icon: Captions,
    path: "/tools/add-subtitles",
    featureList: [
      "Burns subtitle text permanently into the video",
      "Supports custom timing, font and position",
      "Works with common subtitle (SRT-style) formats",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "MultimediaApplication",
  },
  {
    slug: "image-converter",
    name: "Image Converter",
    description: "Convert PNG, JPG, WebP and AVIF in seconds.",
    category: "image",
    icon: FileImage,
    path: "/tools/image-converter",
    featureList: [
      "Converts between PNG, JPG, WebP and AVIF",
      "Batch conversion of multiple images",
      "Preserves image quality during conversion",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "MultimediaApplication",
  },
  {
    slug: "image-compressor",
    name: "Image Compressor",
    description: "Shrink images without losing quality.",
    category: "image",
    icon: Minimize2,
    path: "/tools/image-compressor",
    featureList: [
      "Shrinks file size with adjustable quality slider",
      "Visual before/after size comparison",
      "Supports JPG, PNG and WebP",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "MultimediaApplication",
  },
  {
    slug: "image-upscaler",
    name: "Image Upscaler",
    description: "Upscale images 2x or 4x with Real-ESRGAN AI.",
    category: "image",
    icon: Sparkles,
    path: "/tools/image-upscaler",
    featureList: [
      "AI-powered 2x or 4x upscaling with Real-ESRGAN",
      "Recovers detail lost in low-resolution images",
      "Works on photos and illustrations",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "MultimediaApplication",
  },
  {
    slug: "remove-bg",
    name: "Remove Background",
    description: "Erase image backgrounds with one click.",
    category: "image",
    icon: Scissors,
    path: "/tools/remove-bg",
    featureList: [
      "One-click automatic background removal",
      "AI-based edge detection for clean cutouts",
      "Exports as transparent PNG",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "MultimediaApplication",
  },
  {
    slug: "pdf-text-extractor",
    name: "Extract Text from PDF",
    description: "Extract all text from any PDF instantly.",
    category: "pdf",
    icon: FileText,
    path: "/tools/pdf-text-extractor",
    featureList: [
      "Extracts all text content from any PDF",
      "Preserves paragraph structure where possible",
      "Copy or download the extracted text",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "BusinessApplication",
  },
  {
    slug: "word-to-pdf",
    name: "Word to PDF",
    description: "Turn Word documents into polished PDFs.",
    category: "pdf",
    icon: FileType,
    path: "/tools/word-to-pdf",
    featureList: [
      "Converts Word documents (.docx) to PDF",
      "Preserves formatting, images and layout",
      "No software installation required",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "BusinessApplication",
  },
  {
    slug: "merge-pdf",
    name: "Merge PDF",
    description: "Combine multiple PDFs into a single file.",
    category: "pdf",
    icon: Combine,
    path: "/tools/merge-pdf",
    featureList: [
      "Combine multiple PDF files into one",
      "Reorder files before merging",
      "No file size or page limits",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "BusinessApplication",
  },
  {
    slug: "qr-generator",
    name: "QR Code Generator",
    description: "Create custom QR codes from any URL or text.",
    category: "utility",
    icon: QrCode,
    path: "/tools/qr-generator",
    featureList: [
      "Creates QR codes from any URL or text",
      "Adjustable size and error-correction level",
      "Download as PNG instantly",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "qr-reader",
    name: "QR Code Reader",
    description: "Decode QR codes from images or your camera.",
    category: "utility",
    icon: ScanLine,
    path: "/tools/qr-reader",
    featureList: [
      "Decodes QR codes from an uploaded image",
      "Also scans live via your camera",
      "Instantly reveals the encoded link or text",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "image-to-text",
    name: "Image to Text (OCR)",
    description: "Extract text from images in multiple languages.",
    category: "image",
    icon: ScanText,
    path: "/tools/image-to-text",
    featureList: [
      "OCR text extraction from photos and screenshots",
      "Supports multiple languages",
      "Copy extracted text directly to clipboard",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "MultimediaApplication",
  },
  {
    slug: "text-to-speech",
    name: "Text to Speech",
    description: "Convert text to natural speech in multiple languages.",
    category: "audio",
    icon: Volume2,
    path: "/tools/text-to-speech",
    featureList: [
      "Converts written text into natural-sounding speech",
      "Multiple languages and voice options",
      "Download the generated audio file",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "MultimediaApplication",
  },
  {
    slug: "speech-to-text",
    name: "Speech to Text",
    description: "Transcribe your voice to text in real-time.",
    category: "audio",
    icon: Mic,
    path: "/tools/speech-to-text",
    featureList: [
      "Real-time transcription of your voice",
      "Supports multiple languages",
      "Copy or export the transcribed text",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "MultimediaApplication",
  },
  {
    slug: "password-generator",
    name: "Password Generator",
    description: "Generate strong, secure passwords instantly.",
    category: "utility",
    icon: Lock,
    path: "/tools/password-generator",
    featureList: [
      "Generates strong, random passwords",
      "Adjustable length and character sets",
      "Copy to clipboard with one click",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "base64",
    name: "Base64 Encoder / Decoder",
    description: "Encode plain text to Base64 or decode Base64 strings instantly.",
    category: "text",
    icon: Code2,
    path: "/tools/base64",
    featureList: [
      "Encodes plain text to Base64",
      "Decodes Base64 strings back to plain text",
      "Instant, real-time conversion",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "word-counter",
    name: "Word Counter",
    description: "Count words, characters, sentences and estimate reading time.",
    category: "text",
    icon: Type,
    path: "/tools/word-counter",
    featureList: [
      "Counts words, characters and sentences live",
      "Estimates reading time",
      "Useful for essays, captions and social posts",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "fancy-text-generator",
    name: "Fancy Text Generator",
    description:
      "Convert plain text into 40+ decorative Unicode styles — bold, italic, cursive, bubble, gothic, upside-down. Instant, copyable.",
    category: "text",
    icon: Sparkles,
    path: "/tools/fancy-text-generator",
  },
  {
    slug: "json-formatter",
    name: "JSON Formatter",
    description: "Format, prettify and minify JSON instantly.",
    category: "text",
    icon: Braces,
    path: "/tools/json-formatter",
    featureList: [
      "Formats and prettifies raw JSON",
      "Minifies JSON for production use",
      "Highlights syntax errors",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "color-palette",
    name: "Color Palette Extractor",
    description: "Extract the dominant colors from any image instantly.",
    category: "image",
    icon: Palette,
    path: "/tools/color-palette",
    featureList: [
      "Extracts the dominant colors from any image",
      "Shows HEX, RGB and HSL values per color",
      "One-click copy for each swatch",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "MultimediaApplication",
  },
  {
    slug: "image-filters",
    name: "Image Filters",
    description: "Apply beautiful filters to your images instantly in the browser.",
    category: "image",
    icon: Wand2,
    path: "/tools/image-filters",
    featureList: [
      "Real-time preview of multiple photo filters",
      "Adjustable brightness, contrast and saturation",
      "Non-destructive — original file is untouched",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "MultimediaApplication",
  },
  {
    slug: "add-watermark",
    name: "Add Watermark",
    description: "Add custom text watermarks to your images in seconds.",
    category: "image",
    icon: Stamp,
    path: "/tools/add-watermark",
    featureList: [
      "Adds custom text watermarks to images",
      "Adjustable position, opacity, size and rotation",
      "Batch-apply to multiple images",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "MultimediaApplication",
  },
  {
    slug: "image-to-sketch",
    name: "Image to Sketch",
    description: "Transform any photo into a pencil or charcoal sketch instantly.",
    category: "image",
    icon: Pencil,
    path: "/tools/image-to-sketch",
    featureList: [
      "Converts photos to pencil or charcoal sketch style",
      "Adjustable sketch intensity",
      "Instant preview before download",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "MultimediaApplication",
  },
  {
    slug: "markdown-to-html",
    name: "Markdown to HTML",
    description: "Convert Markdown to clean HTML with live preview instantly.",
    category: "text",
    icon: FileCode,
    path: "/tools/markdown-to-html",
    featureList: [
      "Converts Markdown to clean HTML",
      "Live side-by-side preview",
      "Copy the generated HTML instantly",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "screen-recorder",
    name: "Screen Recorder",
    description: "Record your screen with audio directly in the browser — no installs needed.",
    category: "video",
    icon: Monitor,
    path: "/tools/screen-recorder",
    featureList: [
      "Records your screen, window, or browser tab",
      "Captures system and microphone audio together",
      "Downloads directly as a video file, no install",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "MultimediaApplication",
  },
  {
    slug: "split-pdf",
    name: "Split PDF",
    description: "Extract specific pages from any PDF file instantly.",
    category: "pdf",
    icon: Scissors,
    path: "/tools/split-pdf",
    featureList: [
      "Extract specific pages or page ranges from a PDF",
      "Preview pages before splitting",
      "Download each part separately",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "BusinessApplication",
  },
  {
    slug: "audio-converter",
    name: "Audio Converter",
    description: "Convert audio files between MP3, WAV, OGG, AAC and FLAC instantly.",
    category: "audio",
    icon: Music,
    path: "/tools/audio-converter",
    featureList: [
      "Converts between MP3, WAV, OGG, AAC and FLAC",
      "Preserves audio quality during conversion",
      "No file size limits",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "MultimediaApplication",
  },
  {
    slug: "video-compressor",
    name: "Video Compressor",
    description: "Reduce video file size without losing quality.",
    category: "video",
    icon: Video,
    path: "/tools/video-compressor",
    featureList: [
      "Reduces file size while preserving visual quality",
      "Adjustable compression level",
      "Ideal for faster uploads and sharing",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "MultimediaApplication",
  },
  {
    slug: "extract-audio",
    name: "Extract Audio from Video",
    description: "Extract MP3, AAC or WAV audio from any video file.",
    category: "video",
    icon: AudioLines,
    path: "/tools/extract-audio",
    featureList: [
      "Extracts audio track from any video file",
      "Choose MP3, AAC or WAV output",
      "Keeps original audio quality",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "MultimediaApplication",
  },
  {
    slug: "background-blur",
    name: "AI Background Blur",
    description: "Blur photo or webcam backgrounds in real time with AI.",
    category: "ai",
    icon: Aperture,
    path: "/tools/background-blur",
    featureList: [
      "AI-powered real-time background blur",
      "Works on photos and live webcam feed",
      "No app install, runs in the browser",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "face-landmarks",
    name: "Face Landmarks",
    description: "Detect 468 facial landmarks on photos or live camera.",
    category: "ai",
    icon: ScanFace,
    path: "/tools/face-landmarks",
    featureList: [
      "Detects 468 facial landmarks in real time",
      "Works with uploaded photos or live camera",
      "Tracks up to 4 faces simultaneously",
      "Toggle between dot and mesh overlay views",
      "Download the annotated image",
      "No signup required",
      "100% browser-based — nothing sent to a server",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "hand-gesture",
    name: "Hand Gesture Recognition",
    description: "Recognize hand gestures in real time from your webcam.",
    category: "ai",
    icon: Hand,
    path: "/tools/hand-gesture",
    featureList: [
      "Recognizes 12 distinct hand gestures in real time",
      "Tracks up to 2 hands simultaneously",
      "Tracks 21 hand landmarks per hand via MediaPipe Hands",
      "Confidence score shown for each detected gesture",
      "Mirror mode and screenshot capture",
      "No signup required",
      "100% browser-based — camera feed never leaves your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "object-detection",
    name: "Object Detection",
    description: "Detect 80 object classes in images or live video with COCO-SSD.",
    category: "ai",
    icon: Boxes,
    path: "/tools/object-detection",
    featureList: [
      "Detects 80 object categories from the COCO dataset",
      "Works with uploaded images or live camera",
      "Draws bounding boxes with confidence scores",
      "Powered by TensorFlow.js COCO-SSD",
      "No signup required",
      "100% browser-based — nothing sent to a server",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "sentiment-analysis",
    name: "AI Sentiment Analysis",
    description: "Analyze the sentiment of any text — positive, negative or neutral.",
    category: "ai",
    icon: Brain,
    path: "/tools/sentiment-analysis",
    featureList: [
      "Analyzes text sentiment as positive, negative or neutral",
      "Instant results as you type or paste",
      "Useful for reviews, feedback and social posts",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "image-resizer",
    name: "Image Resizer",
    description: "Resize images by pixels or percentage with quality control.",
    category: "image",
    icon: Maximize2,
    path: "/tools/image-resizer",
    featureList: [
      "Resize by exact pixels or percentage",
      "Quality control to balance size and clarity",
      "Keeps or unlocks the original aspect ratio",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "MultimediaApplication",
  },
  {
    slug: "image-cropper",
    name: "Image Cropper",
    description: "Crop, rotate and flip images with aspect-ratio presets.",
    category: "image",
    icon: Crop,
    path: "/tools/image-cropper",
    featureList: [
      "Crop, rotate and flip images",
      "Common aspect-ratio presets (1:1, 16:9, 4:3, etc.)",
      "Free-form cropping also supported",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "MultimediaApplication",
  },
  {
    slug: "passport-photo-maker",
    name: "Passport & ID Photo Maker",
    description:
      "Crop, remove the background, and print passport or ID photos in the exact size your country requires.",
    category: "image",
    icon: IdCard,
    path: "/tools/passport-photo-maker",
    featureList: [
      "Official size presets for US, UK, Schengen/EU, Canada and India",
      "Crop box locked to each document's exact aspect ratio",
      "AI background removal composited onto a solid white background",
      "Exports at true 300 DPI in JPG or PNG",
      "Printable 4 × 6 in PDF sheet with multiple copies and cut guides",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "MultimediaApplication",
  },
  {
    slug: "add-text-to-image",
    name: "Add Text to Image",
    description: "Add custom, draggable text layers to any image.",
    category: "image",
    icon: Type,
    path: "/tools/add-text-to-image",
    featureList: [
      "Add multiple draggable text layers to any image",
      "Customize font, size, color and rotation per layer",
      "Export the final flattened image",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "MultimediaApplication",
  },
  {
    slug: "image-to-pdf",
    name: "Image to PDF",
    description: "Convert one or many images into a single PDF document.",
    category: "pdf",
    categories: ["image", "pdf"],
    icon: FileImage,
    path: "/tools/image-to-pdf",
    featureList: [
      "Convert one or multiple images into a single PDF",
      "Reorder images before combining",
      "Supports JPG, PNG and WebP input",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "BusinessApplication",
  },
  {
    slug: "collage-maker",
    name: "Photo Collage Maker",
    description: "Combine 2–9 photos into a beautiful grid collage.",
    category: "image",
    icon: LayoutGrid,
    path: "/tools/collage-maker",
    featureList: [
      "Combine 2 to 9 photos into a grid layout",
      "Multiple layout templates to choose from",
      "Adjustable spacing and border style",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "MultimediaApplication",
  },
  {
    slug: "meme-generator",
    name: "Meme Generator",
    description: "Create classic memes from popular templates or your own image.",
    category: "image",
    icon: Laugh,
    path: "/tools/meme-generator",
    featureList: [
      "Classic meme templates or upload your own image",
      "Top/bottom text with the standard meme font",
      "Instant download, no watermark",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "MultimediaApplication",
  },
  {
    slug: "business-card-generator",
    name: "Business Card Generator",
    description: "Design print-ready business cards with QR codes.",
    category: "image",
    icon: CreditCard,
    path: "/tools/business-card-generator",
    featureList: [
      "Design print-ready business cards",
      "Built-in QR code generation",
      "Multiple layout templates",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "MultimediaApplication",
  },
  {
    slug: "compress-pdf",
    name: "Compress PDF",
    description: "Reduce PDF file size while keeping quality.",
    category: "pdf",
    icon: FileMinus,
    path: "/tools/compress-pdf",
    featureList: [
      "Reduces PDF file size while keeping readability",
      "Adjustable compression level",
      "Ideal for email attachments and uploads",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "BusinessApplication",
  },
  {
    slug: "pdf-to-images",
    name: "PDF to Images",
    description: "Convert every PDF page into a high-quality PNG image.",
    category: "pdf",
    icon: Layers,
    path: "/tools/pdf-to-images",
    featureList: [
      "Converts every PDF page into a high-quality PNG",
      "Batch download of all pages",
      "Adjustable output resolution",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "BusinessApplication",
  },
  {
    slug: "rotate-pdf",
    name: "Rotate PDF",
    description: "Rotate one or all pages in your PDF to the correct orientation.",
    category: "pdf",
    icon: RotateCw,
    path: "/tools/rotate-pdf",
    featureList: [
      "Rotate one page or the entire document",
      "Fix incorrectly scanned or oriented pages",
      "Preview before saving",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "BusinessApplication",
  },
  {
    slug: "document-scanner",
    name: "Document Scanner",
    description: "Scan documents with camera, auto-crop, enhance and export to PDF.",
    category: "pdf",
    icon: ScanSearch,
    path: "/tools/document-scanner",
    featureList: [
      "Scans documents using your camera",
      "Automatic edge detection and cropping",
      "Enhances contrast and exports to PDF",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "BusinessApplication",
  },
  {
    slug: "pdf-to-word",
    name: "PDF to Word",
    description: "Convert PDF files to editable Word documents instantly.",
    category: "pdf",
    icon: FileOutput,
    path: "/tools/pdf-to-word",
    featureList: [
      "Converts PDF files into editable Word documents",
      "Preserves text formatting and layout",
      "No signup, instant download",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "BusinessApplication",
  },
  {
    slug: "delete-pdf-pages",
    name: "Delete PDF Pages",
    description: "Remove unwanted pages from any PDF file.",
    category: "pdf",
    icon: FileX,
    path: "/tools/delete-pdf-pages",
    featureList: [
      "Remove specific unwanted pages from a PDF",
      "Visual page picker before deleting",
      "Download the cleaned-up file instantly",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "BusinessApplication",
  },
  {
    slug: "pdf-page-numbers",
    name: "Add Page Numbers to PDF",
    description: "Add page numbers to any PDF with custom position and style.",
    category: "pdf",
    icon: FilePen,
    path: "/tools/pdf-page-numbers",
    featureList: [
      "Adds page numbers to any PDF",
      "Customizable position and number style",
      "Preview before applying",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "BusinessApplication",
  },
  {
    slug: "protect-pdf",
    name: "Protect PDF",
    description: "Add a password to your PDF to prevent unauthorized access.",
    category: "pdf",
    icon: Shield,
    path: "/tools/protect-pdf",
    hidden: true,
  },
  {
    slug: "pdf-reader",
    name: "PDF Reader",
    description: "View and read PDF files directly in your browser.",
    category: "pdf",
    icon: FileSearch,
    path: "/tools/pdf-reader",
    featureList: [
      "View PDF files directly in the browser",
      "No download or installation needed",
      "Zoom, scroll and page navigation",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "BusinessApplication",
  },
  {
    slug: "file-viewer",
    name: "File Viewer",
    description:
      "Open and view Word, Excel, PDF, TXT, Markdown and CSV files instantly in your browser. No upload, no account, no download required.",
    category: "utility",
    categories: ["utility", "pdf", "text"],
    icon: FolderOpen,
    path: "/tools/file-viewer",
    featureList: [
      "Opens Word, Excel, PDF, TXT, Markdown and CSV files",
      "No upload, no account required",
      "Renders documents directly in the browser",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "spinning-wheel",
    name: "Spinning Wheel",
    description: "Spin a customizable wheel to make random decisions. Add your own options.",
    category: "games",
    icon: RotateCw,
    path: "/tools/spinning-wheel",
    featureList: [
      "Fully customizable wheel with your own options",
      "Instant random selection with animation",
      "Great for giveaways and group decisions",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },

  {
    slug: "link-shortener",
    name: "Link Shortener",
    description: "Shorten any URL and generate a QR code for it instantly.",
    category: "utility",
    icon: Link,
    path: "/tools/link-shortener",
    featureList: [
      "Shortens any long URL instantly",
      "Generates a matching QR code",
      "No account needed to create a short link",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "free-time-fixer",
    name: "Free Time Fixer",
    description: "Tell us how many minutes you have free — we'll tell you exactly what to do.",
    category: "utility",
    icon: Clock,
    path: "/tools/free-time-fixer",
    featureList: [
      "Suggests activities based on your available minutes",
      "Quick decision-making for short breaks",
      "No signup or setup required",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "sleep-calculator",
    name: "Sleep Calculator",
    description: "Find the best time to wake up or go to sleep based on sleep cycles.",
    category: "utility",
    icon: Moon,
    path: "/tools/sleep-calculator",
    featureList: [
      "Calculates ideal wake-up or bedtime by sleep cycle",
      "Based on 90-minute sleep cycle science",
      "Works backward or forward from a target time",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "tip-calculator",
    name: "Tip Calculator",
    description: "Calculate tips and split bills instantly.",
    category: "utility",
    icon: Calculator,
    path: "/tools/tip-calculator",
    featureList: [
      "Calculates tip amount and total bill",
      "Splits the bill evenly between any number of people",
      "Adjustable tip percentage",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "income-tax-calculator",
    name: "Income Tax Calculator",
    description: "Estimate your annual US federal income tax, effective rate, and refund or amount owed.",
    category: "utility",
    icon: Landmark,
    path: "/tools/income-tax-calculator",
    dateAdded: "2026-07-30",
    featureList: [
      "2026 US federal tax brackets and standard deduction",
      "All four filing statuses",
      "Standard vs itemized deduction — uses whichever is larger",
      "Taxable income, federal tax owed, effective and marginal rates",
      "Bracket-by-bracket breakdown chart and table",
      "Optional refund or amount-owed estimate from tax already withheld",
      "Instant results as you type",
      "No signup required",
      "100% browser-based",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "percentage-calculator",
    name: "Percentage Calculator",
    description: "Calculate percentages, percentage change, and percentage increase or decrease instantly.",
    category: "utility",
    icon: Percent,
    path: "/tools/percentage-calculator",
    dateAdded: "2026-07-30",
    featureList: [
      "Finds X% of any number",
      "Works out what percent one number is of another",
      "Percentage change between two values, with increase or decrease indicated",
      "Increases or decreases a number by a percentage",
      "Instant results as you type",
      "No signup required",
      "100% browser-based",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "margin-calculator",
    name: "Margin Calculator",
    description: "Calculate gross margin, markup and profit from cost and revenue.",
    category: "utility",
    icon: Percent,
    path: "/tools/margin-calculator",
    featureList: [
      "Calculates gross margin, markup and profit",
      "Works from either cost or revenue as the input",
      "Instant results as you type",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "bmi-calculator",
    name: "BMI Calculator",
    description: "Calculate your Body Mass Index and healthy weight range.",
    category: "utility",
    icon: Activity,
    path: "/tools/bmi-calculator",
    featureList: [
      "Calculates Body Mass Index from height and weight",
      "Shows your healthy weight range",
      "Supports metric and imperial units",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "age-calculator",
    name: "Age Calculator",
    description: "Calculate your exact age in years, months and days.",
    category: "utility",
    icon: CalendarDays,
    path: "/tools/age-calculator",
    featureList: [
      "Calculates exact age in years, months and days",
      "Counts down to the next birthday",
      "Supports any two dates, not just today",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "world-radio",
    name: "World Radio",
    description: "Explore and listen to live radio stations from around the world on an interactive map.",
    category: "utility",
    icon: Radio,
    path: "/tools/world-radio",
    featureList: [
      "Streams live radio stations from around the world",
      "Interactive map-based station browser",
      "No signup, no app install",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "url-encoder",
    name: "URL Encoder / Decoder",
    description: "Encode or decode URL-safe strings using percent-encoding instantly.",
    category: "text",
    icon: Link2,
    path: "/tools/url-encoder",
    featureList: [
      "Encodes text into URL-safe percent-encoding",
      "Decodes percent-encoded strings back to plain text",
      "Handles special characters correctly",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    description: "Generate placeholder Lorem Ipsum text with custom length and format.",
    category: "text",
    icon: AlignLeft,
    path: "/tools/lorem-ipsum",
    featureList: [
      "Generates placeholder Lorem Ipsum text",
      "Custom length by words, sentences or paragraphs",
      "Copy directly into any design or document",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "uuid-generator",
    name: "UUID Generator",
    description: "Generate random UUID v4 identifiers — single or in bulk.",
    category: "text",
    icon: Fingerprint,
    path: "/tools/uuid-generator",
    featureList: [
      "Generates random UUID v4 identifiers",
      "Single or bulk generation",
      "One-click copy per UUID",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "hash-generator",
    name: "Hash Generator",
    description: "Compute MD5, SHA-1, SHA-256 and SHA-512 hashes from any text.",
    category: "text",
    icon: Hash,
    path: "/tools/hash-generator",
    featureList: [
      "Computes MD5, SHA-1, SHA-256 and SHA-512 hashes",
      "Instant hashing as you type",
      "Useful for checksums and data verification",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "pdf-watermark-remover",
    name: "PDF Watermark Remover",
    description: "Remove watermarks from PDF files entirely in your browser.",
    category: "pdf",
    icon: Stamp,
    path: "/tools/pdf-watermark-remover",
    featureList: [
      "Removes watermarks from PDF files",
      "Processes entirely in the browser",
      "No file uploaded to a server",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "BusinessApplication",
  },
  {
    slug: "role-spinner",
    name: "Role Spinner",
    description: "Randomly assign roles to players. Perfect for Mafia, party games and team activities.",
    category: "games",
    icon: Shuffle,
    path: "/tools/role-spinner",
    featureList: [
      "Randomly assigns roles to a group of players",
      "Ideal for Mafia, Werewolf and party games",
      "No signup, unlimited replays",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "random-team-maker",
    name: "Random Team Maker",
    description: "Split any group of players into balanced random teams instantly.",
    category: "games",
    icon: Users,
    path: "/tools/random-team-maker",
    featureList: [
      "Splits any group into balanced random teams",
      "Supports custom number of teams",
      "Instant re-shuffle for a new split",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "truth-or-dare",
    name: "Truth or Dare",
    description: "Spin the bottle and get random Truth or Dare challenges. Perfect for parties and friend groups.",
    category: "games",
    icon: Flame,
    path: "/tools/truth-or-dare",
    featureList: [
      "40+ built-in Truth or Dare prompts for any group size",
      "Truth-only, Dare-only, or mixed mode",
      "Add your own custom truths and dares",
      "Great for parties and friend gatherings",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "would-you-rather",
    name: "Would You Rather",
    description:
      "160+ Would You Rather questions across 8 categories — funny, deep, couples, kids-friendly and more. Add your own, no signup.",
    category: "games",
    icon: Scale,
    path: "/tools/would-you-rather",
    featureList: [
      "170+ hand-written questions across 8 categories",
      "Funny, Deep, Gross, Hard Choices, Kids-Friendly, Couples, Work, Fantasy",
      "Add your own custom questions to the session",
      "Session-local vote tally per question",
      "One-tap next question for fast group play",
      "No signup, unlimited plays",
      "Mobile-friendly",
    ],
    schemaCategory: "GameApplication",
  },
  {
    slug: "never-have-i-ever",
    name: "Never Have I Ever",
    description:
      "Play Never Have I Ever online — 160 original questions across 7 categories, category filters, no-repeat shuffle and your own custom questions. No signup.",
    category: "games",
    icon: Sparkles,
    path: "/tools/never-have-i-ever",
    dateAdded: "2026-07-28",
    featureList: [
      "160 original Never Have I Ever questions",
      "7 category filters: Funny, Embarrassing, Travel, Food, Dating, School & Work, Bold",
      "No-repeat shuffle until the whole category pool is used",
      "Add and delete your own custom questions",
      "Use-custom-only mode to play from your list alone",
      "Custom questions saved in your browser, never uploaded",
      "Session counter of questions shown",
      "No signup, unlimited plays, mobile-friendly",
    ],
    schemaCategory: "GameApplication",
  },
  {
    slug: "dice-roller",
    name: "Dice Roller",
    description: "Roll multiple dice of any type — D4, D6, D8, D10, D12, D20. Perfect for board games and RPGs.",
    category: "games",
    icon: Dices,
    path: "/tools/dice-roller",
    featureList: [
      "Rolls D4, D6, D8, D10, D12 and D20 dice",
      "Roll multiple dice at once",
      "Perfect for board games and tabletop RPGs",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "wordle",
    name: "Wordle",
    description: "Guess the hidden 5-letter word in 6 tries. A new word every day!",
    category: "minigames",
    icon: Grid2x2,
    path: "/tools/wordle",
    featureList: [
      "Guess the hidden 5-letter word in 6 tries",
      "A brand-new word every day",
      "Share your result as a colored emoji grid",
      "Free to play, no download",
      "No signup required",
    ],
    schemaType: "VideoGame",
  },
  {
    slug: "2048",
    name: "2048",
    description: "Slide tiles and merge numbers to reach 2048. Simple rules, endless challenge.",
    category: "minigames",
    icon: Joystick,
    path: "/tools/2048",
    featureList: [
      "Slide and merge numbered tiles to reach 2048",
      "Simple one-tap/swipe controls",
      "Tracks your best score",
      "Free to play, no download",
      "No signup required",
    ],
    schemaType: "VideoGame",
  },
  {
    slug: "tic-tac-toe",
    name: "Tic Tac Toe",
    description: "Classic X and O game. Play against a friend or challenge the AI.",
    category: "minigames",
    icon: X,
    path: "/tools/tic-tac-toe",
    featureList: [
      "Classic 3x3 grid game",
      "Play against a friend or the built-in AI",
      "Instant rematch",
      "Free to play, no download",
      "No signup required",
    ],
    schemaType: "VideoGame",
  },
  {
    slug: "snake",
    name: "Snake",
    description: "Eat the food, grow longer, don't hit the walls. The classic arcade game!",
    category: "minigames",
    icon: Crosshair,
    path: "/tools/snake",
    featureList: [
      "Classic snake arcade game",
      "Increasing difficulty as you grow longer",
      "Keyboard and touch controls supported",
      "Free to play, no download",
      "No signup required",
    ],
    schemaType: "VideoGame",
  },
  {
    slug: "memory-match",
    name: "Memory Match",
    description: "Flip cards and find matching pairs. Train your memory with increasing difficulty!",
    category: "minigames",
    icon: LayoutGrid,
    path: "/tools/memory-match",
    featureList: [
      "Flip cards to find matching pairs",
      "Multiple difficulty levels",
      "Tracks moves and completion time",
      "Free to play, no download",
      "No signup required",
    ],
    schemaType: "VideoGame",
  },
  {
    slug: "hangman",
    name: "Hangman",
    description: "Guess the hidden word letter by letter before the hangman is complete!",
    category: "minigames",
    icon: BookOpen,
    path: "/tools/hangman",
    featureList: [
      "Classic word-guessing game",
      "Guess the hidden word letter by letter",
      "Multiple word categories",
      "Free to play, no download",
      "No signup required",
    ],
    schemaType: "VideoGame",
  },
  {
    slug: "minesweeper",
    name: "Minesweeper",
    description: "Classic Minesweeper — uncover all safe cells without hitting a mine!",
    category: "minigames",
    icon: Bomb,
    path: "/tools/minesweeper",
    featureList: [
      "Classic Minesweeper logic puzzle",
      "Multiple grid sizes and difficulty levels",
      "Flag suspected mines as you play",
      "Free to play, no download",
      "No signup required",
    ],
    schemaType: "VideoGame",
  },
  {
    slug: "sudoku",
    name: "Sudoku",
    description: "Fill the 9×9 grid so every row, column and box contains digits 1–9.",
    category: "minigames",
    icon: Hash,
    path: "/tools/sudoku",
    featureList: [
      "Classic 9x9 Sudoku puzzle generator",
      "Multiple difficulty levels",
      "Built-in mistake checking",
      "Free to play, no download",
      "No signup required",
    ],
    schemaType: "VideoGame",
  },
  {
    slug: "tetris",
    name: "Tetris",
    description: "Stack falling blocks and clear lines in the ultimate classic arcade game!",
    category: "minigames",
    icon: Layers,
    path: "/tools/tetris",
    featureList: [
      "Classic falling-block puzzle game",
      "Increasing speed as you clear lines",
      "Keyboard controls with next-piece preview",
      "Free to play, no download",
      "No signup required",
    ],
    schemaType: "VideoGame",
  },
  {
    slug: "word-search",
    name: "Word Search",
    description: "Find hidden words in the letter grid — horizontally, vertically and diagonally!",
    category: "minigames",
    icon: Search,
    path: "/tools/word-search",
    featureList: [
      "Find hidden words in a letter grid",
      "Words hidden horizontally, vertically and diagonally",
      "Multiple themed puzzles",
      "Free to play, no download",
      "No signup required",
    ],
    schemaType: "VideoGame",
  },
  {
    slug: "word-groups",
    name: "Word Groups",
    description:
      "Sort 16 words into 4 hidden groups in this free connections-style daily word puzzle. New puzzle every day, unlimited practice mode, and free archive of every past puzzle.",
    category: "minigames",
    icon: LayoutGrid,
    path: "/tools/word-groups",
    dateAdded: "2026-07-15",
    featureList: [
      "Sort 16 words into 4 hidden category groups daily",
      "Free archive of every past puzzle",
      "Unlimited practice mode beyond the daily puzzle",
      "Free to play, no download",
      "No signup required",
    ],
    schemaType: "VideoGame",
  },
  {
    slug: "crossword",
    name: "Daily Crossword Puzzle",
    description:
      "Solve a free crossword puzzle every day online. Unlimited practice grids, a free archive of every past puzzle, and printable PDF worksheets with answer keys.",
    category: "minigames",
    icon: LayoutGrid,
    path: "/tools/crossword",
    dateAdded: "2026-07-28",
    featureList: [
      "New crossword puzzle every day",
      "Free archive of every past daily puzzle",
      "Unlimited practice mode",
      "Printable PDF worksheet with answer key",
      "Check and reveal helpers with a solve timer",
      "No signup required",
    ],
    schemaType: "VideoGame",
  },
  {
    slug: "maze-puzzle",
    name: "Maze Puzzle",
    description:
      "Play an endless maze game online free, then print the exact maze with an answer key. Four real grid sizes, emoji themes, fog of war — no signup, no premium tier.",
    category: "minigames",
    icon: LayoutGrid,
    path: "/tools/maze-puzzle",
    dateAdded: "2026-07-28",
    featureList: [
      "Endless freshly generated mazes",
      "Four real grid sizes from 11x11 to 35x35",
      "Arrow keys, WASD, swipe, or on-screen D-pad controls",
      "Breadcrumb trail and optional fog of war",
      "Reveal the correct path at any time",
      "Printable PDF worksheet with a separate answer key",
      "Timer, move counter and local best times",
      "No signup required",
    ],
    schemaType: "VideoGame",
  },
  {
    slug: "typing-speed",
    name: "Typing Speed Test",
    description: "Test your typing speed and accuracy! How many words per minute can you type?",
    category: "minigames",
    icon: Keyboard,
    path: "/tools/typing-speed",
    featureList: [
      "Measures your typing speed in words per minute",
      "Tracks accuracy alongside speed",
      "Instant results after each test",
      "Free to play, no download",
      "No signup required",
    ],
    schemaType: "VideoGame",
  },
  {
    slug: "flappy-bird",
    name: "Flappy Bird",
    description: "Tap to flap and fly through the pipes! How far can you go?",
    category: "minigames",
    icon: Bird,
    path: "/tools/flappy-bird",
    featureList: [
      "Classic tap-to-fly arcade game",
      "Simple one-tap controls",
      "Tracks your best score",
      "Free to play, no download",
      "No signup required",
    ],
    schemaType: "VideoGame",
  },
  {
    slug: "chess",
    name: "Chess",
    description: "Play chess against a smart AI opponent. Classic strategy game with full rules support!",
    category: "minigames",
    icon: Crown,
    path: "/tools/chess",
    featureList: [
      "Full chess rules with a built-in AI opponent",
      "Legal move highlighting",
      "Play at your own pace, no time limit",
      "Free to play, no download",
      "No signup required",
    ],
    schemaType: "VideoGame",
  },
  {
    slug: "connect-four",
    name: "Connect Four",
    description: "Drop discs and connect four in a row before the AI does. Classic strategy game!",
    category: "minigames",
    icon: Circle,
    path: "/tools/connect-four",
    featureList: [
      "Classic Connect Four strategy game",
      "Play against the built-in AI",
      "Clean, simple board interface",
      "Free to play, no download",
      "No signup required",
    ],
    schemaType: "VideoGame",
  },
  {
    slug: "sliding-puzzle",
    name: "Sliding Puzzle",
    description: "Slide numbered tiles into order in the fewest moves. 3×3, 4×4, or 5×5.",
    category: "minigames",
    icon: Grid2x2,
    path: "/tools/sliding-puzzle",
  },
  {
    slug: "whack-a-mole",
    name: "Whack-a-Mole",
    description: "Tap the moles before they disappear! Classic arcade reaction game.",
    category: "minigames",
    icon: Hammer,
    path: "/tools/whack-a-mole",
  },
  {
    slug: "bubble-shooter",
    name: "Bubble Shooter",
    description: "Aim, shoot, and pop colored bubbles. Match 3 or more before they reach the bottom!",
    category: "minigames",
    icon: Target,
    path: "/tools/bubble-shooter",
  },
  {
    slug: "breakout",
    name: "Breakout",
    description: "Classic brick breaker — bounce the ball and clear all the bricks!",
    category: "minigames",
    icon: Rows3,
    path: "/tools/breakout",
  },
  {
    slug: "pac-man",
    name: "Pac-Man",
    description: "Eat all the dots and avoid the ghosts in this classic arcade maze game!",
    category: "minigames",
    icon: Ghost,
    path: "/tools/pac-man",
  },
  {
    slug: "solitaire",
    name: "Solitaire",
    description: "Classic Klondike Solitaire — move all cards to the foundations to win!",
    category: "minigames",
    icon: Spade,
    path: "/tools/solitaire",
  },
  {
    slug: "mahjong",
    name: "Mahjong Solitaire",
    description: "Classic Mahjong Solitaire — match identical free tiles to clear the board!",
    category: "minigames",
    icon: Puzzle,
    path: "/tools/mahjong",
  },
  {
    slug: "tunnel-dash",
    name: "Tunnel Dash",
    description: "Dig tunnels, collect gems and drop rocks on enemies in this classic arcade digger!",
    category: "minigames",
    icon: Pickaxe,
    path: "/tools/tunnel-dash",
  },
  {
    slug: "pinball",
    name: "Pinball",
    description: "Classic arcade pinball with 3 tables, realistic physics, and full sound effects!",
    category: "minigames",
    icon: Zap,
    path: "/tools/pinball",
  },
  {
    slug: "space-shooter",
    name: "Space Shooter",
    description: "Destroy alien ships and survive the galaxy!",
    category: "minigames",
    icon: Rocket,
    path: "/tools/space-shooter",
    featureList: [
      "Fast-paced arcade space shooter",
      "Increasing enemy waves as you progress",
      "Keyboard and touch controls",
      "Free to play, no download",
      "No signup required",
    ],
    schemaType: "VideoGame",
  },
  {
    slug: "network-speed-test",
    name: "Network Speed Test",
    description: "Test your internet download, upload, ping and jitter speeds instantly.",
    category: "utility",
    icon: Gauge,
    path: "/tools/network-speed-test",
    featureList: [
      "Tests download, upload, ping and jitter",
      "Runs entirely from your browser",
      "Results in seconds, no app install",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "ip-address-lookup",
    name: "IP Address Lookup",
    description: "Look up any IP address to see its country, city, ISP, timezone and coordinates.",
    category: "utility",
    icon: Globe,
    path: "/tools/ip-address-lookup",
    featureList: [
      "Looks up any IP address's location and ISP",
      "Shows country, city, timezone and coordinates",
      "Works for both IPv4 and IPv6",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "port-checker",
    name: "Port Checker",
    description: "Check whether a port is open on any host. Quick test for common ports right in your browser.",
    category: "utility",
    icon: Network,
    path: "/tools/port-checker",
    featureList: [
      "Checks whether a specific port is open on a host",
      "Tests common service ports instantly",
      "No software installation required",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "webrtc-leak-test",
    name: "WebRTC Leak Test",
    description: "Check if WebRTC is leaking your real IP address behind a VPN.",
    category: "utility",
    icon: Wifi,
    path: "/tools/webrtc-leak-test",
    featureList: [
      "Detects if WebRTC is exposing your real IP behind a VPN",
      "Runs entirely in your browser",
      "Clear pass/fail result",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "dns-leak-test",
    name: "DNS & IP Leak Check",
    description: "Check your public IP, detected country and ISP — and compare with your expected VPN location.",
    category: "utility",
    icon: Shield,
    path: "/tools/dns-leak-test",
    featureList: [
      "Checks your public IP, country and ISP",
      "Compares against your expected VPN location",
      "Helps verify VPN configuration",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "ssh-key-generator",
    name: "SSH Key Generator",
    description: "Generate Ed25519 or RSA SSH key pairs entirely in your browser — no backend, no uploads.",
    category: "utility",
    icon: KeyRound,
    path: "/tools/ssh-key-generator",
    featureList: [
      "Generates Ed25519 or RSA SSH key pairs",
      "Runs entirely client-side, no backend involved",
      "Private key never leaves your browser",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "timetable-generator",
    name: "School Timetable Generator",
    description: "Build school timetables in 10 languages, with logo, classes, teachers, and PDF/Excel export.",
    category: "utility",
    icon: CalendarDays,
    path: "/tools/timetable-generator",
    featureList: [
      "Builds school timetables with classes and teachers",
      "Available in 10 languages",
      "Exports to PDF or Excel with your logo",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "youtube-comment-analyzer",
    name: "YouTube Comment Analyzer",
    description: "Fetch and analyze YouTube comments — sentiment, top comments, word cloud.",
    category: "ai",
    icon: MessageSquare,
    path: "/tools/youtube-comment-analyzer",
    featureList: [
      "Fetches and analyzes comments from any YouTube video",
      "Sentiment breakdown and top comments",
      "Generates a word cloud of common themes",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "weather-checker",
    name: "Weather Checker",
    description:
      "Check live weather for any city — current conditions, 24-hour forecast, 7-day outlook, UV index, air quality, sunrise and sunset times. Free, no signup.",
    category: "utility",
    icon: CloudSun,
    path: "/tools/weather-checker",
    featureList: [
      "Live current conditions for any city",
      "24-hour and 7-day forecast",
      "UV index, air quality, sunrise and sunset times",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "holiday-checker",
    name: "Holiday Checker",
    description: "Find public holidays for any country instantly.",
    category: "utility",
    icon: Calendar,
    path: "/tools/holiday-checker",
    featureList: [
      "Finds public holidays for any country",
      "Covers the full calendar year",
      "Useful for planning international meetings or trips",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "country-info",
    name: "Country Info",
    description: "Explore facts and data for every country in the world.",
    category: "utility",
    icon: Globe,
    path: "/tools/country-info",
    featureList: [
      "Explores key facts and data for every country",
      "Population, currency, languages and more",
      "Instant search by country name",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "time-zone-converter",
    name: "Time Zone Converter",
    description:
      "Convert time between any two cities instantly. Live world clock for 90+ cities, meeting planner for remote teams, and specific time converter. Free, no signup.",
    category: "utility",
    icon: Clock,
    path: "/tools/time-zone-converter",
  },
  {
    slug: "currency-converter",
    name: "Currency Converter",
    description: "Convert between 170+ currencies with live exchange rates.",
    category: "utility",
    icon: ArrowLeftRight,
    path: "/tools/currency-converter",
    featureList: [
      "Converts between 170+ world currencies",
      "Uses live, regularly updated exchange rates",
      "Instant conversion as you type",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "word-processor",
    name: "Word Processor",
    description:
      "Write and format documents free in your browser. No Google account, no Microsoft account needed. Supports Arabic RTL, exports to PDF and Word.",
    category: "text",
    categories: ["text", "pdf"],
    icon: FileText,
    path: "/tools/word-processor",
    featureList: [
      "Full document editor running in your browser",
      "No Google or Microsoft account required",
      "Supports Arabic RTL text and exports to PDF/Word",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "element-mixer",
    name: "Element Mixer",
    description: "Mix chemical elements and discover real or imaginary compounds in your personal virtual lab.",
    category: "utility",
    icon: FlaskConical,
    path: "/tools/element-mixer",
    featureList: [
      "Mix up to 6 chemical elements at once in a virtual lab",
      "Discover real and imaginary compounds",
      "Lab Progress tracker with unlockable category badges",
      "Fun, hands-on way to explore chemistry",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "loan-calculator",
    name: "Loan Calculator",
    description: "Calculate monthly payments, total interest and amortization for any loan.",
    category: "utility",
    icon: Calculator,
    path: "/tools/loan-calculator",
    featureList: [
      "Calculates monthly payments for any loan",
      "Shows total interest paid over the loan term",
      "Full amortization schedule included",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "emi-calculator",
    name: "EMI Calculator",
    description: "Calculate Equated Monthly Installment for personal, home and vehicle loans.",
    category: "utility",
    icon: Calculator,
    path: "/tools/emi-calculator",
    featureList: [
      "Calculates Equated Monthly Installment (EMI)",
      "Works for personal, home and vehicle loans",
      "Instant results as you adjust the inputs",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "mortgage-calculator",
    name: "Mortgage Calculator",
    description: "Calculate mortgage payments with PITI: principal, interest, tax, insurance and PMI.",
    category: "utility",
    icon: Calculator,
    path: "/tools/mortgage-calculator",
    featureList: [
      "Calculates full PITI mortgage payments",
      "Includes principal, interest, tax, insurance and PMI",
      "Shows the complete amortization schedule",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "car-loan-calculator",
    name: "Car Loan Calculator",
    description: "Calculate auto loan payments including sales tax, down payment and trade-in value.",
    category: "utility",
    icon: Calculator,
    path: "/tools/car-loan-calculator",
    featureList: [
      "Calculates auto loan monthly payments",
      "Accounts for sales tax, down payment and trade-in",
      "Shows total interest over the loan term",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "compound-interest",
    name: "Compound Interest Calculator",
    description: "Calculate how your investment grows over time with compound interest and monthly contributions.",
    category: "utility",
    icon: Calculator,
    path: "/tools/compound-interest",
    featureList: [
      "Projects investment growth over time",
      "Supports recurring monthly contributions",
      "Visual chart of balance growth",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "paycheck-calculator",
    name: "Paycheck Calculator",
    description: "Estimate US take-home pay after federal tax, state tax, FICA and pre-tax deductions.",
    category: "utility",
    icon: Wallet,
    path: "/tools/paycheck-calculator",
    dateAdded: "2026-07-15",
  },
  {
    slug: "insurance-estimator",
    name: "Insurance Estimator",
    description: "Estimate life insurance coverage needs and car insurance premiums — no signup, no email.",
    category: "utility",
    icon: Shield,
    path: "/tools/insurance-estimator",
    dateAdded: "2026-07-15",
  },
  {
    slug: "debt-payoff-calculator",
    name: "Debt Payoff Calculator",
    description:
      "Compare debt snowball vs avalanche side by side. Enter your debts and see months to debt-free, total interest, and interest saved.",
    category: "utility",
    icon: TrendingDown,
    path: "/tools/debt-payoff-calculator",
    dateAdded: "2026-07-15",
  },
  {
    slug: "rent-vs-buy-calculator",
    name: "Rent vs Buy Calculator",
    description:
      "Find your breakeven year for buying vs renting. Full cost of ownership, opportunity cost of the down payment, and interactive assumptions.",
    category: "utility",
    icon: Home,
    path: "/tools/rent-vs-buy-calculator",
    dateAdded: "2026-07-15",
  },
  {
    slug: "retirement-calculator",
    name: "Retirement Calculator",
    description:
      "Project your 401(k) at retirement as a conservative-to-optimistic range with real tiered employer match and inflation-adjusted values. No signup.",
    category: "utility",
    icon: PiggyBank,
    path: "/tools/retirement-calculator",
    dateAdded: "2026-07-18",
  },
  {
    slug: "color-picker",
    name: "Color Picker",
    description:
      "Pick, convert, and generate color palettes. Supports HEX, RGB, HSL, HSB, CMYK. Includes harmony generator, contrast checker, gradient builder, and image color extractor.",
    category: "utility",
    icon: Pipette,
    path: "/tools/color-picker",
    featureList: [
      "Pick and convert colors across HEX, RGB, HSL, HSB and CMYK",
      "Built-in color harmony generator",
      "Contrast checker and gradient builder included",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "satoshi-converter",
    name: "Satoshi Converter",
    description:
      "Convert between Bitcoin, Satoshi, mBTC, bits, USD, EUR and MAD instantly. Live BTC price updated every 60 seconds.",
    category: "utility",
    icon: Bitcoin,
    path: "/tools/satoshi-converter",
    featureList: [
      "Converts between Bitcoin, Satoshi, mBTC and bits",
      "Also converts to USD, EUR and MAD",
      "Live BTC price updated every 60 seconds",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "unit-converter",
    name: "Unit Converter",
    description:
      "Convert length, weight, temperature, area, volume, speed, time, data, pressure and energy units instantly.",
    category: "utility",
    icon: Ruler,
    path: "/tools/unit-converter",
    featureList: [
      "Converts length, weight, temperature, area and volume",
      "Also covers speed, time, data, pressure and energy",
      "Instant conversion as you type",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "calorie-calculator",
    name: "Calorie Calculator",
    description: "Calculate your daily calorie needs and macros based on your age, weight, height, and activity level.",
    category: "utility",
    icon: Flame,
    path: "/tools/calorie-calculator",
    featureList: [
      "Calculates daily calorie needs from age, weight and activity",
      "Includes a macro breakdown",
      "Based on standard BMR/TDEE formulas",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "invoice-generator",
    name: "Invoice Generator",
    description:
      "Create professional invoices in seconds. Live preview, 3 templates, multi-currency, logo upload, and instant PDF download. 100% free and private.",
    category: "utility",
    icon: FileText,
    path: "/tools/invoice-generator",
    featureList: [
      "Creates professional invoices with a live preview",
      "3 templates and multi-currency support",
      "Add your logo and export instantly to PDF",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "water-intake-calculator",
    name: "Water Intake Calculator",
    description:
      "Calculate your personalized daily water intake. Interactive glass tracker with sound effects and smart hydration schedule.",
    category: "utility",
    icon: Droplets,
    path: "/tools/water-intake-calculator",
    featureList: [
      "Calculates personalized daily water intake target",
      "Interactive glass-by-glass tracker",
      "Smart hydration reminder schedule",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "pregnancy-calculator",
    name: "Pregnancy Week Calculator",
    description:
      "Find out how far along you are, your due date, and what's happening with your baby this week. Week-by-week development guide with baby size, milestones and key dates.",
    category: "utility",
    icon: Baby,
    path: "/tools/pregnancy-calculator",
  },
  {
    slug: "big-five-personality-test",
    name: "Big Five Personality Test",
    description:
      "Free scientifically-grounded Big Five (OCEAN) personality quiz — 50 IPIP-based questions, full results shown immediately, no signup, no paywall, no email.",
    category: "utility",
    icon: BrainCircuit,
    path: "/tools/big-five-personality-test",
  },
  {
    slug: "attachment-style-test",
    name: "Attachment Style Test",
    description:
      "Free 28-question attachment style test scored on two dimensions — anxiety and avoidance. Secure, anxious, avoidant or fearful-avoidant, full results instantly, no signup.",
    category: "utility",
    icon: HeartHandshake,
    path: "/tools/attachment-style-test",
  },
  {
    slug: "heart-rate-zone-calculator",
    name: "Heart Rate Zone Calculator",
    description:
      "Calculate your maximum heart rate and 5 training zones using Tanaka, Fox, Gulati, Nes or the Karvonen (HRR) method. Free, private, runs in your browser.",
    category: "utility",
    icon: HeartPulse,
    path: "/tools/heart-rate-zone-calculator",
    featureList: [
      "Calculates max heart rate and 5 training zones",
      "Supports Tanaka, Fox, Gulati, Nes and Karvonen (HRR) methods",
      "Free, private, no signup",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "intermittent-fasting-calculator",
    name: "Intermittent Fasting Calculator",
    description:
      "Find your ideal fasting schedule with a 4-question quiz. Live countdown timer, 6 proven protocols (12:12 to OMAD), and personalized daily eating window.",
    category: "utility",
    icon: Timer,
    path: "/tools/intermittent-fasting-calculator",
    featureList: [
      "Finds your ideal fasting schedule via a quick quiz",
      "6 proven protocols from 12:12 to OMAD",
      "Live countdown timer for your eating window",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "macro-calculator",
    name: "Macro Calculator",
    description:
      "Free macro calculator with a complete protein / carb / fat breakdown for cutting, maintenance and lean bulking. Protein-first (g/kg) approach, Mifflin-St Jeor and Katch-McArdle formulas, no signup.",
    category: "utility",
    icon: PieChart,
    path: "/tools/macro-calculator",
  },
  {
    slug: "ball-sort",
    name: "Ball Sort Puzzle",
    description: "Sort colored balls into matching tubes. 30 free levels, mobile and desktop, no download.",
    category: "minigames",
    icon: CircleDot,
    path: "/tools/ball-sort",
    featureList: [
      "Sort colored balls into matching tubes",
      "30 free levels of increasing difficulty",
      "Works on both mobile and desktop",
      "Free to play, no download",
      "No signup required",
    ],
    schemaType: "VideoGame",
  },
  {
    slug: "shooting-ball",
    name: "Shooting Ball",
    description: "Aim and shoot the white ball to pocket colored balls. 20 free billiard puzzle levels, no download.",
    category: "minigames",
    icon: Target,
    path: "/tools/shooting-ball",
  },
  {
    slug: "ai-cover-letter-generator",
    name: "AI Cover Letter Generator",
    description:
      "Generate a tailored, professional cover letter in seconds. Pick tone, length, and language. Free, private, and ready to copy or download as PDF.",
    category: "ai",
    icon: FileSignature,
    path: "/tools/ai-cover-letter-generator",
  },
  {
    slug: "ai-resume-builder",
    name: "AI Resume Builder",
    description:
      "Free AI resume builder — create a professional, ATS-optimized resume in seconds. No signup, no limits, download as PDF or TXT.",
    category: "ai",
    icon: FileText,
    path: "/tools/ai-resume-builder",
  },
  {
    slug: "ai-email-writer",
    name: "AI Email Writer",
    description:
      "Free AI email writer — generate professional emails in seconds. Cold outreach, follow-ups, apologies, sales pitches and more. No signup, no limits.",
    category: "ai",
    icon: Mail,
    path: "/tools/ai-email-writer",
  },
  {
    slug: "ai-bio-generator",
    name: "AI Bio Generator",
    description:
      "Free AI bio generator — Instagram, TikTok, X, LinkedIn and dating app bios with accurate platform character limits. No signup, no credit limits.",
    category: "ai",
    icon: UserRound,
    path: "/tools/ai-bio-generator",
  },
  {
    slug: "ai-writing-assistant",
    name: "AI Writing Assistant",
    description:
      "Free AI writing assistant — check grammar, paraphrase text, and summarize documents instantly. No signup, no limits, powered by AI.",
    category: "ai",
    categories: ["ai", "text"],
    icon: PenLine,
    path: "/tools/ai-writing-assistant",
    featureList: [
      "AI-powered grammar and spelling checker",
      "Paraphrases text while preserving meaning",
      "Summarizes long documents instantly",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "ai-image-generator",
    name: "AI Image Generator",
    description:
      "Free AI image generator — create stunning images from text in seconds. No signup, no limits, no watermark. Powered by Flux.",
    category: "ai",
    categories: ["ai", "image"],
    icon: Sparkles,
    path: "/tools/ai-image-generator",
    featureList: [
      "Generates images from a text description",
      "Powered by the Flux AI model",
      "No signup, no limits, no watermark",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "UtilitiesApplication",
  },
  {
    slug: "image-animator",
    name: "AI Image Animator",
    description:
      "Free AI image animator — bring any photo to life with cinematic motion effects. Export as MP4 or GIF, no signup, no limits.",
    category: "image",
    categories: ["image", "video", "ai"],
    icon: Clapperboard,
    path: "/tools/image-animator",
    featureList: [
      "AI-powered cinematic motion effects from a single photo",
      "Export as MP4 or animated GIF",
      "No signup, no daily limits",
      "No signup required",
      "100% browser-based",
      "Private — files never leave your device",
      "Free forever",
    ],
    schemaCategory: "MultimediaApplication",
  },

  // ── SEO Tools (Semrush-powered) ────────────────────────────────
  // ⚠️ Hidden: API not currently connected (Semrush requires the $549/mo
  // Advanced plan for API access, plus per-unit costs). Unhide once a
  // working data source (Semrush Advanced or a cheaper alternative like
  // DataForSEO/SE Ranking) is actually wired up and verified working.
  {
    slug: "keyword-research",
    name: "Keyword Research Tool",
    description:
      "Free keyword research with real monthly search volume, CPC, competition and related keywords. Live Semrush data, no signup.",
    category: "seo",
    icon: Search,
    path: "/tools/keyword-research",
    hidden: true,
  },
  {
    slug: "domain-analysis",
    name: "Website Traffic Checker",
    description:
      "Estimate any website's organic traffic, keyword count and top ranking pages. Free domain SEO overview powered by Semrush.",
    category: "seo",
    icon: Globe,
    path: "/tools/domain-analysis",
    hidden: true,
  },
  {
    slug: "backlink-checker",
    name: "Backlink Checker",
    description:
      "Check any domain's backlink profile — authority score, total backlinks, referring domains and top referrers. Free, no signup.",
    category: "seo",
    icon: Link2,
    path: "/tools/backlink-checker",
    hidden: true,
  },
  {
    slug: "keyword-difficulty",
    name: "Keyword Difficulty Checker",
    description:
      "Check how hard it is to rank on Google for up to 10 keywords at once. Real Semrush KD scores, volume and CPC. Free.",
    category: "seo",
    icon: Target,
    path: "/tools/keyword-difficulty",
    hidden: true,
  },
  {
    slug: "competitor-analysis",
    name: "Competitor Analysis Tool",
    description:
      "Discover your real Google search competitors in seconds. See keyword overlap, total keywords ranked and estimated traffic.",
    category: "seo",
    icon: Users,
    path: "/tools/competitor-analysis",
    hidden: true,
  },
  {
    slug: "page-seo-analyzer",
    name: "Page SEO Analyzer",
    description:
      "Paste any URL and see every Google keyword it ranks for, positions, volumes and traffic share. Perfect for on-page SEO audits.",
    category: "seo",
    icon: FileSearch,
    path: "/tools/page-seo-analyzer",
    hidden: true,
  },
];

/** Single source of truth for the visible tool count — used on the homepage
 *  hero and the About page so the two numbers can never drift out of sync
 *  or go stale again as tools are added, hidden, or un-hidden. */
export const TOOL_COUNT = tools.filter((t) => !t.hidden).length;
