export type MltCategory = "funny" | "party" | "school" | "relationships" | "bold" | "wholesome";

export interface MltQuestion {
  text: string;
  category: MltCategory;
}

export const CATEGORY_META: { id: MltCategory; label: string; emoji: string; gradient: string }[] = [
  { id: "funny", label: "Funny", emoji: "😂", gradient: "linear-gradient(135deg,#f59e0b,#f97316)" },
  { id: "party", label: "Party", emoji: "🎉", gradient: "linear-gradient(135deg,#8b5cf6,#ec4899)" },
  { id: "school", label: "School", emoji: "📚", gradient: "linear-gradient(135deg,#3b82f6,#6366f1)" },
  { id: "relationships", label: "Relationships", emoji: "💕", gradient: "linear-gradient(135deg,#f43f5e,#ef4444)" },
  { id: "bold", label: "Bold", emoji: "🔥", gradient: "linear-gradient(135deg,#f97316,#dc2626)" },
  { id: "wholesome", label: "Wholesome", emoji: "🌟", gradient: "linear-gradient(135deg,#22c55e,#14b8a6)" },
];

const FUNNY: string[] = [
  "Most likely to trip over a completely flat floor",
  "Most likely to laugh at the worst possible moment",
  "Most likely to talk to an animal like it owes them money",
  "Most likely to get lost in a building they visit every week",
  "Most likely to reply to a text three weeks later like nothing happened",
  "Most likely to name their car and defend it in an argument",
  "Most likely to microwave something and forget it exists",
  "Most likely to start a story and forget the ending halfway through",
  "Most likely to wave at someone who was waving at the person behind them",
  "Most likely to buy something ridiculous at 2am and regret it by breakfast",
  "Most likely to sing the wrong lyrics with absolute confidence",
  "Most likely to fall asleep during a movie they chose themselves",
  "Most likely to lose their phone while holding their phone",
  "Most likely to make a group chat for a plan that never happens",
  "Most likely to burn instant noodles somehow",
  "Most likely to describe a film for ten minutes and never say its name",
  "Most likely to have a folder of screenshots nobody understands",
  "Most likely to argue with a vending machine and lose",
  "Most likely to take the longest possible route and call it a shortcut",
  "Most likely to get emotional about a commercial",
  "Most likely to be beaten at a video game by a small child",
  "Most likely to wear the same outfit three days in a row and pull it off",
  "Most likely to answer a question nobody asked them",
  "Most likely to trip while trying to look cool",
  "Most likely to keep an expired coupon like it's a treasure map",
  "Most likely to say 'you too' to a waiter who said enjoy your meal",
  "Most likely to survive on snacks alone for an entire weekend",
  "Most likely to fall for an obviously fake headline",
  "Most likely to be found narrating their own life out loud",
  "Most likely to bring the wrong gift and act like it was intentional",
  "Most likely to give directions to a place they have never been",
  "Most likely to laugh so hard no sound comes out",
  "Most likely to trip up the stairs, not down",
  "Most likely to sneeze exactly when a photo is taken",
];

const PARTY: string[] = [
  "Most likely to be the last one standing at 4am",
  "Most likely to start a dance floor out of nothing",
  "Most likely to lose their jacket at every single party",
  "Most likely to take over the music and refuse to give it back",
  "Most likely to fall asleep in the middle of the loudest room",
  "Most likely to invite five extra people without asking anyone",
  "Most likely to disappear without saying goodbye",
  "Most likely to make friends with everyone in the kitchen",
  "Most likely to organise the party and then leave first",
  "Most likely to volunteer to be the driver every time",
  "Most likely to know the whole life story of a stranger by midnight",
  "Most likely to suggest karaoke and mean it",
  "Most likely to bring food nobody asked for and everyone eats",
  "Most likely to still be texting the group about last night three days later",
  "Most likely to take 400 photos and post none of them",
  "Most likely to fix a broken speaker with pure confidence",
  "Most likely to end up on a rooftop somehow",
  "Most likely to start a game that ruins several friendships",
  "Most likely to get everyone to sing happy birthday to a stranger",
  "Most likely to say 'one more song' six times in a row",
  "Most likely to be recognised by the staff at every venue",
  "Most likely to arrive two hours late looking incredible",
  "Most likely to be the reason the neighbours complain",
  "Most likely to lose their keys before the night even starts",
  "Most likely to become the unofficial photographer",
  "Most likely to fall asleep on the ride home mid-sentence",
  "Most likely to plan an after-party nobody agreed to",
  "Most likely to convince everyone to try something questionable",
  "Most likely to be first on the dance floor and last off it",
  "Most likely to say they're leaving and stay another three hours",
  "Most likely to make a toast that goes on far too long",
  "Most likely to bring a board game to a house party",
  "Most likely to end the night eating something they'll regret",
];

const SCHOOL: string[] = [
  "Most likely to have done the homework the morning it was due",
  "Most likely to argue with a teacher and somehow win",
  "Most likely to fall asleep in the front row",
  "Most likely to ask a question with two minutes left in class",
  "Most likely to colour-code notes they never read again",
  "Most likely to pass an exam they never studied for",
  "Most likely to be late every single day and never apologise",
  "Most likely to volunteer to present first just to get it over with",
  "Most likely to lose a group project file the night before",
  "Most likely to know the answer and stay completely silent",
  "Most likely to become a teacher's favourite without trying",
  "Most likely to still remember a random fact from year three",
  "Most likely to write the entire essay in one night",
  "Most likely to skip class and still get the highest grade",
  "Most likely to correct the teacher in front of everyone",
  "Most likely to bring snacks to a lecture and share with nobody",
  "Most likely to have the messiest bag in the room",
  "Most likely to plan a study group that becomes a chat session",
  "Most likely to forget their own student number every year",
  "Most likely to end up running a club by accident",
  "Most likely to read the whole book before the first class",
  "Most likely to lose their pen within the first five minutes",
  "Most likely to be caught daydreaming during a test",
  "Most likely to become genuinely famous years after graduation",
  "Most likely to keep in touch with absolutely everyone",
  "Most likely to bring the wrong textbook every time",
  "Most likely to start a group chat for a class of forty people",
  "Most likely to explain a topic better than the teacher did",
  "Most likely to sit in the exact same seat all year",
  "Most likely to sign up for every club and attend none",
  "Most likely to make a whole friendship group in one week",
  "Most likely to survive on coffee during exam season",
  "Most likely to hand in a project one minute before the deadline",
];

const RELATIONSHIPS: string[] = [
  "Most likely to accidentally like a three-year-old photo while stalking someone",
  "Most likely to fall for someone within one conversation",
  "Most likely to write a long message and never send it",
  "Most likely to be caught rehearsing what they'll say",
  "Most likely to introduce a new partner to the group too early",
  "Most likely to still be friends with everyone they've dated",
  "Most likely to plan a whole future after one nice date",
  "Most likely to reply instantly no matter what time it is",
  "Most likely to be the one who says it first",
  "Most likely to remember every anniversary without a reminder",
  "Most likely to get flustered by a simple compliment",
  "Most likely to give great advice and ignore all of it themselves",
  "Most likely to fall for someone completely wrong for them",
  "Most likely to keep old messages for years",
  "Most likely to plan a surprise that gets ruined by their own excitement",
  "Most likely to be set up by their own family",
  "Most likely to get along instantly with someone's parents",
  "Most likely to notice a crush before the person does",
  "Most likely to make a playlist about how they feel",
  "Most likely to overthink a single emoji",
  "Most likely to say they're not looking and then find someone that week",
  "Most likely to cry at someone else's wedding",
  "Most likely to be the group's unofficial relationship counsellor",
  "Most likely to leave a date early with a fake phone call",
  "Most likely to date someone with the exact same personality as them",
  "Most likely to keep a crush secret for years",
  "Most likely to be caught staring across a room",
  "Most likely to write something sweet in a card and ruin it with a joke",
  "Most likely to move in with someone way too fast",
  "Most likely to have a type everyone can describe except them",
  "Most likely to get engaged first out of everyone here",
  "Most likely to spend an hour picking a profile picture",
  "Most likely to double text and then apologise for double texting",
];

const BOLD: string[] = [
  "Most likely to argue with a stranger about something completely pointless",
  "Most likely to quit a job with no plan whatsoever",
  "Most likely to move to another country on two weeks' notice",
  "Most likely to say the thing everyone was thinking out loud",
  "Most likely to send food back at a restaurant",
  "Most likely to go on stage without being asked",
  "Most likely to try a stunt they clearly cannot do",
  "Most likely to start a business on a random idea",
  "Most likely to confront someone on behalf of a friend",
  "Most likely to change their entire look overnight",
  "Most likely to bet money on something ridiculous",
  "Most likely to go somewhere alone with no itinerary",
  "Most likely to cut their own hair at 1am",
  "Most likely to speak to the manager and actually be right",
  "Most likely to survive the longest with no phone",
  "Most likely to ask a celebrity for a photo without hesitating",
  "Most likely to jump into freezing water first",
  "Most likely to tell a hard truth nobody wanted to hear",
  "Most likely to get a tattoo on a whim",
  "Most likely to try the strangest thing on the menu",
  "Most likely to sign up for a marathon with no training",
  "Most likely to walk into a room and take charge",
  "Most likely to talk their way out of any trouble",
  "Most likely to say yes before hearing the full plan",
  "Most likely to make a scene defending something small",
  "Most likely to negotiate the price of anything, anywhere",
  "Most likely to end up in a story that sounds made up",
  "Most likely to break a rule nobody knew existed",
  "Most likely to try skydiving without telling anyone first",
  "Most likely to interrupt a silence with a wild opinion",
  "Most likely to sell everything they own and start over",
  "Most likely to go viral for something completely unplanned",
  "Most likely to survive a week in the wilderness by sheer stubbornness",
];

const WHOLESOME: string[] = [
  "Most likely to remember everyone's birthday without being reminded",
  "Most likely to check in on a friend at exactly the right moment",
  "Most likely to adopt every stray animal they meet",
  "Most likely to give the best advice in the group",
  "Most likely to bring soup when someone is sick",
  "Most likely to drive across town for a friend at midnight",
  "Most likely to compliment a stranger and make their day",
  "Most likely to keep every handwritten note they've received",
  "Most likely to remember a small detail from a conversation years ago",
  "Most likely to make everyone feel included",
  "Most likely to be the first to apologise after an argument",
  "Most likely to cook for the whole group without complaining",
  "Most likely to volunteer for something nobody else wants to do",
  "Most likely to have a friend from every stage of their life",
  "Most likely to send a good morning message that actually helps",
  "Most likely to remember how everyone takes their coffee",
  "Most likely to become everyone's emergency contact",
  "Most likely to plan a surprise just because it's Tuesday",
  "Most likely to hug someone who really needed it",
  "Most likely to donate their last snack without hesitating",
  "Most likely to cheer the loudest for someone else's win",
  "Most likely to stay in touch after everyone else drifts away",
  "Most likely to take care of everyone before themselves",
  "Most likely to write a thank you note nobody expected",
  "Most likely to defend a friend before hearing the details",
  "Most likely to make the new person feel like an old friend",
  "Most likely to keep a promise made years ago",
  "Most likely to notice when someone is quiet and ask why",
  "Most likely to become the parent of the group by accident",
  "Most likely to give away something they love to someone who needs it",
  "Most likely to celebrate the smallest wins like they're huge",
  "Most likely to be the reason this group still hangs out",
  "Most likely to grow old and still be exactly this kind",
];

const build = (items: string[], category: MltCategory): MltQuestion[] => items.map((text) => ({ text, category }));

export const MLT_QUESTIONS: MltQuestion[] = [
  ...build(FUNNY, "funny"),
  ...build(PARTY, "party"),
  ...build(SCHOOL, "school"),
  ...build(RELATIONSHIPS, "relationships"),
  ...build(BOLD, "bold"),
  ...build(WHOLESOME, "wholesome"),
];

export const MLT_TOTAL = MLT_QUESTIONS.length;
