// AUTO-AUTHORED STATIC PUZZLE DATA — Skycally Daily Crossword.
// Every grid, answer, and clue in this file was authored for this project.
// Puzzles are pre-generated static data: nothing here is computed at runtime.

export type CrosswordDirection = "across" | "down";

export interface CrosswordWord {
  /** Grid number shown in the starting square. */
  number: number;
  /** Uppercase A-Z answer, no spaces or punctuation. */
  answer: string;
  clue: string;
  /** Zero-based row of the first letter. */
  row: number;
  /** Zero-based column of the first letter. */
  col: number;
  direction: CrosswordDirection;
}

export interface CrosswordPuzzle {
  id: number;
  title: string;
  rows: number;
  cols: number;
  words: CrosswordWord[];
}

export const CROSSWORD_PUZZLES: CrosswordPuzzle[] = [
  {
    id: 1,
    title: "Crossword No. 1",
    rows: 13,
    cols: 12,
    words: [
      { number: 1, answer: "MALTA", clue: "Tiny Mediterranean island nation", row: 0, col: 1, direction: "down" },
      { number: 2, answer: "DATABASE", clue: "Organized store of records", row: 0, col: 5, direction: "down" },
      { number: 3, answer: "SPAIN", clue: "Country of flamenco and paella", row: 0, col: 10, direction: "down" },
      { number: 4, answer: "TUNDRA", clue: "Treeless plain of the far north", row: 2, col: 5, direction: "across" },
      { number: 5, answer: "NAIROBI", clue: "Capital of Kenya", row: 4, col: 0, direction: "across" },
      { number: 6, answer: "NORWAY", clue: "Land of the fjords", row: 5, col: 7, direction: "down" },
      { number: 7, answer: "KEYBOARD", clue: "Device you type on", row: 5, col: 9, direction: "down" },
      { number: 8, answer: "MICROSCOPE", clue: "Instrument for viewing tiny things", row: 6, col: 0, direction: "across" },
      { number: 9, answer: "ICELAND", clue: "Nordic island of geysers and glaciers", row: 6, col: 1, direction: "down" },
      { number: 10, answer: "RELIC", clue: "Object surviving from the distant past", row: 6, col: 3, direction: "down" },
      { number: 11, answer: "CHAPTER", clue: "Numbered division of a book", row: 6, col: 11, direction: "down" },
      { number: 12, answer: "FALCON", clue: "Swift bird of prey", row: 10, col: 0, direction: "across" },
      { number: 13, answer: "THUNDER", clue: "Rumble that follows lightning", row: 12, col: 5, direction: "across" },
    ],
  },
  {
    id: 2,
    title: "Crossword No. 2",
    rows: 13,
    cols: 13,
    words: [
      { number: 1, answer: "LEMON", clue: "Sour yellow citrus", row: 0, col: 7, direction: "across" },
      { number: 2, answer: "NETWORK", clue: "Group of connected computers", row: 0, col: 11, direction: "down" },
      { number: 3, answer: "HEDGEHOG", clue: "Small mammal covered in spines", row: 1, col: 0, direction: "down" },
      { number: 4, answer: "TIGER", clue: "Big cat with orange stripes", row: 2, col: 2, direction: "down" },
      { number: 5, answer: "ORBIT", clue: "Curved path of a moon or planet", row: 2, col: 7, direction: "across" },
      { number: 6, answer: "ORCHARD", clue: "Grove planted with fruit trees", row: 4, col: 5, direction: "down" },
      { number: 7, answer: "MIRROR", clue: "Glass that shows your reflection", row: 4, col: 7, direction: "across" },
      { number: 7, answer: "MANGO", clue: "Sweet tropical stone fruit", row: 4, col: 7, direction: "down" },
      { number: 8, answer: "HURRICANE", clue: "Powerful tropical storm", row: 6, col: 0, direction: "across" },
      { number: 9, answer: "CAIRO", clue: "Egyptian capital near the Giza pyramids", row: 8, col: 2, direction: "down" },
      { number: 10, answer: "OXYGEN", clue: "Gas we breathe, symbol O", row: 8, col: 7, direction: "across" },
      { number: 11, answer: "EGYPT", clue: "Country of the Sphinx and the Nile", row: 8, col: 11, direction: "down" },
      { number: 12, answer: "SATURN", clue: "Planet famous for its bright rings", row: 9, col: 1, direction: "across" },
      { number: 13, answer: "TOKYO", clue: "Japan's capital", row: 10, col: 8, direction: "across" },
      { number: 14, answer: "OTTER", clue: "Playful mammal of rivers and coasts", row: 12, col: 2, direction: "across" },
    ],
  },
  {
    id: 3,
    title: "Crossword No. 3",
    rows: 12,
    cols: 12,
    words: [
      { number: 1, answer: "PAINTING", clue: "Artwork made with brush and pigment", row: 0, col: 3, direction: "across" },
      { number: 1, answer: "PRISM", clue: "Glass shape that splits white light", row: 0, col: 3, direction: "down" },
      { number: 2, answer: "GALAXY", clue: "Enormous system of stars and dust", row: 0, col: 10, direction: "down" },
      { number: 3, answer: "AUTHOR", clue: "Person who wrote the book", row: 1, col: 1, direction: "down" },
      { number: 4, answer: "CURIOSITY", clue: "Strong urge to find things out", row: 2, col: 0, direction: "across" },
      { number: 5, answer: "HAMMER", clue: "Tool that drives nails", row: 4, col: 1, direction: "across" },
      { number: 6, answer: "MOLECULE", clue: "Group of bonded atoms", row: 4, col: 4, direction: "down" },
      { number: 7, answer: "BEAKER", clue: "Wide lab glass for holding liquid", row: 6, col: 7, direction: "down" },
      { number: 8, answer: "CHEESE", clue: "Dairy food made from curds", row: 7, col: 2, direction: "across" },
      { number: 9, answer: "ATLAS", clue: "Bound collection of maps", row: 7, col: 9, direction: "down" },
      { number: 10, answer: "ACTOR", clue: "Performer in a play or film", row: 8, col: 7, direction: "across" },
      { number: 11, answer: "SODIUM", clue: "Element that pairs with chlorine in table salt", row: 9, col: 0, direction: "across" },
      { number: 12, answer: "RELAY", clue: "Race in which a baton is passed", row: 10, col: 6, direction: "across" },
      { number: 13, answer: "SOCCER", clue: "Sport played with a round ball and feet", row: 11, col: 0, direction: "across" },
    ],
  },
  {
    id: 4,
    title: "Crossword No. 4",
    rows: 13,
    cols: 13,
    words: [
      { number: 1, answer: "VIENNA", clue: "Austrian capital known for waltzes", row: 0, col: 1, direction: "across" },
      { number: 1, answer: "VOLCANO", clue: "Mountain that can erupt", row: 0, col: 1, direction: "down" },
      { number: 2, answer: "ALMOND", clue: "Nut ground into marzipan", row: 2, col: 0, direction: "across" },
      { number: 3, answer: "PIANO", clue: "Keyboard with eighty-eight keys", row: 2, col: 8, direction: "across" },
      { number: 4, answer: "OLIVE", clue: "Small fruit pressed for its oil", row: 2, col: 12, direction: "down" },
      { number: 5, answer: "CANVAS", clue: "Stretched cloth an artist paints on", row: 4, col: 0, direction: "across" },
      { number: 6, answer: "SPARROW", clue: "Small, common brown bird", row: 4, col: 5, direction: "down" },
      { number: 7, answer: "PHARAOH", clue: "Ruler of ancient Egypt", row: 4, col: 8, direction: "down" },
      { number: 8, answer: "OPERA", clue: "Drama that is sung throughout", row: 6, col: 1, direction: "across" },
      { number: 9, answer: "DANUBE", clue: "River passing Vienna and Budapest", row: 6, col: 7, direction: "across" },
      { number: 10, answer: "FIREWALL", clue: "Barrier that filters network traffic", row: 8, col: 3, direction: "across" },
      { number: 10, answer: "FROST", clue: "Thin icy coating on a cold morning", row: 8, col: 3, direction: "down" },
      { number: 11, answer: "ATHENS", clue: "Greek capital crowned by the Acropolis", row: 12, col: 2, direction: "across" },
    ],
  },
  {
    id: 5,
    title: "Crossword No. 5",
    rows: 13,
    cols: 13,
    words: [
      { number: 1, answer: "DELHI", clue: "Sprawling capital region of India", row: 0, col: 12, direction: "down" },
      { number: 2, answer: "PARIS", clue: "Capital city on the Seine", row: 1, col: 1, direction: "down" },
      { number: 3, answer: "PENCIL", clue: "Writing tool with a graphite core", row: 1, col: 4, direction: "down" },
      { number: 4, answer: "NEEDLE", clue: "Slim tool used for sewing", row: 1, col: 7, direction: "across" },
      { number: 4, answer: "NEON", clue: "Gas that glows in bright signs", row: 1, col: 7, direction: "down" },
      { number: 5, answer: "PATIENCE", clue: "Ability to wait without complaint", row: 2, col: 0, direction: "across" },
      { number: 6, answer: "HOCKEY", clue: "Sport played with sticks and a puck", row: 4, col: 9, direction: "down" },
      { number: 7, answer: "OLYMPICS", clue: "Games held every four years", row: 6, col: 3, direction: "across" },
      { number: 8, answer: "SCARF", clue: "Wrap that keeps your neck warm", row: 8, col: 4, direction: "down" },
      { number: 9, answer: "CAMEL", clue: "Desert animal with humps", row: 8, col: 6, direction: "across" },
      { number: 10, answer: "ATOM", clue: "Smallest unit of a chemical element", row: 8, col: 7, direction: "down" },
      { number: 11, answer: "CARBON", clue: "Element found in both diamond and graphite", row: 10, col: 3, direction: "across" },
      { number: 12, answer: "REEF", clue: "Ridge of coral near the surface", row: 12, col: 1, direction: "across" },
    ],
  },
  {
    id: 6,
    title: "Crossword No. 6",
    rows: 13,
    cols: 13,
    words: [
      { number: 1, answer: "JUPITER", clue: "Biggest planet in the solar system", row: 0, col: 0, direction: "down" },
      { number: 2, answer: "ALPS", clue: "European range with the Matterhorn", row: 1, col: 2, direction: "down" },
      { number: 3, answer: "SAMURAI", clue: "Warrior of feudal Japan", row: 1, col: 6, direction: "across" },
      { number: 4, answer: "ARCHERY", clue: "Sport of the bow and arrow", row: 1, col: 11, direction: "down" },
      { number: 5, answer: "INSECT", clue: "Small creature with six legs", row: 3, col: 7, direction: "across" },
      { number: 6, answer: "STAGE", clue: "Platform where actors perform", row: 4, col: 2, direction: "across" },
      { number: 7, answer: "ECLIPSE", clue: "Event where one body hides another", row: 4, col: 6, direction: "down" },
      { number: 8, answer: "CRICKET", clue: "Sport with wickets and overs", row: 5, col: 6, direction: "across" },
      { number: 9, answer: "ROBOT", clue: "Machine built to perform tasks", row: 6, col: 0, direction: "across" },
      { number: 10, answer: "TRUMPET", clue: "Brass instrument with three valves", row: 6, col: 4, direction: "down" },
      { number: 11, answer: "IRON", clue: "Metal whose symbol is Fe", row: 7, col: 9, direction: "down" },
      { number: 12, answer: "SCULPTURE", clue: "Artwork carved or modeled in three dimensions", row: 8, col: 2, direction: "across" },
      { number: 13, answer: "ANDES", clue: "Long mountain chain of South America", row: 10, col: 8, direction: "across" },
      { number: 14, answer: "BUCKET", clue: "Pail for carrying water", row: 11, col: 0, direction: "across" },
    ],
  },
  {
    id: 7,
    title: "Crossword No. 7",
    rows: 12,
    cols: 13,
    words: [
      { number: 1, answer: "UMBRELLA", clue: "Portable shield against rain", row: 0, col: 1, direction: "down" },
      { number: 2, answer: "OCTOPUS", clue: "Sea creature with eight arms", row: 0, col: 6, direction: "across" },
      { number: 3, answer: "PILLOW", clue: "Soft rest for your head", row: 0, col: 10, direction: "down" },
      { number: 4, answer: "BUTTER", clue: "Spread churned from cream", row: 1, col: 4, direction: "down" },
      { number: 5, answer: "PETAL", clue: "Colored part of a flower", row: 2, col: 6, direction: "across" },
      { number: 6, answer: "SHELF", clue: "Flat board for storing books", row: 2, col: 12, direction: "down" },
      { number: 7, answer: "TELESCOPE", clue: "Instrument for viewing distant objects", row: 4, col: 4, direction: "across" },
      { number: 8, answer: "LIBRARY", clue: "Building where books are borrowed", row: 6, col: 1, direction: "across" },
      { number: 9, answer: "BREEZE", clue: "Gentle wind", row: 6, col: 3, direction: "down" },
      { number: 10, answer: "ACORN", clue: "Seed that grows into an oak", row: 6, col: 5, direction: "down" },
      { number: 11, answer: "OXIDE", clue: "Compound of oxygen and another element", row: 8, col: 5, direction: "across" },
      { number: 12, answer: "NOVEL", clue: "Long work of fiction", row: 10, col: 5, direction: "across" },
      { number: 13, answer: "KOREA", clue: "Peninsula split into north and south", row: 11, col: 0, direction: "across" },
    ],
  },
  {
    id: 8,
    title: "Crossword No. 8",
    rows: 13,
    cols: 13,
    words: [
      { number: 1, answer: "PASTA", clue: "Italian staple served al dente", row: 0, col: 3, direction: "down" },
      { number: 2, answer: "CANDLE", clue: "Wax column with a wick", row: 1, col: 5, direction: "across" },
      { number: 2, answer: "CARROT", clue: "Orange root vegetable", row: 1, col: 5, direction: "down" },
      { number: 3, answer: "KANGAROO", clue: "Marsupial that gets around by hopping", row: 2, col: 1, direction: "down" },
      { number: 4, answer: "CHILE", clue: "Long, narrow South American country", row: 2, col: 11, direction: "down" },
      { number: 5, answer: "BATTERY", clue: "Portable source of power", row: 3, col: 0, direction: "across" },
      { number: 6, answer: "SATELLITE", clue: "Object placed in orbit around Earth", row: 6, col: 3, direction: "across" },
      { number: 7, answer: "LUGGAGE", clue: "Bags packed for a trip", row: 6, col: 8, direction: "down" },
      { number: 8, answer: "VIKING", clue: "Norse seafarer and raider", row: 8, col: 3, direction: "across" },
      { number: 9, answer: "KENYA", clue: "East African country on the equator", row: 8, col: 5, direction: "down" },
      { number: 10, answer: "FJORD", clue: "Narrow sea inlet with steep sides", row: 8, col: 11, direction: "down" },
      { number: 11, answer: "SALMON", clue: "Fish that swims upstream to spawn", row: 10, col: 7, direction: "across" },
      { number: 12, answer: "LIMA", clue: "Capital of Peru", row: 12, col: 2, direction: "across" },
      { number: 13, answer: "MELODY", clue: "Tune you can hum", row: 12, col: 7, direction: "across" },
    ],
  },
  {
    id: 9,
    title: "Crossword No. 9",
    rows: 13,
    cols: 13,
    words: [
      { number: 1, answer: "ALBUM", clue: "Collection of recorded songs", row: 0, col: 1, direction: "across" },
      { number: 2, answer: "MEDAL", clue: "Award that hangs on a ribbon", row: 0, col: 5, direction: "down" },
      { number: 3, answer: "ANCIENT", clue: "Belonging to the very distant past", row: 1, col: 12, direction: "down" },
      { number: 4, answer: "STATION", clue: "Stop along a rail line", row: 2, col: 1, direction: "down" },
      { number: 5, answer: "JACKET", clue: "Short, light coat", row: 2, col: 3, direction: "down" },
      { number: 6, answer: "DUBLIN", clue: "Irish capital on the Liffey", row: 2, col: 7, direction: "across" },
      { number: 6, answer: "DYNASTY", clue: "Succession of rulers from one family", row: 2, col: 7, direction: "down" },
      { number: 7, answer: "CALENDAR", clue: "Chart of days and months", row: 4, col: 3, direction: "across" },
      { number: 8, answer: "RIDDLE", clue: "Question posed as a brain teaser", row: 4, col: 10, direction: "down" },
      { number: 9, answer: "VACCINE", clue: "Shot that trains the immune system", row: 6, col: 5, direction: "down" },
      { number: 10, answer: "PORTRAIT", clue: "Artwork depicting a person", row: 7, col: 0, direction: "across" },
      { number: 11, answer: "PERU", clue: "Country that holds Machu Picchu", row: 9, col: 9, direction: "across" },
      { number: 12, answer: "CLIMBING", clue: "Ascending rock or an indoor wall", row: 10, col: 0, direction: "across" },
      { number: 13, answer: "GENOME", clue: "Complete set of an organism's genes", row: 12, col: 0, direction: "across" },
    ],
  },
  {
    id: 10,
    title: "Crossword No. 10",
    rows: 13,
    cols: 13,
    words: [
      { number: 1, answer: "STUDIO", clue: "Workspace of an artist", row: 0, col: 4, direction: "down" },
      { number: 2, answer: "BALANCE", clue: "Even distribution of weight", row: 0, col: 6, direction: "down" },
      { number: 3, answer: "BRIDGE", clue: "Structure that spans a river", row: 0, col: 8, direction: "down" },
      { number: 4, answer: "KNIGHT", clue: "Armored warrior of the Middle Ages", row: 0, col: 10, direction: "down" },
      { number: 5, answer: "LEOPARD", clue: "Big cat covered in spots", row: 1, col: 12, direction: "down" },
      { number: 6, answer: "ORCHESTRA", clue: "Large ensemble led by a conductor", row: 5, col: 4, direction: "across" },
      { number: 7, answer: "SUMMIT", clue: "Highest point of a mountain", row: 5, col: 9, direction: "down" },
      { number: 8, answer: "TEMPLE", clue: "Building raised for worship", row: 6, col: 0, direction: "down" },
      { number: 9, answer: "ANCHOR", clue: "Heavy weight that holds a ship", row: 7, col: 3, direction: "down" },
      { number: 10, answer: "ITALY", clue: "Boot-shaped European country", row: 7, col: 5, direction: "down" },
      { number: 11, answer: "MAGNET", clue: "Object that attracts iron", row: 8, col: 0, direction: "across" },
      { number: 12, answer: "SEOUL", clue: "South Korea's capital", row: 8, col: 11, direction: "down" },
      { number: 13, answer: "ARCHIVE", clue: "Store of historical records", row: 9, col: 5, direction: "across" },
      { number: 14, answer: "PIXEL", clue: "Tiny dot in a screen image", row: 12, col: 7, direction: "across" },
    ],
  },
  {
    id: 11,
    title: "Crossword No. 11",
    rows: 13,
    cols: 13,
    words: [
      { number: 1, answer: "FOLDER", clue: "Container that holds files", row: 0, col: 5, direction: "down" },
      { number: 2, answer: "NEURON", clue: "Nerve cell that carries signals", row: 1, col: 1, direction: "across" },
      { number: 3, answer: "NEBULA", clue: "Vast cloud of gas and dust in space", row: 3, col: 0, direction: "down" },
      { number: 4, answer: "POTATO", clue: "Tuber behind fries and mash", row: 3, col: 2, direction: "down" },
      { number: 5, answer: "HARBOR", clue: "Sheltered spot where ships dock", row: 3, col: 7, direction: "across" },
      { number: 5, answer: "HELIUM", clue: "Gas that makes party balloons rise", row: 3, col: 7, direction: "down" },
      { number: 6, answer: "BUTTERFLY", clue: "Insect with broad, colorful wings", row: 5, col: 0, direction: "across" },
      { number: 7, answer: "LETTUCE", clue: "Crisp leaf at the base of a salad", row: 6, col: 9, direction: "down" },
      { number: 8, answer: "TREASURE", clue: "Hoard of valuable things", row: 7, col: 2, direction: "across" },
      { number: 9, answer: "AMAZON", clue: "World's largest rainforest", row: 7, col: 5, direction: "down" },
      { number: 10, answer: "FLUTE", clue: "Woodwind you blow across", row: 10, col: 7, direction: "across" },
      { number: 11, answer: "CANYON", clue: "Deep gorge carved by a river", row: 11, col: 1, direction: "across" },
      { number: 12, answer: "POETRY", clue: "Writing arranged in verse", row: 12, col: 7, direction: "across" },
    ],
  },
  {
    id: 12,
    title: "Crossword No. 12",
    rows: 13,
    cols: 13,
    words: [
      { number: 1, answer: "YOGURT", clue: "Cultured dairy snack", row: 0, col: 1, direction: "down" },
      { number: 2, answer: "ENERGY", clue: "Capacity to do work", row: 0, col: 3, direction: "down" },
      { number: 3, answer: "WAFFLE", clue: "Breakfast cake with square pockets", row: 0, col: 6, direction: "down" },
      { number: 4, answer: "FORMULA", clue: "Compact expression of a rule or compound", row: 0, col: 9, direction: "down" },
      { number: 5, answer: "GRAVITY", clue: "Force that pulls objects toward Earth", row: 0, col: 11, direction: "down" },
      { number: 6, answer: "DOWNLOAD", clue: "Pull a file from the internet", row: 1, col: 0, direction: "across" },
      { number: 7, answer: "BREAD", clue: "Baked staple sold by the loaf", row: 2, col: 8, direction: "across" },
      { number: 8, answer: "NEPAL", clue: "Himalayan country bordering Tibet", row: 5, col: 5, direction: "across" },
      { number: 8, answer: "NILE", clue: "Long river flowing north through Egypt", row: 5, col: 5, direction: "down" },
      { number: 9, answer: "PEANUT", clue: "Legume roasted and salted", row: 5, col: 7, direction: "down" },
      { number: 10, answer: "MURAL", clue: "Painting made directly on a wall", row: 7, col: 1, direction: "across" },
      { number: 10, answer: "MEMORY", clue: "Something recalled from the past", row: 7, col: 1, direction: "down" },
      { number: 11, answer: "BEAVER", clue: "Rodent that builds dams", row: 7, col: 12, direction: "down" },
      { number: 12, answer: "NOODLE", clue: "Long strand in a bowl of soup", row: 8, col: 7, direction: "across" },
      { number: 13, answer: "THEATER", clue: "Venue for plays and films", row: 10, col: 3, direction: "across" },
    ],
  },
  {
    id: 13,
    title: "Crossword No. 13",
    rows: 13,
    cols: 12,
    words: [
      { number: 1, answer: "SILENCE", clue: "Total absence of sound", row: 0, col: 0, direction: "down" },
      { number: 2, answer: "BLIZZARD", clue: "Fierce snowstorm", row: 0, col: 2, direction: "across" },
      { number: 2, answer: "BUTTON", clue: "Small fastener on a shirt", row: 0, col: 2, direction: "down" },
      { number: 3, answer: "TOWER", clue: "Tall and narrow structure", row: 2, col: 2, direction: "across" },
      { number: 4, answer: "CUBA", clue: "Largest island nation in the Caribbean", row: 3, col: 8, direction: "across" },
      { number: 5, answer: "BLOSSOM", clue: "Flower on a fruit tree", row: 3, col: 10, direction: "down" },
      { number: 6, answer: "COCONUT", clue: "Hard-shelled tropical fruit", row: 4, col: 6, direction: "down" },
      { number: 7, answer: "CINNAMON", clue: "Warm spice made from tree bark", row: 5, col: 0, direction: "across" },
      { number: 8, answer: "GARLIC", clue: "Pungent bulb used in cooking", row: 7, col: 1, direction: "down" },
      { number: 9, answer: "COMPASS", clue: "Instrument that points north", row: 7, col: 5, direction: "across" },
      { number: 10, answer: "EAGLE", clue: "Large bird of prey with keen sight", row: 8, col: 0, direction: "across" },
      { number: 11, answer: "ALGORITHM", clue: "Step-by-step procedure for solving a problem", row: 10, col: 0, direction: "across" },
      { number: 12, answer: "CIRCUIT", clue: "Closed loop that carries current", row: 12, col: 1, direction: "across" },
    ],
  },
  {
    id: 14,
    title: "Crossword No. 14",
    rows: 13,
    cols: 13,
    words: [
      { number: 1, answer: "BLANKET", clue: "Warm covering on a bed", row: 0, col: 4, direction: "down" },
      { number: 2, answer: "TENNIS", clue: "Racket sport scored with love and deuce", row: 0, col: 8, direction: "down" },
      { number: 3, answer: "VOLTAGE", clue: "Difference in electric potential", row: 1, col: 2, direction: "across" },
      { number: 4, answer: "SUGAR", clue: "Sweetener stirred into tea", row: 2, col: 1, direction: "down" },
      { number: 5, answer: "CARTOON", clue: "Drawn or animated picture", row: 2, col: 10, direction: "down" },
      { number: 6, answer: "DESERT", clue: "Region that gets almost no rain", row: 2, col: 12, direction: "down" },
      { number: 7, answer: "PANCAKE", clue: "Flat cake cooked on a griddle", row: 3, col: 6, direction: "across" },
      { number: 8, answer: "FOREST", clue: "Large area thick with trees", row: 5, col: 6, direction: "down" },
      { number: 9, answer: "FRICTION", clue: "Force that resists sliding", row: 6, col: 0, direction: "across" },
      { number: 9, answer: "FREEDOM", clue: "State of being unrestrained", row: 6, col: 0, direction: "down" },
      { number: 10, answer: "MARKET", clue: "Place to buy and sell goods", row: 8, col: 2, direction: "across" },
      { number: 11, answer: "RHYTHM", clue: "Underlying beat of a piece", row: 10, col: 3, direction: "across" },
      { number: 12, answer: "MEADOW", clue: "Open field of grass and flowers", row: 12, col: 0, direction: "across" },
    ],
  },
  {
    id: 15,
    title: "Crossword No. 15",
    rows: 13,
    cols: 13,
    words: [
      { number: 1, answer: "EMPIRE", clue: "Many lands under a single ruler", row: 0, col: 6, direction: "across" },
      { number: 2, answer: "MONARCH", clue: "King or queen", row: 0, col: 7, direction: "down" },
      { number: 3, answer: "CURSOR", clue: "Blinking marker on a screen", row: 1, col: 3, direction: "down" },
      { number: 4, answer: "SUITCASE", clue: "Travel bag with a handle", row: 1, col: 12, direction: "down" },
      { number: 5, answer: "CRYSTAL", clue: "Solid with an orderly repeating structure", row: 3, col: 2, direction: "across" },
      { number: 6, answer: "PROMISE", clue: "Word given that you will do something", row: 5, col: 0, direction: "down" },
      { number: 7, answer: "MOSAIC", clue: "Picture assembled from small tiles", row: 5, col: 2, direction: "across" },
      { number: 8, answer: "ARTERY", clue: "Vessel that carries blood from the heart", row: 5, col: 5, direction: "down" },
      { number: 9, answer: "DROUGHT", clue: "Long stretch with no rain", row: 6, col: 10, direction: "down" },
      { number: 10, answer: "PANDA", clue: "Black-and-white bear that eats bamboo", row: 7, col: 2, direction: "down" },
      { number: 11, answer: "ENVELOPE", clue: "Paper sleeve for a letter", row: 8, col: 5, direction: "across" },
      { number: 12, answer: "SYDNEY", clue: "Australian city with a shell-shaped opera house", row: 10, col: 0, direction: "across" },
      { number: 13, answer: "GINGER", clue: "Spicy root often brewed in tea", row: 10, col: 7, direction: "across" },
      { number: 14, answer: "WALNUT", clue: "Nut with a wrinkled kernel", row: 12, col: 5, direction: "across" },
    ],
  },
  {
    id: 16,
    title: "Crossword No. 16",
    rows: 13,
    cols: 13,
    words: [
      { number: 1, answer: "GUITAR", clue: "Instrument with six strings", row: 0, col: 4, direction: "down" },
      { number: 2, answer: "KETTLE", clue: "Pot for boiling water", row: 0, col: 11, direction: "down" },
      { number: 3, answer: "CACTUS", clue: "Desert plant covered in spines", row: 1, col: 0, direction: "across" },
      { number: 4, answer: "GARDEN", clue: "Plot where flowers are grown", row: 1, col: 7, direction: "across" },
      { number: 4, answer: "GIRAFFE", clue: "Tallest animal on land", row: 1, col: 7, direction: "down" },
      { number: 5, answer: "SOFTWARE", clue: "Programs that run on a machine", row: 3, col: 1, direction: "across" },
      { number: 6, answer: "OSLO", clue: "Norway's capital", row: 4, col: 9, direction: "across" },
      { number: 7, answer: "SAHARA", clue: "Vast desert across northern Africa", row: 5, col: 0, direction: "across" },
      { number: 8, answer: "PICKLE", clue: "Cucumber preserved in brine", row: 7, col: 0, direction: "down" },
      { number: 9, answer: "TURTLE", clue: "Reptile that carries a shell", row: 7, col: 2, direction: "across" },
      { number: 10, answer: "UMPIRE", clue: "Official who calls balls and strikes", row: 7, col: 3, direction: "down" },
      { number: 11, answer: "COPPER", clue: "Reddish metal used in wiring", row: 9, col: 0, direction: "across" },
      { number: 12, answer: "VENUS", clue: "Second planet from the sun", row: 12, col: 2, direction: "across" },
    ],
  },
  {
    id: 17,
    title: "Crossword No. 17",
    rows: 13,
    cols: 13,
    words: [
      { number: 1, answer: "HARVEST", clue: "Gathering in of the crops", row: 0, col: 5, direction: "across" },
      { number: 2, answer: "SENATE", clue: "Governing body of ancient Rome", row: 0, col: 10, direction: "down" },
      { number: 3, answer: "SPINACH", clue: "Leafy green rich in iron", row: 1, col: 0, direction: "down" },
      { number: 4, answer: "PUMPKIN", clue: "Big orange gourd of autumn", row: 2, col: 4, direction: "across" },
      { number: 5, answer: "PEACH", clue: "Fuzzy summer fruit", row: 2, col: 7, direction: "down" },
      { number: 6, answer: "MADRID", clue: "Capital of Spain", row: 4, col: 3, direction: "down" },
      { number: 7, answer: "ATLANTIC", clue: "Ocean between Europe and the Americas", row: 5, col: 0, direction: "across" },
      { number: 8, answer: "VALLEY", clue: "Low land between hills", row: 6, col: 11, direction: "down" },
      { number: 9, answer: "ENZYME", clue: "Protein that speeds up a reaction", row: 7, col: 5, direction: "down" },
      { number: 10, answer: "ONION", clue: "Layered bulb that brings on tears", row: 8, col: 1, direction: "across" },
      { number: 11, answer: "SCROLL", clue: "Rolled-up ancient document", row: 8, col: 7, direction: "across" },
      { number: 12, answer: "CLOCK", clue: "Device that shows the time", row: 8, col: 8, direction: "down" },
      { number: 13, answer: "MERCURY", clue: "Planet nearest the sun", row: 11, col: 5, direction: "across" },
      { number: 14, answer: "WHALE", clue: "Largest mammal in the ocean", row: 12, col: 1, direction: "across" },
    ],
  },
  {
    id: 18,
    title: "Crossword No. 18",
    rows: 13,
    cols: 13,
    words: [
      { number: 1, answer: "HARMONY", clue: "Pleasing agreement of parts", row: 0, col: 2, direction: "down" },
      { number: 2, answer: "ORANGE", clue: "Citrus fruit that names a color", row: 0, col: 7, direction: "down" },
      { number: 3, answer: "PASSPORT", clue: "Travel document full of stamps", row: 1, col: 1, direction: "across" },
      { number: 4, answer: "MONITOR", clue: "Screen attached to a computer", row: 2, col: 9, direction: "down" },
      { number: 5, answer: "RAINBOW", clue: "Arc of colors after a shower", row: 3, col: 4, direction: "across" },
      { number: 6, answer: "BANANA", clue: "Curved yellow fruit", row: 5, col: 0, direction: "across" },
      { number: 7, answer: "NEPTUNE", clue: "Outermost planet of the solar system", row: 5, col: 4, direction: "down" },
      { number: 8, answer: "PENGUIN", clue: "Flightless bird of the far south", row: 6, col: 11, direction: "down" },
      { number: 9, answer: "COMET", clue: "Icy visitor with a glowing tail", row: 7, col: 8, direction: "across" },
      { number: 10, answer: "TOMATO", clue: "Red fruit common in salads", row: 8, col: 0, direction: "across" },
      { number: 11, answer: "CHORUS", clue: "Part of a song that repeats", row: 10, col: 7, direction: "across" },
      { number: 12, answer: "MUSEUM", clue: "Building full of exhibits", row: 11, col: 1, direction: "across" },
      { number: 13, answer: "HAVANA", clue: "Cuban capital famous for cigars", row: 12, col: 7, direction: "across" },
    ],
  },
  {
    id: 19,
    title: "Crossword No. 19",
    rows: 13,
    cols: 13,
    words: [
      { number: 1, answer: "LEGEND", clue: "Traditional tale, or a key on a map", row: 0, col: 5, direction: "across" },
      { number: 1, answer: "LASER", clue: "Tightly focused beam of light", row: 0, col: 5, direction: "down" },
      { number: 2, answer: "KITCHEN", clue: "Room where meals are cooked", row: 1, col: 3, direction: "down" },
      { number: 3, answer: "SERVER", clue: "Machine that hosts a website", row: 2, col: 9, direction: "down" },
      { number: 4, answer: "JOURNEY", clue: "Long trip from place to place", row: 2, col: 11, direction: "down" },
      { number: 5, answer: "CASTLE", clue: "Fortified home of royalty", row: 3, col: 0, direction: "across" },
      { number: 6, answer: "RUMOR", clue: "Story passed along without proof", row: 4, col: 5, direction: "across" },
      { number: 7, answer: "PRAIRIE", clue: "Wide expanse of grassland", row: 6, col: 1, direction: "down" },
      { number: 8, answer: "BROWSER", clue: "App used to visit websites", row: 6, col: 5, direction: "down" },
      { number: 9, answer: "REFEREE", clue: "Official who enforces the rules", row: 7, col: 5, direction: "across" },
      { number: 10, answer: "WISDOM", clue: "Deep insight gained from experience", row: 9, col: 5, direction: "across" },
      { number: 11, answer: "ELEPHANT", clue: "Largest animal on land", row: 11, col: 5, direction: "across" },
      { number: 12, answer: "PEPPER", clue: "Spice ground from dried peppercorns", row: 12, col: 0, direction: "across" },
    ],
  },
  {
    id: 20,
    title: "Crossword No. 20",
    rows: 13,
    cols: 13,
    words: [
      { number: 1, answer: "KIDNEY", clue: "Organ that filters the blood", row: 0, col: 7, direction: "across" },
      { number: 2, answer: "NOTEBOOK", clue: "Bound pages for jotting things down", row: 0, col: 10, direction: "down" },
      { number: 3, answer: "BISCUIT", clue: "Small baked treat", row: 2, col: 4, direction: "across" },
      { number: 4, answer: "COMEDY", clue: "Genre meant to make you laugh", row: 2, col: 12, direction: "down" },
      { number: 5, answer: "PROTEIN", clue: "Nutrient built from amino acids", row: 3, col: 1, direction: "down" },
      { number: 6, answer: "THAMES", clue: "River that runs through London", row: 4, col: 6, direction: "down" },
      { number: 7, answer: "MYSTERY", clue: "Something that remains unexplained", row: 4, col: 8, direction: "down" },
      { number: 8, answer: "HONEY", clue: "Sweet syrup made by bees", row: 5, col: 0, direction: "across" },
      { number: 9, answer: "PASSWORD", clue: "Secret string that unlocks an account", row: 6, col: 5, direction: "across" },
      { number: 10, answer: "BALLET", clue: "Classical dance done on pointe", row: 7, col: 3, direction: "down" },
      { number: 11, answer: "GIRAFFE", clue: "Tallest animal on land", row: 8, col: 0, direction: "across" },
      { number: 12, answer: "SURFING", clue: "Riding ocean waves on a board", row: 9, col: 6, direction: "across" },
      { number: 13, answer: "CHERRY", clue: "Small red fruit with a pit", row: 11, col: 1, direction: "across" },
    ],
  },
  {
    id: 21,
    title: "Crossword No. 21",
    rows: 13,
    cols: 13,
    words: [
      { number: 1, answer: "LAGOON", clue: "Shallow water sheltered by a reef", row: 0, col: 0, direction: "across" },
      { number: 1, answer: "LADDER", clue: "Climbing frame with rungs", row: 0, col: 0, direction: "down" },
      { number: 2, answer: "OPERA", clue: "Drama that is sung throughout", row: 0, col: 3, direction: "down" },
      { number: 3, answer: "VIOLIN", clue: "String instrument played with a bow", row: 0, col: 8, direction: "down" },
      { number: 4, answer: "LISBON", clue: "Portugal's coastal capital", row: 1, col: 7, direction: "across" },
      { number: 5, answer: "CRYSTAL", clue: "Solid with an orderly repeating structure", row: 3, col: 2, direction: "across" },
      { number: 6, answer: "MARATHON", clue: "Race of 26.2 miles", row: 3, col: 11, direction: "down" },
      { number: 7, answer: "CONCERT", clue: "Live performance of music", row: 5, col: 6, direction: "across" },
      { number: 8, answer: "GOALIE", clue: "Player guarding the net", row: 6, col: 3, direction: "down" },
      { number: 9, answer: "SEOUL", clue: "South Korea's capital", row: 7, col: 1, direction: "across" },
      { number: 9, answer: "SUNSET", clue: "Colorful end of the day", row: 7, col: 1, direction: "down" },
      { number: 10, answer: "LYRICS", clue: "Words that go with the music", row: 7, col: 5, direction: "down" },
      { number: 11, answer: "NILE", clue: "Long river flowing north through Egypt", row: 8, col: 8, direction: "down" },
      { number: 12, answer: "WINDOW", clue: "Glass opening in a wall", row: 9, col: 7, direction: "across" },
      { number: 13, answer: "TELESCOPE", clue: "Instrument for viewing distant objects", row: 11, col: 0, direction: "across" },
    ],
  },
  {
    id: 22,
    title: "Crossword No. 22",
    rows: 13,
    cols: 13,
    words: [
      { number: 1, answer: "MANGO", clue: "Sweet tropical stone fruit", row: 0, col: 0, direction: "across" },
      { number: 1, answer: "MONSOON", clue: "Season of heavy tropical rains", row: 0, col: 0, direction: "down" },
      { number: 2, answer: "CANADA", clue: "Nation with a maple leaf on its flag", row: 1, col: 5, direction: "down" },
      { number: 3, answer: "FOLDER", clue: "Container that holds files", row: 1, col: 7, direction: "down" },
      { number: 4, answer: "AIRPORT", clue: "Where flights arrive and depart", row: 1, col: 9, direction: "down" },
      { number: 5, answer: "NEBULA", clue: "Vast cloud of gas and dust in space", row: 2, col: 0, direction: "across" },
      { number: 6, answer: "LYRICS", clue: "Words that go with the music", row: 3, col: 7, direction: "across" },
      { number: 7, answer: "STADIUM", clue: "Large venue for sporting events", row: 3, col: 12, direction: "down" },
      { number: 8, answer: "HEDGEHOG", clue: "Small mammal covered in spines", row: 5, col: 3, direction: "across" },
      { number: 8, answer: "HARMONY", clue: "Pleasing agreement of parts", row: 5, col: 3, direction: "down" },
      { number: 9, answer: "COMET", clue: "Icy visitor with a glowing tail", row: 8, col: 1, direction: "across" },
      { number: 9, answer: "CLOUD", clue: "Floating mass of water vapor", row: 8, col: 1, direction: "down" },
      { number: 10, answer: "NEON", clue: "Gas that glows in bright signs", row: 8, col: 7, direction: "down" },
      { number: 11, answer: "NAIROBI", clue: "Capital of Kenya", row: 10, col: 3, direction: "across" },
    ],
  },
  {
    id: 23,
    title: "Crossword No. 23",
    rows: 13,
    cols: 13,
    words: [
      { number: 1, answer: "GLACIER", clue: "Slow-moving river of ice", row: 0, col: 0, direction: "across" },
      { number: 1, answer: "GENOME", clue: "Complete set of an organism's genes", row: 0, col: 0, direction: "down" },
      { number: 2, answer: "ALPS", clue: "European range with the Matterhorn", row: 0, col: 2, direction: "down" },
      { number: 3, answer: "EQUATOR", clue: "Imaginary line at zero degrees latitude", row: 0, col: 5, direction: "down" },
      { number: 4, answer: "TOKYO", clue: "Japan's capital", row: 1, col: 11, direction: "down" },
      { number: 5, answer: "PUZZLE", clue: "Problem solved for the fun of it", row: 2, col: 4, direction: "across" },
      { number: 6, answer: "BUTTERFLY", clue: "Insect with broad, colorful wings", row: 4, col: 3, direction: "across" },
      { number: 7, answer: "RIDDLE", clue: "Question posed as a brain teaser", row: 4, col: 8, direction: "down" },
      { number: 8, answer: "DANUBE", clue: "River passing Vienna and Budapest", row: 5, col: 2, direction: "down" },
      { number: 9, answer: "FREEDOM", clue: "State of being unrestrained", row: 6, col: 4, direction: "across" },
      { number: 9, answer: "FJORD", clue: "Narrow sea inlet with steep sides", row: 6, col: 4, direction: "down" },
      { number: 10, answer: "THEORY", clue: "Well-tested scientific explanation", row: 7, col: 11, direction: "down" },
      { number: 11, answer: "NEURON", clue: "Nerve cell that carries signals", row: 8, col: 0, direction: "across" },
      { number: 11, answer: "NEPAL", clue: "Himalayan country bordering Tibet", row: 8, col: 0, direction: "down" },
      { number: 12, answer: "GREECE", clue: "Birthplace of the ancient Olympics", row: 9, col: 6, direction: "across" },
      { number: 13, answer: "CAMERA", clue: "Device that captures photographs", row: 11, col: 7, direction: "across" },
    ],
  },
  {
    id: 24,
    title: "Crossword No. 24",
    rows: 13,
    cols: 13,
    words: [
      { number: 1, answer: "SALAD", clue: "Bowl of raw vegetables", row: 0, col: 5, direction: "down" },
      { number: 2, answer: "EGYPT", clue: "Country of the Sphinx and the Nile", row: 1, col: 3, direction: "down" },
      { number: 3, answer: "ATHENS", clue: "Greek capital crowned by the Acropolis", row: 1, col: 5, direction: "across" },
      { number: 4, answer: "PYRAMID", clue: "Ancient tomb with triangular sides", row: 3, col: 2, direction: "across" },
      { number: 5, answer: "DATABASE", clue: "Organized store of records", row: 3, col: 8, direction: "down" },
      { number: 6, answer: "NETWORK", clue: "Group of connected computers", row: 5, col: 10, direction: "down" },
      { number: 7, answer: "SKELETON", clue: "Framework of bones in the body", row: 5, col: 12, direction: "down" },
      { number: 8, answer: "VANILLA", clue: "Classic pale ice cream flavor", row: 6, col: 4, direction: "down" },
      { number: 9, answer: "EVEREST", clue: "Tallest mountain on Earth", row: 6, col: 6, direction: "down" },
      { number: 10, answer: "LEMON", clue: "Sour yellow citrus", row: 7, col: 0, direction: "down" },
      { number: 11, answer: "MICROSCOPE", clue: "Instrument for viewing tiny things", row: 9, col: 3, direction: "across" },
      { number: 12, answer: "NOVEL", clue: "Long work of fiction", row: 11, col: 0, direction: "across" },
      { number: 13, answer: "ARTERY", clue: "Vessel that carries blood from the heart", row: 12, col: 4, direction: "across" },
    ],
  },
  {
    id: 25,
    title: "Crossword No. 25",
    rows: 13,
    cols: 13,
    words: [
      { number: 1, answer: "BROWSER", clue: "App used to visit websites", row: 0, col: 0, direction: "across" },
      { number: 2, answer: "SUMMIT", clue: "Highest point of a mountain", row: 0, col: 4, direction: "down" },
      { number: 3, answer: "TICKET", clue: "Pass that gets you in", row: 0, col: 8, direction: "down" },
      { number: 4, answer: "LISBON", clue: "Portugal's coastal capital", row: 1, col: 7, direction: "across" },
      { number: 5, answer: "BRAZIL", clue: "Largest country in South America", row: 2, col: 6, direction: "down" },
      { number: 6, answer: "FRICTION", clue: "Force that resists sliding", row: 3, col: 2, direction: "down" },
      { number: 7, answer: "HURRICANE", clue: "Powerful tropical storm", row: 4, col: 0, direction: "across" },
      { number: 8, answer: "PLANET", clue: "Large body that circles a star", row: 5, col: 10, direction: "down" },
      { number: 9, answer: "LIBRARY", clue: "Building where books are borrowed", row: 7, col: 6, direction: "across" },
      { number: 10, answer: "BASKET", clue: "Woven container with a handle", row: 7, col: 8, direction: "down" },
      { number: 11, answer: "COFFEE", clue: "Morning brew made from beans", row: 9, col: 1, direction: "across" },
      { number: 12, answer: "SHELF", clue: "Flat board for storing books", row: 9, col: 8, direction: "across" },
      { number: 13, answer: "REPTILE", clue: "Cold-blooded animal with scales", row: 12, col: 5, direction: "across" },
    ],
  },
  {
    id: 26,
    title: "Crossword No. 26",
    rows: 13,
    cols: 13,
    words: [
      { number: 1, answer: "ANDES", clue: "Long mountain chain of South America", row: 0, col: 1, direction: "down" },
      { number: 2, answer: "SCULPTURE", clue: "Artwork carved or modeled in three dimensions", row: 0, col: 4, direction: "across" },
      { number: 3, answer: "THAMES", clue: "River that runs through London", row: 0, col: 9, direction: "down" },
      { number: 4, answer: "SAHARA", clue: "Vast desert across northern Africa", row: 2, col: 4, direction: "across" },
      { number: 4, answer: "SALMON", clue: "Fish that swims upstream to spawn", row: 2, col: 4, direction: "down" },
      { number: 5, answer: "KENYA", clue: "East African country on the equator", row: 3, col: 0, direction: "across" },
      { number: 6, answer: "BREAD", clue: "Baked staple sold by the loaf", row: 3, col: 11, direction: "down" },
      { number: 7, answer: "CHERRY", clue: "Small red fruit with a pit", row: 4, col: 7, direction: "across" },
      { number: 8, answer: "VACCINE", clue: "Shot that trains the immune system", row: 5, col: 2, direction: "down" },
      { number: 9, answer: "MONSOON", clue: "Season of heavy tropical rains", row: 6, col: 6, direction: "down" },
      { number: 10, answer: "CANYON", clue: "Deep gorge carved by a river", row: 7, col: 2, direction: "across" },
      { number: 11, answer: "SUGAR", clue: "Sweetener stirred into tea", row: 9, col: 6, direction: "across" },
      { number: 12, answer: "FOSSIL", clue: "Ancient remains preserved in rock", row: 11, col: 5, direction: "across" },
    ],
  },
  {
    id: 27,
    title: "Crossword No. 27",
    rows: 13,
    cols: 13,
    words: [
      { number: 1, answer: "PACIFIC", clue: "Largest ocean on the planet", row: 0, col: 1, direction: "down" },
      { number: 2, answer: "BISCUIT", clue: "Small baked treat", row: 0, col: 6, direction: "across" },
      { number: 2, answer: "BANANA", clue: "Curved yellow fruit", row: 0, col: 6, direction: "down" },
      { number: 3, answer: "TROPHY", clue: "Prize handed to the winner", row: 0, col: 12, direction: "down" },
      { number: 4, answer: "CURTAIN", clue: "Fabric drawn across a window", row: 1, col: 3, direction: "down" },
      { number: 5, answer: "PIANO", clue: "Keyboard with eighty-eight keys", row: 2, col: 8, direction: "across" },
      { number: 6, answer: "THUNDER", clue: "Rumble that follows lightning", row: 4, col: 3, direction: "across" },
      { number: 7, answer: "LIMA", clue: "Capital of Peru", row: 5, col: 0, direction: "across" },
      { number: 8, answer: "REFEREE", clue: "Official who enforces the rules", row: 6, col: 5, direction: "down" },
      { number: 9, answer: "ENVELOPE", clue: "Paper sleeve for a letter", row: 7, col: 2, direction: "across" },
      { number: 10, answer: "PILLOW", clue: "Soft rest for your head", row: 7, col: 8, direction: "down" },
      { number: 11, answer: "DELTA", clue: "Fan-shaped mouth of a river", row: 7, col: 11, direction: "down" },
      { number: 12, answer: "PUZZLE", clue: "Problem solved for the fun of it", row: 9, col: 0, direction: "across" },
      { number: 13, answer: "NORWAY", clue: "Land of the fjords", row: 11, col: 7, direction: "across" },
      { number: 14, answer: "ORANGE", clue: "Citrus fruit that names a color", row: 12, col: 0, direction: "across" },
    ],
  },
  {
    id: 28,
    title: "Crossword No. 28",
    rows: 13,
    cols: 13,
    words: [
      { number: 1, answer: "HAVANA", clue: "Cuban capital famous for cigars", row: 0, col: 8, direction: "down" },
      { number: 2, answer: "DOLPHIN", clue: "Clever marine mammal", row: 1, col: 3, direction: "down" },
      { number: 3, answer: "ISLAND", clue: "Land with water all around it", row: 1, col: 5, direction: "across" },
      { number: 4, answer: "PROTEIN", clue: "Nutrient built from amino acids", row: 3, col: 0, direction: "down" },
      { number: 5, answer: "MEDAL", clue: "Award that hangs on a ribbon", row: 3, col: 5, direction: "across" },
      { number: 6, answer: "ORCHESTRA", clue: "Large ensemble led by a conductor", row: 5, col: 0, direction: "across" },
      { number: 7, answer: "SURFING", clue: "Riding ocean waves on a board", row: 5, col: 5, direction: "down" },
      { number: 8, answer: "MARATHON", clue: "Race of 26.2 miles", row: 5, col: 12, direction: "down" },
      { number: 9, answer: "SALAD", clue: "Bowl of raw vegetables", row: 8, col: 2, direction: "down" },
      { number: 10, answer: "FROST", clue: "Thin icy coating on a cold morning", row: 8, col: 5, direction: "across" },
      { number: 11, answer: "SPAIN", clue: "Country of flamenco and paella", row: 8, col: 8, direction: "down" },
      { number: 12, answer: "ALMOND", clue: "Nut ground into marzipan", row: 10, col: 1, direction: "across" },
      { number: 13, answer: "LANTERN", clue: "Portable light with a handle", row: 12, col: 6, direction: "across" },
    ],
  },
  {
    id: 29,
    title: "Crossword No. 29",
    rows: 13,
    cols: 13,
    words: [
      { number: 1, answer: "CANVAS", clue: "Stretched cloth an artist paints on", row: 0, col: 3, direction: "across" },
      { number: 2, answer: "SAMURAI", clue: "Warrior of feudal Japan", row: 0, col: 8, direction: "down" },
      { number: 3, answer: "BAMBOO", clue: "Fast-growing woody grass", row: 2, col: 6, direction: "across" },
      { number: 4, answer: "OSLO", clue: "Norway's capital", row: 2, col: 11, direction: "down" },
      { number: 5, answer: "UMPIRE", clue: "Official who calls balls and strikes", row: 4, col: 4, direction: "across" },
      { number: 6, answer: "SATELLITE", clue: "Object placed in orbit around Earth", row: 6, col: 2, direction: "across" },
      { number: 6, answer: "SKATING", clue: "Gliding across ice on blades", row: 6, col: 2, direction: "down" },
      { number: 7, answer: "TOMATO", clue: "Red fruit common in salads", row: 6, col: 9, direction: "down" },
      { number: 8, answer: "AUTHOR", clue: "Person who wrote the book", row: 6, col: 12, direction: "down" },
      { number: 9, answer: "PRAIRIE", clue: "Wide expanse of grassland", row: 8, col: 0, direction: "across" },
      { number: 10, answer: "ITALY", clue: "Boot-shaped European country", row: 8, col: 5, direction: "down" },
      { number: 11, answer: "BLIZZARD", clue: "Fierce snowstorm", row: 10, col: 0, direction: "across" },
      { number: 12, answer: "TOWER", clue: "Tall and narrow structure", row: 11, col: 8, direction: "across" },
    ],
  },
  {
    id: 30,
    title: "Crossword No. 30",
    rows: 13,
    cols: 13,
    words: [
      { number: 1, answer: "BASKET", clue: "Woven container with a handle", row: 0, col: 5, direction: "down" },
      { number: 2, answer: "SANDAL", clue: "Open shoe for warm weather", row: 1, col: 4, direction: "across" },
      { number: 3, answer: "SYDNEY", clue: "Australian city with a shell-shaped opera house", row: 1, col: 12, direction: "down" },
      { number: 4, answer: "LANTERN", clue: "Portable light with a handle", row: 3, col: 3, direction: "down" },
      { number: 5, answer: "KEYBOARD", clue: "Device you type on", row: 3, col: 5, direction: "across" },
      { number: 6, answer: "YOGURT", clue: "Cultured dairy snack", row: 3, col: 7, direction: "down" },
      { number: 7, answer: "LAGOON", clue: "Shallow water sheltered by a reef", row: 4, col: 1, direction: "down" },
      { number: 8, answer: "MAGNET", clue: "Object that attracts iron", row: 5, col: 0, direction: "across" },
      { number: 9, answer: "GOALIE", clue: "Player guarding the net", row: 5, col: 7, direction: "across" },
      { number: 10, answer: "ACORN", clue: "Seed that grows into an oak", row: 5, col: 9, direction: "down" },
      { number: 11, answer: "CARTOON", clue: "Drawn or animated picture", row: 7, col: 5, direction: "across" },
      { number: 11, answer: "CANDLE", clue: "Wax column with a wick", row: 7, col: 5, direction: "down" },
      { number: 12, answer: "PIXEL", clue: "Tiny dot in a screen image", row: 12, col: 2, direction: "across" },
    ],
  },
  {
    id: 31,
    title: "Crossword No. 31",
    rows: 13,
    cols: 13,
    words: [
      { number: 1, answer: "SCARF", clue: "Wrap that keeps your neck warm", row: 0, col: 2, direction: "across" },
      { number: 1, answer: "STUDIO", clue: "Workspace of an artist", row: 0, col: 2, direction: "down" },
      { number: 2, answer: "COURAGE", clue: "Bravery in the face of fear", row: 2, col: 0, direction: "across" },
      { number: 2, answer: "CUBA", clue: "Largest island nation in the Caribbean", row: 2, col: 0, direction: "down" },
      { number: 3, answer: "PATIENCE", clue: "Ability to wait without complaint", row: 2, col: 12, direction: "down" },
      { number: 4, answer: "SUNSET", clue: "Colorful end of the day", row: 3, col: 9, direction: "down" },
      { number: 5, answer: "DROUGHT", clue: "Long stretch with no rain", row: 4, col: 6, direction: "across" },
      { number: 5, answer: "DOWNLOAD", clue: "Pull a file from the internet", row: 4, col: 6, direction: "down" },
      { number: 6, answer: "AVOCADO", clue: "Green fruit mashed into guacamole", row: 5, col: 0, direction: "across" },
      { number: 7, answer: "CHAPTER", clue: "Numbered division of a book", row: 5, col: 3, direction: "down" },
      { number: 8, answer: "SOCCER", clue: "Sport played with a round ball and feet", row: 7, col: 0, direction: "down" },
      { number: 9, answer: "TALENT", clue: "Natural ability at something", row: 7, col: 2, direction: "across" },
      { number: 10, answer: "CALENDAR", clue: "Chart of days and months", row: 10, col: 0, direction: "across" },
    ],
  },
  {
    id: 32,
    title: "Crossword No. 32",
    rows: 13,
    cols: 13,
    words: [
      { number: 1, answer: "ATLAS", clue: "Bound collection of maps", row: 0, col: 3, direction: "across" },
      { number: 2, answer: "TALENT", clue: "Natural ability at something", row: 0, col: 4, direction: "down" },
      { number: 3, answer: "NEEDLE", clue: "Slim tool used for sewing", row: 1, col: 2, direction: "down" },
      { number: 4, answer: "DELTA", clue: "Fan-shaped mouth of a river", row: 1, col: 8, direction: "down" },
      { number: 5, answer: "ECLIPSE", clue: "Event where one body hides another", row: 2, col: 2, direction: "across" },
      { number: 6, answer: "ALBUM", clue: "Collection of recorded songs", row: 2, col: 12, direction: "down" },
      { number: 7, answer: "LETTUCE", clue: "Crisp leaf at the base of a salad", row: 4, col: 10, direction: "down" },
      { number: 8, answer: "PLATEAU", clue: "Raised area of flat land", row: 5, col: 6, direction: "across" },
      { number: 9, answer: "IRON", clue: "Metal whose symbol is Fe", row: 6, col: 5, direction: "down" },
      { number: 10, answer: "AMAZON", clue: "World's largest rainforest", row: 7, col: 1, direction: "down" },
      { number: 11, answer: "CURIOSITY", clue: "Strong urge to find things out", row: 7, col: 3, direction: "across" },
      { number: 12, answer: "FALCON", clue: "Swift bird of prey", row: 9, col: 0, direction: "across" },
      { number: 13, answer: "SERVER", clue: "Machine that hosts a website", row: 10, col: 6, direction: "across" },
    ],
  },
  {
    id: 33,
    title: "Crossword No. 33",
    rows: 13,
    cols: 13,
    words: [
      { number: 1, answer: "ACTOR", clue: "Performer in a play or film", row: 0, col: 5, direction: "down" },
      { number: 2, answer: "CLIMBING", clue: "Ascending rock or an indoor wall", row: 1, col: 5, direction: "across" },
      { number: 3, answer: "BLANKET", clue: "Warm covering on a bed", row: 1, col: 9, direction: "down" },
      { number: 4, answer: "DOLPHIN", clue: "Clever marine mammal", row: 3, col: 3, direction: "down" },
      { number: 5, answer: "PARIS", clue: "Capital city on the Seine", row: 3, col: 8, direction: "across" },
      { number: 6, answer: "WHALE", clue: "Largest mammal in the ocean", row: 5, col: 0, direction: "across" },
      { number: 7, answer: "TIGER", clue: "Big cat with orange stripes", row: 6, col: 6, direction: "across" },
      { number: 7, answer: "TUNDRA", clue: "Treeless plain of the far north", row: 6, col: 6, direction: "down" },
      { number: 8, answer: "MUSEUM", clue: "Building full of exhibits", row: 7, col: 12, direction: "down" },
      { number: 9, answer: "VIKING", clue: "Norse seafarer and raider", row: 8, col: 2, direction: "across" },
      { number: 10, answer: "REPTILE", clue: "Cold-blooded animal with scales", row: 10, col: 6, direction: "across" },
      { number: 11, answer: "PASTA", clue: "Italian staple served al dente", row: 11, col: 2, direction: "across" },
      { number: 12, answer: "WISDOM", clue: "Deep insight gained from experience", row: 12, col: 7, direction: "across" },
    ],
  },
  {
    id: 34,
    title: "Crossword No. 34",
    rows: 13,
    cols: 13,
    words: [
      { number: 1, answer: "JUPITER", clue: "Biggest planet in the solar system", row: 0, col: 5, direction: "across" },
      { number: 2, answer: "POTATO", clue: "Tuber behind fries and mash", row: 0, col: 7, direction: "down" },
      { number: 3, answer: "FOSSIL", clue: "Ancient remains preserved in rock", row: 2, col: 0, direction: "across" },
      { number: 4, answer: "SILENCE", clue: "Total absence of sound", row: 2, col: 2, direction: "down" },
      { number: 5, answer: "TENNIS", clue: "Racket sport scored with love and deuce", row: 2, col: 7, direction: "across" },
      { number: 6, answer: "PAINTING", clue: "Artwork made with brush and pigment", row: 4, col: 10, direction: "down" },
      { number: 7, answer: "PERU", clue: "Country that holds Machu Picchu", row: 5, col: 1, direction: "across" },
      { number: 8, answer: "COMPASS", clue: "Instrument that points north", row: 5, col: 6, direction: "across" },
      { number: 9, answer: "CACTUS", clue: "Desert plant covered in spines", row: 7, col: 4, direction: "down" },
      { number: 10, answer: "COCONUT", clue: "Hard-shelled tropical fruit", row: 7, col: 6, direction: "across" },
      { number: 11, answer: "CARROT", clue: "Orange root vegetable", row: 7, col: 8, direction: "down" },
      { number: 12, answer: "PETAL", clue: "Colored part of a flower", row: 8, col: 1, direction: "across" },
      { number: 13, answer: "ORBIT", clue: "Curved path of a moon or planet", row: 9, col: 7, direction: "across" },
      { number: 14, answer: "MALTA", clue: "Tiny Mediterranean island nation", row: 10, col: 1, direction: "across" },
      { number: 15, answer: "PASSPORT", clue: "Travel document full of stamps", row: 12, col: 1, direction: "across" },
    ],
  },
  {
    id: 35,
    title: "Crossword No. 35",
    rows: 13,
    cols: 13,
    words: [
      { number: 1, answer: "CHORUS", clue: "Part of a song that repeats", row: 0, col: 11, direction: "down" },
      { number: 2, answer: "PEACH", clue: "Fuzzy summer fruit", row: 1, col: 7, direction: "across" },
      { number: 2, answer: "PANDA", clue: "Black-and-white bear that eats bamboo", row: 1, col: 7, direction: "down" },
      { number: 3, answer: "MONITOR", clue: "Screen attached to a computer", row: 3, col: 5, direction: "across" },
      { number: 4, answer: "MONARCH", clue: "King or queen", row: 4, col: 3, direction: "down" },
      { number: 5, answer: "INSECT", clue: "Small creature with six legs", row: 5, col: 0, direction: "down" },
      { number: 6, answer: "SOFTWARE", clue: "Programs that run on a machine", row: 5, col: 2, direction: "across" },
      { number: 7, answer: "TREATY", clue: "Formal agreement between nations", row: 5, col: 5, direction: "down" },
      { number: 8, answer: "ELEPHANT", clue: "Largest animal on land", row: 5, col: 9, direction: "down" },
      { number: 9, answer: "SENATE", clue: "Governing body of ancient Rome", row: 7, col: 0, direction: "across" },
      { number: 10, answer: "POETRY", clue: "Writing arranged in verse", row: 7, col: 7, direction: "across" },
      { number: 11, answer: "BRAZIL", clue: "Largest country in South America", row: 10, col: 7, direction: "across" },
      { number: 12, answer: "OTTER", clue: "Playful mammal of rivers and coasts", row: 12, col: 7, direction: "across" },
    ],
  },
  {
    id: 36,
    title: "Crossword No. 36",
    rows: 13,
    cols: 13,
    words: [
      { number: 1, answer: "FOREST", clue: "Large area thick with trees", row: 0, col: 5, direction: "down" },
      { number: 2, answer: "SODIUM", clue: "Element that pairs with chlorine in table salt", row: 1, col: 4, direction: "across" },
      { number: 3, answer: "JACKET", clue: "Short, light coat", row: 1, col: 12, direction: "down" },
      { number: 4, answer: "CHEESE", clue: "Dairy food made from curds", row: 3, col: 2, direction: "across" },
      { number: 5, answer: "HONEY", clue: "Sweet syrup made by bees", row: 3, col: 3, direction: "down" },
      { number: 6, answer: "HARVEST", clue: "Gathering in of the crops", row: 4, col: 8, direction: "down" },
      { number: 7, answer: "PLANET", clue: "Large body that circles a star", row: 5, col: 0, direction: "across" },
      { number: 8, answer: "AIRPORT", clue: "Where flights arrive and depart", row: 6, col: 6, direction: "across" },
      { number: 8, answer: "ANCIENT", clue: "Belonging to the very distant past", row: 6, col: 6, direction: "down" },
      { number: 9, answer: "ORCHARD", clue: "Grove planted with fruit trees", row: 6, col: 10, direction: "down" },
      { number: 10, answer: "OXYGEN", clue: "Gas we breathe, symbol O", row: 7, col: 1, direction: "across" },
      { number: 11, answer: "OLYMPICS", clue: "Games held every four years", row: 9, col: 1, direction: "across" },
      { number: 12, answer: "CURTAIN", clue: "Fabric drawn across a window", row: 11, col: 0, direction: "across" },
    ],
  },
  {
    id: 37,
    title: "Crossword No. 37",
    rows: 13,
    cols: 13,
    words: [
      { number: 1, answer: "VALLEY", clue: "Low land between hills", row: 0, col: 0, direction: "down" },
      { number: 2, answer: "STAGE", clue: "Platform where actors perform", row: 0, col: 2, direction: "down" },
      { number: 3, answer: "PICKLE", clue: "Cucumber preserved in brine", row: 1, col: 4, direction: "across" },
      { number: 3, answer: "PEANUT", clue: "Legume roasted and salted", row: 1, col: 4, direction: "down" },
      { number: 4, answer: "LASER", clue: "Tightly focused beam of light", row: 1, col: 8, direction: "down" },
      { number: 5, answer: "BREEZE", clue: "Gentle wind", row: 1, col: 12, direction: "down" },
      { number: 6, answer: "LUGGAGE", clue: "Bags packed for a trip", row: 3, col: 0, direction: "across" },
      { number: 7, answer: "KETTLE", clue: "Pot for boiling water", row: 4, col: 7, direction: "across" },
      { number: 8, answer: "VOLTAGE", clue: "Difference in electric potential", row: 6, col: 1, direction: "across" },
      { number: 9, answer: "EQUATOR", clue: "Imaginary line at zero degrees latitude", row: 6, col: 7, direction: "down" },
      { number: 10, answer: "HELIUM", clue: "Gas that makes party balloons rise", row: 7, col: 9, direction: "down" },
      { number: 11, answer: "MOLECULE", clue: "Group of bonded atoms", row: 8, col: 2, direction: "across" },
      { number: 12, answer: "BUCKET", clue: "Pail for carrying water", row: 10, col: 2, direction: "across" },
      { number: 13, answer: "DRAWER", clue: "Sliding box in a desk", row: 12, col: 2, direction: "across" },
    ],
  },
  {
    id: 38,
    title: "Crossword No. 38",
    rows: 13,
    cols: 13,
    words: [
      { number: 1, answer: "CAMERA", clue: "Device that captures photographs", row: 0, col: 3, direction: "across" },
      { number: 1, answer: "CINNAMON", clue: "Warm spice made from tree bark", row: 0, col: 3, direction: "down" },
      { number: 2, answer: "MAMMAL", clue: "Warm-blooded animal with fur or hair", row: 2, col: 0, direction: "down" },
      { number: 3, answer: "ENZYME", clue: "Protein that speeds up a reaction", row: 2, col: 2, direction: "across" },
      { number: 4, answer: "WAFFLE", clue: "Breakfast cake with square pockets", row: 4, col: 2, direction: "across" },
      { number: 5, answer: "ALGORITHM", clue: "Step-by-step procedure for solving a problem", row: 6, col: 0, direction: "across" },
      { number: 6, answer: "TROPHY", clue: "Prize handed to the winner", row: 6, col: 6, direction: "down" },
      { number: 7, answer: "ICELAND", clue: "Nordic island of geysers and glaciers", row: 6, col: 10, direction: "down" },
      { number: 8, answer: "ROBOT", clue: "Machine built to perform tasks", row: 8, col: 2, direction: "down" },
      { number: 9, answer: "OXIDE", clue: "Compound of oxygen and another element", row: 8, col: 6, direction: "across" },
      { number: 10, answer: "CLOCK", clue: "Device that shows the time", row: 9, col: 0, direction: "across" },
      { number: 11, answer: "HOCKEY", clue: "Sport played with sticks and a puck", row: 11, col: 1, direction: "across" },
      { number: 12, answer: "VENUS", clue: "Second planet from the sun", row: 11, col: 8, direction: "across" },
    ],
  },
  {
    id: 39,
    title: "Crossword No. 39",
    rows: 13,
    cols: 13,
    words: [
      { number: 1, answer: "KNIGHT", clue: "Armored warrior of the Middle Ages", row: 0, col: 0, direction: "down" },
      { number: 2, answer: "TEMPLE", clue: "Building raised for worship", row: 0, col: 7, direction: "down" },
      { number: 3, answer: "PRISM", clue: "Glass shape that splits white light", row: 0, col: 12, direction: "down" },
      { number: 4, answer: "BEAVER", clue: "Rodent that builds dams", row: 1, col: 3, direction: "across" },
      { number: 5, answer: "PLATEAU", clue: "Raised area of flat land", row: 2, col: 9, direction: "down" },
      { number: 6, answer: "CANADA", clue: "Nation with a maple leaf on its flag", row: 4, col: 3, direction: "down" },
      { number: 7, answer: "PUMPKIN", clue: "Big orange gourd of autumn", row: 4, col: 5, direction: "down" },
      { number: 8, answer: "ATOM", clue: "Smallest unit of a chemical element", row: 4, col: 9, direction: "across" },
      { number: 9, answer: "TREASURE", clue: "Hoard of valuable things", row: 5, col: 0, direction: "across" },
      { number: 10, answer: "REEF", clue: "Ridge of coral near the surface", row: 5, col: 1, direction: "down" },
      { number: 11, answer: "THEATER", clue: "Venue for plays and films", row: 6, col: 11, direction: "down" },
      { number: 12, answer: "PHARAOH", clue: "Ruler of ancient Egypt", row: 7, col: 5, direction: "across" },
      { number: 13, answer: "PACIFIC", clue: "Largest ocean on the planet", row: 9, col: 2, direction: "across" },
      { number: 14, answer: "MIRROR", clue: "Glass that shows your reflection", row: 12, col: 6, direction: "across" },
    ],
  },
  {
    id: 40,
    title: "Crossword No. 40",
    rows: 13,
    cols: 13,
    words: [
      { number: 1, answer: "SKELETON", clue: "Framework of bones in the body", row: 0, col: 1, direction: "across" },
      { number: 2, answer: "THEORY", clue: "Well-tested scientific explanation", row: 0, col: 6, direction: "down" },
      { number: 3, answer: "BRIDGE", clue: "Structure that spans a river", row: 2, col: 1, direction: "across" },
      { number: 4, answer: "CAMEL", clue: "Desert animal with humps", row: 2, col: 8, direction: "across" },
      { number: 4, answer: "CLOUD", clue: "Floating mass of water vapor", row: 2, col: 8, direction: "down" },
      { number: 5, answer: "KANGAROO", clue: "Marsupial that gets around by hopping", row: 4, col: 1, direction: "across" },
      { number: 6, answer: "ATLANTIC", clue: "Ocean between Europe and the Americas", row: 4, col: 2, direction: "down" },
      { number: 7, answer: "DELHI", clue: "Sprawling capital region of India", row: 6, col: 0, direction: "across" },
      { number: 7, answer: "DUBLIN", clue: "Irish capital on the Liffey", row: 6, col: 0, direction: "down" },
      { number: 8, answer: "CRICKET", clue: "Sport with wickets and overs", row: 6, col: 11, direction: "down" },
      { number: 9, answer: "MELODY", clue: "Tune you can hum", row: 7, col: 7, direction: "down" },
      { number: 10, answer: "NOODLE", clue: "Long strand in a bowl of soup", row: 8, col: 2, direction: "across" },
      { number: 11, answer: "RELAY", clue: "Race in which a baton is passed", row: 8, col: 9, direction: "down" },
      { number: 12, answer: "DRAWER", clue: "Sliding box in a desk", row: 11, col: 7, direction: "across" },
    ],
  },
  {
    id: 41,
    title: "Crossword No. 41",
    rows: 13,
    cols: 13,
    words: [
      { number: 1, answer: "CHILE", clue: "Long, narrow South American country", row: 0, col: 1, direction: "across" },
      { number: 2, answer: "HARBOR", clue: "Sheltered spot where ships dock", row: 0, col: 2, direction: "down" },
      { number: 3, answer: "GRAVITY", clue: "Force that pulls objects toward Earth", row: 0, col: 11, direction: "down" },
      { number: 4, answer: "FLUTE", clue: "Woodwind you blow across", row: 1, col: 0, direction: "down" },
      { number: 5, answer: "EMPIRE", clue: "Many lands under a single ruler", row: 1, col: 7, direction: "across" },
      { number: 6, answer: "PEPPER", clue: "Spice ground from dried peppercorns", row: 2, col: 4, direction: "down" },
      { number: 7, answer: "UMBRELLA", clue: "Portable shield against rain", row: 3, col: 0, direction: "across" },
      { number: 8, answer: "GLACIER", clue: "Slow-moving river of ice", row: 3, col: 9, direction: "down" },
      { number: 9, answer: "PORTRAIT", clue: "Artwork depicting a person", row: 5, col: 4, direction: "across" },
      { number: 10, answer: "RUMOR", clue: "Story passed along without proof", row: 7, col: 0, direction: "across" },
      { number: 11, answer: "MEADOW", clue: "Open field of grass and flowers", row: 7, col: 2, direction: "down" },
      { number: 12, answer: "GUITAR", clue: "Instrument with six strings", row: 7, col: 6, direction: "down" },
      { number: 13, answer: "BUTTER", clue: "Spread churned from cream", row: 8, col: 5, direction: "across" },
      { number: 14, answer: "BALLET", clue: "Classical dance done on pointe", row: 11, col: 5, direction: "across" },
    ],
  },
  {
    id: 42,
    title: "Crossword No. 42",
    rows: 13,
    cols: 13,
    words: [
      { number: 1, answer: "ARCHIVE", clue: "Store of historical records", row: 0, col: 7, direction: "down" },
      { number: 2, answer: "COURAGE", clue: "Bravery in the face of fear", row: 1, col: 4, direction: "across" },
      { number: 3, answer: "BALANCE", clue: "Even distribution of weight", row: 1, col: 12, direction: "down" },
      { number: 4, answer: "PENCIL", clue: "Writing tool with a graphite core", row: 2, col: 2, direction: "down" },
      { number: 5, answer: "ONION", clue: "Layered bulb that brings on tears", row: 4, col: 1, direction: "across" },
      { number: 6, answer: "VIOLIN", clue: "String instrument played with a bow", row: 5, col: 7, direction: "across" },
      { number: 7, answer: "LADDER", clue: "Climbing frame with rungs", row: 5, col: 10, direction: "down" },
      { number: 8, answer: "SUITCASE", clue: "Travel bag with a handle", row: 6, col: 0, direction: "across" },
      { number: 9, answer: "ARCHERY", clue: "Sport of the bow and arrow", row: 6, col: 5, direction: "down" },
      { number: 10, answer: "GALAXY", clue: "Enormous system of stars and dust", row: 7, col: 8, direction: "down" },
      { number: 11, answer: "RHYTHM", clue: "Underlying beat of a piece", row: 9, col: 1, direction: "across" },
      { number: 12, answer: "CAIRO", clue: "Egyptian capital near the Giza pyramids", row: 10, col: 7, direction: "across" },
      { number: 13, answer: "DESERT", clue: "Region that gets almost no rain", row: 11, col: 1, direction: "across" },
    ],
  },
  {
    id: 43,
    title: "Crossword No. 43",
    rows: 13,
    cols: 13,
    words: [
      { number: 1, answer: "JOURNEY", clue: "Long trip from place to place", row: 0, col: 11, direction: "down" },
      { number: 2, answer: "BAMBOO", clue: "Fast-growing woody grass", row: 1, col: 6, direction: "across" },
      { number: 3, answer: "BATTERY", clue: "Portable source of power", row: 1, col: 9, direction: "down" },
      { number: 4, answer: "MURAL", clue: "Painting made directly on a wall", row: 2, col: 1, direction: "down" },
      { number: 5, answer: "SATURN", clue: "Planet famous for its bright rings", row: 3, col: 7, direction: "across" },
      { number: 6, answer: "TRUMPET", clue: "Brass instrument with three valves", row: 4, col: 0, direction: "across" },
      { number: 7, answer: "ANCHOR", clue: "Heavy weight that holds a ship", row: 5, col: 7, direction: "down" },
      { number: 8, answer: "OLIVE", clue: "Small fruit pressed for its oil", row: 6, col: 0, direction: "across" },
      { number: 9, answer: "VOLCANO", clue: "Mountain that can erupt", row: 6, col: 3, direction: "down" },
      { number: 10, answer: "ENERGY", clue: "Capacity to do work", row: 6, col: 6, direction: "across" },
      { number: 11, answer: "COFFEE", clue: "Morning brew made from beans", row: 7, col: 5, direction: "down" },
      { number: 12, answer: "RELIC", clue: "Object surviving from the distant past", row: 8, col: 12, direction: "down" },
      { number: 13, answer: "FIREWALL", clue: "Barrier that filters network traffic", row: 10, col: 5, direction: "across" },
      { number: 14, answer: "KOREA", clue: "Peninsula split into north and south", row: 12, col: 2, direction: "across" },
    ],
  },
  {
    id: 44,
    title: "Crossword No. 44",
    rows: 13,
    cols: 13,
    words: [
      { number: 1, answer: "KITCHEN", clue: "Room where meals are cooked", row: 0, col: 0, direction: "down" },
      { number: 2, answer: "GARLIC", clue: "Pungent bulb used in cooking", row: 0, col: 5, direction: "across" },
      { number: 2, answer: "GREECE", clue: "Birthplace of the ancient Olympics", row: 0, col: 5, direction: "down" },
      { number: 3, answer: "TURTLE", clue: "Reptile that carries a shell", row: 2, col: 0, direction: "across" },
      { number: 4, answer: "MADRID", clue: "Capital of Spain", row: 3, col: 12, direction: "down" },
      { number: 5, answer: "PEACH", clue: "Fuzzy summer fruit", row: 4, col: 2, direction: "across" },
      { number: 6, answer: "BLOSSOM", clue: "Flower on a fruit tree", row: 4, col: 8, direction: "down" },
      { number: 7, answer: "GENOME", clue: "Complete set of an organism's genes", row: 5, col: 10, direction: "down" },
      { number: 8, answer: "NEPAL", clue: "Himalayan country bordering Tibet", row: 6, col: 0, direction: "across" },
      { number: 9, answer: "PENGUIN", clue: "Flightless bird of the far south", row: 6, col: 2, direction: "down" },
      { number: 10, answer: "ITALY", clue: "Boot-shaped European country", row: 6, col: 6, direction: "down" },
      { number: 11, answer: "PASSWORD", clue: "Secret string that unlocks an account", row: 8, col: 5, direction: "across" },
      { number: 12, answer: "JOURNEY", clue: "Long trip from place to place", row: 10, col: 0, direction: "across" },
      { number: 13, answer: "NOTEBOOK", clue: "Bound pages for jotting things down", row: 12, col: 2, direction: "across" },
    ],
  },
];

/** Total number of puzzles in the bank. */
export const PUZZLE_COUNT = CROSSWORD_PUZZLES.length;

/**
 * Build-time sanity check for grid consistency.
 *
 * Validates, for every puzzle:
 *  - all answers are uppercase A-Z and fit inside the declared grid
 *  - every crossing letter agrees between the across and down word
 *  - grid numbers are sequential row-major across distinct starting squares
 *  - two words never start at the same square in the same direction
 *  - no answer is repeated inside a single puzzle
 *
 * Runs only in development so production bundles pay nothing for it.
 */
export function validateCrosswordPuzzles(
  puzzles: CrosswordPuzzle[] = CROSSWORD_PUZZLES,
): string[] {
  const errors: string[] = [];

  for (const puzzle of puzzles) {
    const label = `Puzzle ${puzzle.id}`;
    const letters = new Map<string, string>();
    const slots = new Set<string>();
    const answers = new Set<string>();

    for (const word of puzzle.words) {
      if (!/^[A-Z]+$/.test(word.answer)) {
        errors.push(`${label}: answer "${word.answer}" is not plain uppercase A-Z`);
        continue;
      }
      if (word.clue.trim().length === 0) {
        errors.push(`${label}: answer "${word.answer}" has an empty clue`);
      }
      if (answers.has(word.answer)) {
        errors.push(`${label}: answer "${word.answer}" appears twice`);
      }
      answers.add(word.answer);

      const slotKey = `${word.row}:${word.col}:${word.direction}`;
      if (slots.has(slotKey)) {
        errors.push(`${label}: two words start at ${slotKey}`);
      }
      slots.add(slotKey);

      const dr = word.direction === "down" ? 1 : 0;
      const dc = word.direction === "across" ? 1 : 0;

      for (let i = 0; i < word.answer.length; i += 1) {
        const r = word.row + dr * i;
        const c = word.col + dc * i;
        if (r < 0 || c < 0 || r >= puzzle.rows || c >= puzzle.cols) {
          errors.push(`${label}: "${word.answer}" runs outside the ${puzzle.rows}x${puzzle.cols} grid`);
          break;
        }
        const cellKey = `${r}:${c}`;
        const existing = letters.get(cellKey);
        const letter = word.answer[i];
        if (existing !== undefined && existing !== letter) {
          errors.push(
            `${label}: crossing conflict at (${r}, ${c}) — "${existing}" vs "${letter}" from "${word.answer}"`,
          );
        }
        letters.set(cellKey, letter);
      }
    }

    const starts = Array.from(
      new Set(puzzle.words.map((w) => `${w.row}:${w.col}`)),
    )
      .map((key) => key.split(":").map(Number) as [number, number])
      .sort((a, b) => (a[0] - b[0]) || (a[1] - b[1]));

    const expected = new Map<string, number>();
    starts.forEach(([r, c], index) => expected.set(`${r}:${c}`, index + 1));

    for (const word of puzzle.words) {
      const want = expected.get(`${word.row}:${word.col}`);
      if (want !== word.number) {
        errors.push(
          `${label}: "${word.answer}" is numbered ${word.number} but should be ${want}`,
        );
      }
    }
  }

  return errors;
}

if (import.meta.env.DEV) {
  const problems = validateCrosswordPuzzles();
  if (problems.length > 0) {
    console.error(
      `[crossword] ${problems.length} puzzle data problem(s):\n` + problems.join("\n"),
    );
  }
}
