// Word Groups puzzle bank — 60 hand-authored, original puzzles.
// IMPORTANT: These puzzles are ORIGINAL content authored for Skycally.
// Do NOT copy actual NYT Connections categories or word groupings — those
// are the newspaper's editorial work and copying them would be a copyright
// problem. Each puzzle here is a fresh combination.
//
// Structure: 4 categories × 4 words = 16 unique words per puzzle.
// Difficulty order: yellow (easiest) → green → blue → purple (trickiest).
// At least one deliberate overlap/trap word per puzzle.

export type Difficulty = "yellow" | "green" | "blue" | "purple";

export type Category = {
  name: string;
  difficulty: Difficulty;
  words: [string, string, string, string];
};

export type Puzzle = {
  id: number;
  categories: [Category, Category, Category, Category];
};

const P = (
  id: number,
  y: [string, [string, string, string, string]],
  g: [string, [string, string, string, string]],
  b: [string, [string, string, string, string]],
  p: [string, [string, string, string, string]],
): Puzzle => ({
  id,
  categories: [
    { name: y[0], difficulty: "yellow", words: y[1] },
    { name: g[0], difficulty: "green", words: g[1] },
    { name: b[0], difficulty: "blue", words: b[1] },
    { name: p[0], difficulty: "purple", words: p[1] },
  ],
});

export const PUZZLES: Puzzle[] = [
  P(1,
    ["Fruits", ["APPLE", "PEAR", "PEACH", "PLUM"]],
    ["Shades of blue", ["NAVY", "TEAL", "COBALT", "AZURE"]],
    ["Ballroom dances", ["TANGO", "WALTZ", "SALSA", "RUMBA"]],
    ["___ tree", ["FAMILY", "PALM", "CHRISTMAS", "SHOE"]],
  ),
  P(2,
    ["Baking basics", ["FLOUR", "SUGAR", "BUTTER", "YEAST"]],
    ["Big cats", ["LION", "TIGER", "JAGUAR", "LEOPARD"]],
    ["Card suits", ["HEART", "SPADE", "CLUB", "DIAMOND"]],
    ["___ ring", ["BOXING", "ONION", "PHONE", "KEY"]],
  ),
  P(3,
    ["Bodies of water", ["LAKE", "RIVER", "POND", "SEA"]],
    ["Musical instruments", ["DRUM", "FLUTE", "GUITAR", "HARP"]],
    ["Chess pieces", ["KING", "QUEEN", "ROOK", "KNIGHT"]],
    ["Bee ___", ["HIVE", "LINE", "KEEPER", "STING"]],
  ),
  P(4,
    ["Farm animals", ["COW", "PIG", "GOAT", "SHEEP"]],
    ["Pasta shapes", ["PENNE", "ZITI", "ROTINI", "ORZO"]],
    ["Cloud types", ["CIRRUS", "STRATUS", "CUMULUS", "NIMBUS"]],
    ["___ bar", ["CANDY", "SNACK", "CROW", "SAND"]],
  ),
  P(5,
    ["Wind instruments", ["OBOE", "CLARINET", "TRUMPET", "FLUTE"]],
    ["Gemstones", ["RUBY", "PEARL", "TOPAZ", "OPAL"]],
    ["Trouser styles", ["JEANS", "KHAKIS", "SLACKS", "CHINOS"]],
    ["___ bath", ["BUBBLE", "BLOOD", "BIRD", "SUN"]],
  ),
  P(6,
    ["Board games", ["CHESS", "CLUE", "RISK", "SORRY"]],
    ["Breads", ["BAGEL", "BAGUETTE", "PITA", "NAAN"]],
    ["Coffee drinks", ["LATTE", "MOCHA", "AMERICANO", "CORTADO"]],
    ["Excuses", ["ALIBI", "PRETEXT", "REASON", "PLEA"]],
  ),
  P(7,
    ["Currencies", ["DOLLAR", "EURO", "YEN", "PESO"]],
    ["Units of weight", ["GRAM", "OUNCE", "TON", "POUND"]],
    ["Boxing terms", ["JAB", "HOOK", "CROSS", "UPPERCUT"]],
    ["___ cake", ["CUP", "PAN", "SPONGE", "CHEESE"]],
  ),
  P(8,
    ["Dog breeds", ["POODLE", "BEAGLE", "HUSKY", "BOXER"]],
    ["Bathroom items", ["TOWEL", "SOAP", "SHAMPOO", "LOOFAH"]],
    ["Coffee terms", ["BREW", "GROUND", "ROAST", "BEAN"]],
    ["___ bag", ["SLEEPING", "PUNCH", "TEA", "HAND"]],
  ),
  P(9,
    ["Rainbow colors", ["RED", "ORANGE", "INDIGO", "VIOLET"]],
    ["Stone fruits", ["CHERRY", "PEACH", "MANGO", "OLIVE"]],
    ["Types of tea", ["GREEN", "BLACK", "WHITE", "CHAI"]],
    ["___ house", ["LIGHT", "FARM", "DOG", "TREE"]],
  ),
  P(10,
    ["Ball sports", ["SOCCER", "TENNIS", "GOLF", "RUGBY"]],
    ["US presidents", ["LINCOLN", "GRANT", "JEFFERSON", "WILSON"]],
    ["Car body types", ["SEDAN", "COUPE", "WAGON", "HATCHBACK"]],
    ["___ ball", ["CURVE", "EYE", "MOTH", "SNOW"]],
  ),
  P(11,
    ["Kitchen appliances", ["BLENDER", "TOASTER", "KETTLE", "OVEN"]],
    ["Card game actions", ["DEAL", "SHUFFLE", "DRAW", "FOLD"]],
    ["Laundry cycles", ["WASH", "RINSE", "SPIN", "DRY"]],
    ["Types of humor", ["WITTY", "DARK", "SLAPSTICK", "DEADPAN"]],
  ),
  P(12,
    ["Types of nut", ["ALMOND", "CASHEW", "PECAN", "WALNUT"]],
    ["Egg preparations", ["POACHED", "SCRAMBLED", "FRIED", "BOILED"]],
    ["Winter gear", ["SCARF", "GLOVE", "BEANIE", "PARKA"]],
    ["Hard to crack", ["CODE", "CASE", "NUT", "SHELL"]],
  ),
  P(13,
    ["Beach items", ["TOWEL", "UMBRELLA", "COOLER", "SANDAL"]],
    ["Ocean creatures", ["OCTOPUS", "DOLPHIN", "SHARK", "MANATEE"]],
    ["Sun ___", ["FLOWER", "BURN", "SET", "GLASSES"]],
    ["Ways to laugh", ["CHUCKLE", "GIGGLE", "SNICKER", "GUFFAW"]],
  ),
  P(14,
    ["Continents", ["AFRICA", "ASIA", "EUROPE", "AUSTRALIA"]],
    ["Planets", ["MARS", "VENUS", "SATURN", "NEPTUNE"]],
    ["Roman gods", ["JUPITER", "MERCURY", "PLUTO", "APOLLO"]],
    ["Chocolate bars", ["MARS", "TWIX", "SNICKERS", "KITKAT"]],
  ),
  P(15,
    ["Pizza toppings", ["PEPPERONI", "OLIVE", "MUSHROOM", "ONION"]],
    ["Salad greens", ["ARUGULA", "SPINACH", "KALE", "ROMAINE"]],
    ["Herbs", ["BASIL", "THYME", "PARSLEY", "SAGE"]],
    ["Sage ___", ["ADVICE", "GRASS", "GREEN", "BRUSH"]],
  ),
  P(16,
    ["Zodiac signs", ["ARIES", "LEO", "TAURUS", "PISCES"]],
    ["Yoga poses", ["COBRA", "CHILD", "WARRIOR", "TREE"]],
    ["Snakes", ["ADDER", "PYTHON", "MAMBA", "VIPER"]],
    ["Programming languages", ["PYTHON", "JAVA", "RUBY", "SWIFT"]],
  ),
  P(17,
    ["Camping gear", ["TENT", "LANTERN", "SLEEPING", "COMPASS"]],
    ["Types of light", ["FLASH", "STROBE", "SPOT", "MOON"]],
    ["Directions", ["NORTH", "SOUTH", "EAST", "WEST"]],
    ["Wild ___", ["FLOWER", "FIRE", "CARD", "LIFE"]],
  ),
  P(18,
    ["Toolbox items", ["HAMMER", "WRENCH", "PLIERS", "SCREWDRIVER"]],
    ["Types of screw", ["PHILLIPS", "FLATHEAD", "TORX", "HEX"]],
    ["Nuts and bolts", ["LOCK", "WING", "CAP", "ACORN"]],
    ["Kinds of party", ["BLOCK", "HOUSE", "GARDEN", "POOL"]],
  ),
  P(19,
    ["Breakfast foods", ["PANCAKE", "WAFFLE", "CEREAL", "OATMEAL"]],
    ["Syrups", ["MAPLE", "CARAMEL", "HAZELNUT", "VANILLA"]],
    ["Ice cream flavors", ["CHOCOLATE", "STRAWBERRY", "PISTACHIO", "MINT"]],
    ["Mint ___", ["CONDITION", "JULEP", "CHIP", "LEAF"]],
  ),
  P(20,
    ["Cutlery", ["FORK", "SPOON", "KNIFE", "CHOPSTICK"]],
    ["Roads", ["AVENUE", "BOULEVARD", "LANE", "HIGHWAY"]],
    ["Fork ___", ["LIFT", "TONGUE", "OVER", "NIFE"]],
    ["Bank terms", ["DEPOSIT", "LOAN", "CREDIT", "INTEREST"]],
  ),
  P(21,
    ["Types of dance", ["BALLET", "HIPHOP", "JAZZ", "TAP"]],
    ["Faucet actions", ["DRIP", "LEAK", "GUSH", "TRICKLE"]],
    ["Water features", ["FOUNTAIN", "GEYSER", "SPRING", "WATERFALL"]],
    ["Tap ___", ["ROOT", "WATER", "DANCE", "OUT"]],
  ),
  P(22,
    ["Bakery items", ["MUFFIN", "SCONE", "CROISSANT", "DONUT"]],
    ["Round things", ["WHEEL", "COIN", "PLATE", "MOON"]],
    ["Board games", ["MONOPOLY", "SCRABBLE", "CATAN", "OTHELLO"]],
    ["Shakespeare plays", ["OTHELLO", "HAMLET", "MACBETH", "TEMPEST"]],
  ),
  P(23,
    ["Ship parts", ["HULL", "MAST", "DECK", "ANCHOR"]],
    ["Deck ___", ["CHAIR", "HAND", "OUT", "SHOE"]],
    ["Card games", ["POKER", "BRIDGE", "RUMMY", "HEARTS"]],
    ["Body parts", ["ELBOW", "SHOULDER", "KNEE", "ANKLE"]],
  ),
  P(24,
    ["Movie genres", ["COMEDY", "DRAMA", "HORROR", "THRILLER"]],
    ["Halloween costumes", ["GHOST", "VAMPIRE", "WITCH", "MUMMY"]],
    ["Mummy ___", ["DEAREST", "WRAP", "CASE", "BAG"]],
    ["Wrap ___", ["AROUND", "PAPER", "UP", "PARTY"]],
  ),
  P(25,
    ["Emotions", ["JOY", "ANGER", "FEAR", "SADNESS"]],
    ["Pixar movies", ["UP", "COCO", "SOUL", "CARS"]],
    ["Car brands", ["FORD", "TOYOTA", "HONDA", "SUBARU"]],
    ["Ford ___", ["FOCUS", "MUSTANG", "ESCAPE", "FIESTA"]],
  ),
  P(26,
    ["Bird features", ["BEAK", "FEATHER", "WING", "TALON"]],
    ["Birds of prey", ["EAGLE", "HAWK", "FALCON", "OWL"]],
    ["NFL teams", ["EAGLES", "HAWKS", "FALCONS", "RAVENS"]],
    ["Raven-haired ___", ["BEAUTY", "GIRL", "QUEEN", "SISTER"]],
  ),
  P(27,
    ["Types of soup", ["MISO", "MINESTRONE", "CHOWDER", "GAZPACHO"]],
    ["Cold things", ["ICE", "SNOW", "FROST", "HAIL"]],
    ["Hail ___", ["MARY", "STORM", "STONE", "CAB"]],
    ["Rain-related", ["DRIZZLE", "SHOWER", "POUR", "SPRINKLE"]],
  ),
  P(28,
    ["Painting tools", ["BRUSH", "ROLLER", "PALETTE", "EASEL"]],
    ["Hair styles", ["BOB", "PIXIE", "MULLET", "BRAID"]],
    ["Roller ___", ["COASTER", "SKATE", "BLADE", "DERBY"]],
    ["Skate ___", ["BOARD", "PARK", "RINK", "SHOP"]],
  ),
  P(29,
    ["Insects", ["ANT", "BEE", "MOTH", "WASP"]],
    ["Buzzing sounds", ["HUM", "BUZZ", "DRONE", "WHIR"]],
    ["Drone ___", ["STRIKE", "SHOT", "PILOT", "ZONE"]],
    ["Zones", ["TIME", "END", "SCHOOL", "COMFORT"]],
  ),
  P(30,
    ["Sea creatures", ["CRAB", "LOBSTER", "SHRIMP", "SQUID"]],
    ["Crabby moods", ["GRUMPY", "CRANKY", "SURLY", "MOODY"]],
    ["Squid ink uses", ["PASTA", "SAUCE", "PAINT", "DYE"]],
    ["Types of ink", ["INDIA", "TATTOO", "PRINTER", "PEN"]],
  ),
  P(31,
    ["Instruments played by hand", ["PIANO", "HARP", "TAMBOURINE", "MARACAS"]],
    ["Silent letters", ["KNIFE", "GNOME", "PSALM", "WRIST"]],
    ["Body parts you can twist", ["WRIST", "ANKLE", "NECK", "HIP"]],
    ["Hip ___", ["HOP", "BONE", "STER", "POCKET"]],
  ),
  P(32,
    ["School subjects", ["MATH", "HISTORY", "BIOLOGY", "ART"]],
    ["Art supplies", ["CRAYON", "MARKER", "CHALK", "PENCIL"]],
    ["Chalk ___", ["BOARD", "LINE", "DUST", "TALK"]],
    ["Talk shows", ["ELLEN", "OPRAH", "TONIGHT", "VIEW"]],
  ),
  P(33,
    ["Camping activities", ["HIKING", "FISHING", "KAYAKING", "CLIMBING"]],
    ["Fishing gear", ["ROD", "REEL", "LURE", "BAIT"]],
    ["Reel ___", ["IN", "TIME", "MOWER", "SPINNING"]],
    ["Types of dance move", ["SPIN", "TWIRL", "DIP", "STEP"]],
  ),
  P(34,
    ["Types of soup base", ["BROTH", "STOCK", "CREAM", "BISQUE"]],
    ["Stock ___", ["MARKET", "PILE", "BROKER", "YARD"]],
    ["Market ___", ["PLACE", "SHARE", "PRICE", "ING"]],
    ["Words meaning agreement", ["YES", "AYE", "OKAY", "SURE"]],
  ),
  P(35,
    ["Bee-related", ["HONEY", "HIVE", "SWARM", "POLLEN"]],
    ["Terms of endearment", ["HONEY", "DEAR", "SWEETIE", "DARLING"]],
    ["Words meaning group", ["SWARM", "FLOCK", "HERD", "PACK"]],
    ["Pack ___", ["AGE", "MULE", "RAT", "ICE"]],
  ),
  P(36,
    ["Bathroom fixtures", ["SINK", "TOILET", "TUB", "SHOWER"]],
    ["Baby ___", ["SHOWER", "SITTER", "FACE", "PROOF"]],
    ["Face ___", ["OFF", "PALM", "TIME", "LIFT"]],
    ["Weightlifting moves", ["LIFT", "PRESS", "CURL", "SQUAT"]],
  ),
  P(37,
    ["Salad dressings", ["RANCH", "CAESAR", "ITALIAN", "FRENCH"]],
    ["Salute languages", ["CIAO", "HELLO", "BONJOUR", "HOLA"]],
    ["Words after French", ["KISS", "FRIES", "TOAST", "BREAD"]],
    ["Words after Italian", ["ICE", "JOB", "LEATHER", "SAUSAGE"]],
  ),
  P(38,
    ["Precipitation", ["RAIN", "SNOW", "SLEET", "HAIL"]],
    ["Rain-related", ["FOREST", "COAT", "DROP", "BOW"]],
    ["Snow-related", ["FLAKE", "BALL", "MAN", "STORM"]],
    ["Kinds of storm", ["THUNDER", "DUST", "BRAIN", "IDEA"]],
  ),
  P(39,
    ["Types of bread roll", ["BUN", "BRIOCHE", "KAISER", "CIABATTA"]],
    ["Hairstyles worn up", ["BUN", "PONYTAIL", "TOPKNOT", "BRAID"]],
    ["Ways to say thanks", ["THANKS", "GRACIAS", "MERCI", "DANKE"]],
    ["Grace ___", ["FUL", "NOTE", "PERIOD", "LAND"]],
  ),
  P(40,
    ["Roof parts", ["SHINGLE", "GUTTER", "EAVE", "CHIMNEY"]],
    ["Fireplace items", ["LOG", "POKER", "ASH", "GRATE"]],
    ["Poker terms", ["BLUFF", "CHIP", "ANTE", "RAISE"]],
    ["Raise ___", ["EYEBROW", "CANE", "FLAG", "GLASS"]],
  ),
  P(41,
    ["Beverages", ["JUICE", "MILK", "SODA", "WATER"]],
    ["Water ___", ["FALL", "MELON", "COLOR", "SHED"]],
    ["Shed ___", ["LIGHT", "TEARS", "SKIN", "POUNDS"]],
    ["Skin ___", ["CARE", "TIGHT", "DEEP", "CANCER"]],
  ),
  P(42,
    ["Halloween creatures", ["GHOST", "GHOUL", "GOBLIN", "ZOMBIE"]],
    ["Ghost ___", ["WRITER", "TOWN", "SHIP", "STORY"]],
    ["Story elements", ["PLOT", "THEME", "SETTING", "CHARACTER"]],
    ["Plot ___", ["TWIST", "HOLE", "LINE", "DEVICE"]],
  ),
  P(43,
    ["Types of pepper", ["BELL", "CHILI", "HABANERO", "JALAPENO"]],
    ["Bell ___", ["BOY", "HOP", "PEPPER", "TOWER"]],
    ["Ring ___", ["TONE", "MASTER", "LEADER", "WORM"]],
    ["Worm-related", ["EARTH", "SILK", "TAPE", "BOOK"]],
  ),
  P(44,
    ["Baseball positions", ["PITCHER", "CATCHER", "SHORTSTOP", "OUTFIELDER"]],
    ["Pitcher of ___", ["WATER", "BEER", "LEMONADE", "MILK"]],
    ["Ways to throw", ["TOSS", "HURL", "FLING", "CHUCK"]],
    ["Chuck ___", ["ROAST", "STEAK", "WAGON", "BERRY"]],
  ),
  P(45,
    ["Cocktail ingredients", ["VODKA", "TONIC", "LIME", "MINT"]],
    ["Mint condition means", ["PERFECT", "PRISTINE", "FLAWLESS", "NEW"]],
    ["Ways to say new", ["FRESH", "NOVEL", "RECENT", "MODERN"]],
    ["Fresh ___", ["MAN", "WATER", "PRINCE", "START"]],
  ),
  P(46,
    ["Superhero names", ["BATMAN", "SUPERMAN", "SPIDERMAN", "IRONMAN"]],
    ["Iron ___", ["FIST", "AGE", "MAIDEN", "CLAD"]],
    ["Metals", ["IRON", "COPPER", "TIN", "LEAD"]],
    ["Lead ___", ["SINGER", "ROLE", "PIPE", "TIME"]],
  ),
  P(47,
    ["Cheese types", ["CHEDDAR", "BRIE", "GOUDA", "FETA"]],
    ["Feta-adjacent", ["OLIVE", "TOMATO", "CUCUMBER", "OREGANO"]],
    ["Green things", ["GRASS", "MOSS", "LEAF", "FROG"]],
    ["Frog ___", ["LEG", "PRINCE", "MAN", "SPAWN"]],
  ),
  P(48,
    ["Book parts", ["SPINE", "COVER", "PAGE", "CHAPTER"]],
    ["Page ___", ["TURNER", "BOY", "COUNT", "BREAK"]],
    ["Break ___", ["FAST", "UP", "DOWN", "OUT"]],
    ["Fast ___", ["FOOD", "TRACK", "BALL", "LANE"]],
  ),
  P(49,
    ["Astrology moons", ["FULL", "NEW", "HALF", "CRESCENT"]],
    ["Full ___", ["HOUSE", "MOON", "STOP", "COURT"]],
    ["Court ___", ["ROOM", "SHIP", "ORDER", "YARD"]],
    ["Yard ___", ["STICK", "SALE", "WORK", "AGE"]],
  ),
  P(50,
    ["Bathroom actions", ["SHAVE", "BRUSH", "FLOSS", "RINSE"]],
    ["Dance moves", ["FLOSS", "DAB", "TWIST", "SHUFFLE"]],
    ["Music genres", ["ROCK", "JAZZ", "BLUES", "COUNTRY"]],
    ["Country ___", ["CLUB", "SIDE", "MUSIC", "ROAD"]],
  ),
  P(51,
    ["Types of table", ["COFFEE", "DINNER", "PICNIC", "POOL"]],
    ["Pool ___", ["PARTY", "TABLE", "NOODLE", "SIDE"]],
    ["Side ___", ["WALK", "KICK", "BAR", "SHOW"]],
    ["Walk ___", ["OVER", "WAY", "OUT", "IN"]],
  ),
  P(52,
    ["Time periods", ["HOUR", "DAY", "WEEK", "MONTH"]],
    ["Day ___", ["DREAM", "LIGHT", "TIME", "BREAK"]],
    ["Dream ___", ["CATCHER", "TEAM", "LAND", "BOAT"]],
    ["Team ___", ["MATE", "WORK", "PLAYER", "STER"]],
  ),
  P(53,
    ["Ocean waves", ["SWELL", "SURF", "TIDE", "RIPPLE"]],
    ["Tide ___", ["POOL", "WATER", "TABLE", "MARK"]],
    ["Mark ___", ["UP", "DOWN", "ER", "ET"]],
    ["Word ___", ["PLAY", "COUNT", "SEARCH", "SMITH"]],
  ),
  P(54,
    ["Types of note", ["STICKY", "BANK", "PROMISSORY", "MUSICAL"]],
    ["Bank ___", ["ROLL", "NOTE", "ROBBER", "ACCOUNT"]],
    ["Roll ___", ["OVER", "CALL", "MODEL", "ING"]],
    ["Model ___", ["CITIZEN", "AIRPLANE", "AGENCY", "TRAIN"]],
  ),
  P(55,
    ["Model train parts", ["TRACK", "LOCOMOTIVE", "CABOOSE", "CAR"]],
    ["Track ___", ["SUIT", "STAR", "RECORD", "PAD"]],
    ["Star ___", ["FISH", "GAZER", "LIGHT", "BURST"]],
    ["Burst ___", ["OPEN", "PIPE", "OUT", "IN"]],
  ),
  P(56,
    ["Types of light bulb", ["LED", "HALOGEN", "INCANDESCENT", "NEON"]],
    ["Neon ___", ["SIGN", "LIGHT", "GREEN", "PINK"]],
    ["Pink ___", ["PANTHER", "EYE", "SLIP", "FLOYD"]],
    ["Ways to slip", ["SLIDE", "SKID", "STUMBLE", "TRIP"]],
  ),
  P(57,
    ["Trip types", ["ROAD", "GUILT", "FIELD", "DAY"]],
    ["Road ___", ["TRIP", "MAP", "BLOCK", "KILL"]],
    ["Map ___", ["MAKER", "READER", "OUT", "PLE"]],
    ["Ways to laugh loudly", ["ROAR", "CACKLE", "HOWL", "BELLOW"]],
  ),
  P(58,
    ["Big meals", ["FEAST", "BANQUET", "BUFFET", "SPREAD"]],
    ["Spread ___", ["SHEET", "EAGLE", "OUT", "THIN"]],
    ["Sheet ___", ["MUSIC", "ROCK", "METAL", "CAKE"]],
    ["Heavy metal", ["LEAD", "GOLD", "STEEL", "IRON"]],
  ),
  P(59,
    ["Types of shoe", ["BOOT", "SANDAL", "LOAFER", "SNEAKER"]],
    ["Boot ___", ["CAMP", "STRAP", "LEG", "LICKER"]],
    ["Camp ___", ["FIRE", "SITE", "GROUND", "OUT"]],
    ["Fire ___", ["FLY", "WORK", "PLACE", "ARM"]],
  ),
  P(60,
    ["Time to eat", ["BREAKFAST", "BRUNCH", "LUNCH", "DINNER"]],
    ["Sandwich types", ["CLUB", "WRAP", "SUB", "HOAGIE"]],
    ["Club ___", ["HOUSE", "SODA", "SANDWICH", "FOOT"]],
    ["Foot ___", ["PRINT", "BALL", "NOTE", "PATH"]],
  ),
];

// Sanity-check helper (dev only). Every puzzle must have 16 unique words.
export function validatePuzzles(): { id: number; issue: string }[] {
  const issues: { id: number; issue: string }[] = [];
  for (const p of PUZZLES) {
    const all: string[] = [];
    for (const c of p.categories) all.push(...c.words);
    if (all.length !== 16) issues.push({ id: p.id, issue: `word count ${all.length}` });
    const unique = new Set(all);
    if (unique.size !== all.length) {
      issues.push({ id: p.id, issue: `duplicate words: ${all.filter((w, i) => all.indexOf(w) !== i).join(", ")}` });
    }
    const diffs = new Set(p.categories.map((c) => c.difficulty));
    if (diffs.size !== 4) issues.push({ id: p.id, issue: `duplicate difficulty` });
  }
  return issues;
}
