export type WYRCategory =
  | "funny"
  | "deep"
  | "gross"
  | "hard"
  | "kids"
  | "couples"
  | "work"
  | "fantasy";

export interface WYRQuestion {
  a: string;
  b: string;
  category: WYRCategory;
}

export const CATEGORY_META: Record<
  WYRCategory | "all",
  { label: string; emoji: string; tint: string }
> = {
  all: { label: "All", emoji: "🎲", tint: "#8b5cf6" },
  funny: { label: "Funny", emoji: "😂", tint: "#f97316" },
  deep: { label: "Deep", emoji: "🧠", tint: "#3b82f6" },
  gross: { label: "Gross", emoji: "🤢", tint: "#22c55e" },
  hard: { label: "Hard Choices", emoji: "⚖️", tint: "#ef4444" },
  kids: { label: "Kids-Friendly", emoji: "🧒", tint: "#eab308" },
  couples: { label: "Couples", emoji: "💞", tint: "#ec4899" },
  work: { label: "Work", emoji: "💼", tint: "#0ea5e9" },
  fantasy: { label: "Fantasy", emoji: "🧙", tint: "#a855f7" },
};

export const QUESTIONS: WYRQuestion[] = [
  // ─────────────── FUNNY (22)
  { category: "funny", a: "sneeze uncontrollably every time you hear your own name", b: "burp loudly every time you make eye contact with a stranger" },
  { category: "funny", a: "have permanent bedhead", b: "have permanently sweaty palms" },
  { category: "funny", a: "always speak in rhymes", b: "always sing your sentences like a musical" },
  { category: "funny", a: "have hiccups for the rest of your life", b: "always feel like you need to sneeze but never can" },
  { category: "funny", a: "wear a wedding dress to every job interview", b: "wear a full clown costume to every first date" },
  { category: "funny", a: "have fingers as long as your legs", b: "have legs as short as your fingers" },
  { category: "funny", a: "only be able to whisper", b: "only be able to shout" },
  { category: "funny", a: "have a permanent unibrow", b: "have a permanent handlebar moustache (even if you're a woman)" },
  { category: "funny", a: "sound like Mickey Mouse for the rest of your life", b: "sound like a robotic GPS voice for the rest of your life" },
  { category: "funny", a: "always have spinach in your teeth", b: "always have a small piece of toilet paper stuck to your shoe" },
  { category: "funny", a: "have to slow-dance with the last person you texted every morning", b: "have to high-five every single person you pass on the street" },
  { category: "funny", a: "have a permanent laugh track follow you around", b: "have dramatic movie music play whenever you enter a room" },
  { category: "funny", a: "trip in front of a large crowd every day", b: "spill your drink on someone important once a week" },
  { category: "funny", a: "have autocorrect turn every word into 'duck'", b: "have Siri respond to every question in Shakespearean English" },
  { category: "funny", a: "look like you're always about to cry", b: "look like you're always about to sneeze" },
  { category: "funny", a: "have to narrate your own actions out loud", b: "have to mime everything you're about to do before doing it" },
  { category: "funny", a: "always be underdressed", b: "always be overdressed" },
  { category: "funny", a: "have a small cloud that rains only on you when you're sad", b: "have a tiny spotlight that follows you when you're happy" },
  { category: "funny", a: "have to wear flippers on your feet forever", b: "have to wear oven mitts on your hands forever" },
  { category: "funny", a: "sneeze glitter", b: "cry rainbow tears" },
  { category: "funny", a: "have your phone autoplay a fart sound every time you unlock it", b: "have your ringtone be your most embarrassing voicemail" },
  { category: "funny", a: "be permanently 30 minutes early to everything", b: "be permanently 15 minutes late to everything" },

  // ─────────────── DEEP (22)
  { category: "deep", a: "know the exact date you'll die", b: "know the exact cause of your death" },
  { category: "deep", a: "be forgotten by everyone you love", b: "forget everyone you love" },
  { category: "deep", a: "have all your memories from before age 18 erased", b: "never be able to form new long-term memories again" },
  { category: "deep", a: "always know when someone is lying to you", b: "always know when someone is thinking about you" },
  { category: "deep", a: "lose the ability to feel physical pain", b: "lose the ability to feel emotional pain" },
  { category: "deep", a: "live a long, quiet life with no impact", b: "live a short, loud life that changes the world" },
  { category: "deep", a: "know the truth about every conspiracy theory but never be believed", b: "believe every conspiracy theory is true and be certain of it" },
  { category: "deep", a: "have unlimited money but no close relationships", b: "have deep close relationships but always struggle financially" },
  { category: "deep", a: "know what everyone really thinks of you", b: "never know what anyone thinks of you again" },
  { category: "deep", a: "relive your best day forever on loop", b: "start every morning with a completely blank slate" },
  { category: "deep", a: "have the ability to undo one decision, one time", b: "have the ability to see the outcome of a decision before you make it" },
  { category: "deep", a: "be the smartest person in every room", b: "be the kindest person in every room" },
  { category: "deep", a: "know exactly when and how the world will end", b: "have the power to delay it by ten years, one time" },
  { category: "deep", a: "live 100 years as the same person", b: "live 10 lives of 10 years each, remembering none of them" },
  { category: "deep", a: "always speak your true, unfiltered thoughts", b: "never be able to say what you truly mean" },
  { category: "deep", a: "know the meaning of life but not be allowed to tell anyone", b: "spend your life searching for it and never finding it" },
  { category: "deep", a: "have your regrets erased forever", b: "keep every regret but also keep every lesson from them" },
  { category: "deep", a: "be truly understood by one person", b: "be admired by millions who don't really know you" },
  { category: "deep", a: "know what happens after you die", b: "never wonder about it again" },
  { category: "deep", a: "have chosen your own family", b: "have chosen your own name and identity from birth" },
  { category: "deep", a: "always tell the truth even when it hurts", b: "always tell a comforting lie even when it matters" },
  { category: "deep", a: "be remembered for something you didn't do", b: "be forgotten for something you did" },

  // ─────────────── GROSS (20)
  { category: "gross", a: "drink a glass of warm pickle juice", b: "eat a spoonful of straight mayonnaise" },
  { category: "gross", a: "share a toothbrush with a stranger for a week", b: "wear the same underwear for a week" },
  { category: "gross", a: "swim in a pool of raw eggs", b: "swim in a pool of cold, day-old spaghetti" },
  { category: "gross", a: "have permanently sweaty feet", b: "have permanently smelly breath" },
  { category: "gross", a: "eat a live cricket", b: "eat a spoonful of cat food" },
  { category: "gross", a: "never brush your teeth again", b: "never shower again but always smell neutral" },
  { category: "gross", a: "clean a public toilet with your bare hands", b: "clean a fast-food deep fryer with your bare hands" },
  { category: "gross", a: "find a hair in every meal you eat", b: "find a fly in every drink you order" },
  { category: "gross", a: "step on a wet slug barefoot every morning", b: "put your hand into a bowl of cold worms every night" },
  { category: "gross", a: "have to eat one bug per day", b: "have to eat a bowl of plain broccoli every day for life" },
  { category: "gross", a: "smell rotten fish for an hour", b: "smell a full baby's diaper for ten minutes" },
  { category: "gross", a: "sneeze into your own hands and rub them on your face", b: "lick a subway pole for five seconds" },
  { category: "gross", a: "eat a moldy sandwich", b: "drink milk that expired two weeks ago" },
  { category: "gross", a: "have someone else's earwax on your finger", b: "have someone else's toenail clipping in your food" },
  { category: "gross", a: "chew a piece of gum you found under a table", b: "wear socks a stranger has already worn all day" },
  { category: "gross", a: "wash your hair with mayonnaise", b: "wash your face with vinegar" },
  { category: "gross", a: "swallow a spoonful of hot sauce", b: "swallow a spoonful of raw garlic paste" },
  { category: "gross", a: "drink from a puddle", b: "eat one bite of food that fell on a public sidewalk" },
  { category: "gross", a: "have a snail crawl across your cheek", b: "have a spider crawl across your hand" },
  { category: "gross", a: "step barefoot in wet gym socks", b: "put on jeans straight out of a cold washing machine" },

  // ─────────────── HARD CHOICES (20)
  { category: "hard", a: "save five strangers you will never meet", b: "save one person you love" },
  { category: "hard", a: "give up your phone for a year", b: "give up hot showers for a year" },
  { category: "hard", a: "never watch another movie or show", b: "never listen to music again" },
  { category: "hard", a: "have your dream job with a terrible boss", b: "have a mediocre job with the best team ever" },
  { category: "hard", a: "lose your sense of taste forever", b: "lose your sense of smell forever" },
  { category: "hard", a: "always be 10 minutes late", b: "always be 30 minutes early" },
  { category: "hard", a: "have to speak every thought out loud for a day", b: "not be able to speak at all for a week" },
  { category: "hard", a: "live in a city you hate with people you love", b: "live in your dream city completely alone" },
  { category: "hard", a: "never travel outside your country again", b: "have to travel constantly and never have a permanent home" },
  { category: "hard", a: "be poor and healthy for life", b: "be rich but with chronic pain for life" },
  { category: "hard", a: "know how you'll die but not when", b: "know when you'll die but not how" },
  { category: "hard", a: "never be able to lie again", b: "never be able to tell the truth again" },
  { category: "hard", a: "give up sweets forever", b: "give up bread and pasta forever" },
  { category: "hard", a: "have to work a job you hate for 20 years and retire at 40", b: "have a job you love but have to work until you're 75" },
  { category: "hard", a: "read only one book for the rest of your life", b: "watch only one movie for the rest of your life" },
  { category: "hard", a: "lose all your childhood memories", b: "lose the ability to make new memories for a year" },
  { category: "hard", a: "have to move to a new country every 6 months", b: "have to live in the same small town for the rest of your life" },
  { category: "hard", a: "give up coffee forever", b: "give up all forms of alcohol forever" },
  { category: "hard", a: "sleep 4 hours a night and feel great", b: "sleep 10 hours a night and only feel okay" },
  { category: "hard", a: "have to say yes to everything for a month", b: "have to say no to everything for a month" },

  // ─────────────── KIDS-FRIENDLY (20)
  { category: "kids", a: "have a pet dragon", b: "have a pet unicorn" },
  { category: "kids", a: "be able to fly", b: "be invisible whenever you want" },
  { category: "kids", a: "eat pizza for every meal", b: "eat ice cream for every meal" },
  { category: "kids", a: "have super speed", b: "have super strength" },
  { category: "kids", a: "live in a treehouse", b: "live in an underwater house" },
  { category: "kids", a: "be able to talk to animals", b: "be able to speak every human language" },
  { category: "kids", a: "have summer all year round", b: "have winter all year round" },
  { category: "kids", a: "meet your favorite cartoon character", b: "meet your favorite athlete" },
  { category: "kids", a: "have a bedroom made entirely of candy", b: "have a bedroom that turns into any playground you imagine" },
  { category: "kids", a: "be a famous chef", b: "be a famous inventor" },
  { category: "kids", a: "spend the day at a water park", b: "spend the day at a theme park" },
  { category: "kids", a: "have a bouncy castle in your backyard", b: "have a giant slide in your backyard" },
  { category: "kids", a: "own a robot best friend", b: "own a talking teddy bear" },
  { category: "kids", a: "be really really tall", b: "be really really small" },
  { category: "kids", a: "eat only breakfast foods for a month", b: "eat only desserts for a month" },
  { category: "kids", a: "have wheels for feet", b: "have wings for arms" },
  { category: "kids", a: "sleep in a tent every night", b: "sleep in a giant hammock every night" },
  { category: "kids", a: "have a jetpack", b: "have a magic broom that flies" },
  { category: "kids", a: "explore the deepest ocean", b: "explore outer space" },
  { category: "kids", a: "be the best at every sport", b: "be the best at every video game" },

  // ─────────────── COUPLES (20)
  { category: "couples", a: "know every thought your partner has", b: "share every dream while you sleep" },
  { category: "couples", a: "have your first date on repeat forever", b: "always be planning the next big adventure together" },
  { category: "couples", a: "always know what to say", b: "always know when to just listen" },
  { category: "couples", a: "have one perfect day together every year, no matter what", b: "have a fine, ordinary life together with no big highs or lows" },
  { category: "couples", a: "spend every weekend traveling", b: "spend every weekend cozy at home" },
  { category: "couples", a: "read every text your partner has ever sent", b: "read their private journal from the last year" },
  { category: "couples", a: "meet in a totally different way than you did", b: "have met years earlier than you actually did" },
  { category: "couples", a: "never argue but rarely feel deeply understood", b: "argue sometimes but always feel truly seen" },
  { category: "couples", a: "have the same job", b: "have completely opposite careers you can each learn from" },
  { category: "couples", a: "share a birthday with your partner", b: "share a favorite hobby you both do every week" },
  { category: "couples", a: "hear your partner's voice in your head anytime you want", b: "always feel their hand in yours, even when apart" },
  { category: "couples", a: "know exactly what your partner is thinking on demand", b: "keep the mystery and figure it out the old-fashioned way" },
  { category: "couples", a: "live in the country together with no neighbors", b: "live in the middle of a busy city together" },
  { category: "couples", a: "cook every meal together at home", b: "eat out at a new restaurant every night" },
  { category: "couples", a: "be able to fast-forward through the boring parts", b: "slow down time during the best moments" },
  { category: "couples", a: "always have money but limited time together", b: "always have unlimited time together but very little money" },
  { category: "couples", a: "have your first kiss on repeat", b: "have your wedding day on repeat" },
  { category: "couples", a: "know your partner's future ten years in advance", b: "discover it together, day by day" },
  { category: "couples", a: "be perfectly compatible but rarely surprised", b: "be different in many ways but always learning from each other" },
  { category: "couples", a: "have the same taste in music, movies and food", b: "each have your own tastes and constantly introduce each other to new things" },

  // ─────────────── WORK / OFFICE (20)
  { category: "work", a: "work 4 long days a week", b: "work 5 short days a week" },
  { category: "work", a: "have a manager who micromanages every task", b: "have a manager who is completely absent and never gives feedback" },
  { category: "work", a: "always work from home", b: "always work from a busy office" },
  { category: "work", a: "have unlimited vacation days but can't take more than one week at a time", b: "have four weeks a year you can use however you like" },
  { category: "work", a: "sit through a two-hour meeting that could have been an email", b: "answer 100 emails that could have been solved in a single meeting" },
  { category: "work", a: "have a boss who is your best friend", b: "have a boss who is a total stranger but very fair" },
  { category: "work", a: "be paid double but never get promoted", b: "be paid the same and get promoted every two years" },
  { category: "work", a: "have unlimited coffee at work forever", b: "have unlimited free snacks at work forever" },
  { category: "work", a: "always have to give the presentation", b: "always have to take detailed notes for someone else's presentation" },
  { category: "work", a: "work night shifts with a great team", b: "work day shifts with a team you don't click with" },
  { category: "work", a: "have every Friday off but no other days off ever", b: "have a normal schedule with two weeks off every year" },
  { category: "work", a: "have to respond to Slack within 5 minutes any time it pings", b: "have no Slack at all and only weekly in-person meetings" },
  { category: "work", a: "share your office with your best friend", b: "share your office with a very quiet, respectful stranger" },
  { category: "work", a: "be forced to use only Windows XP for work", b: "be forced to use only a typewriter for all documents" },
  { category: "work", a: "have your camera on for every single meeting", b: "have your camera off but always be on mic" },
  { category: "work", a: "commute two hours a day to a job you love", b: "have a five-minute commute to a job you're indifferent about" },
  { category: "work", a: "work with people who are much smarter than you", b: "always be the smartest person in the room" },
  { category: "work", a: "get performance reviews once a week", b: "never get a performance review ever" },
  { category: "work", a: "have a job title nobody understands", b: "have a job title everyone underestimates" },
  { category: "work", a: "run your own small business", b: "have a very stable, well-paid corporate job" },

  // ─────────────── FANTASY / SUPERPOWERS (20)
  { category: "fantasy", a: "be able to teleport anywhere", b: "be able to stop time whenever you want" },
  { category: "fantasy", a: "read minds", b: "control minds" },
  { category: "fantasy", a: "have super strength", b: "have super speed" },
  { category: "fantasy", a: "be able to fly", b: "be able to breathe underwater" },
  { category: "fantasy", a: "control fire", b: "control water" },
  { category: "fantasy", a: "be immortal but alone", b: "have a normal lifespan surrounded by loved ones" },
  { category: "fantasy", a: "have a functional lightsaber", b: "have a real magic wand" },
  { category: "fantasy", a: "live in Middle-earth", b: "live in Hogwarts" },
  { category: "fantasy", a: "have a pet phoenix", b: "have a pet direwolf" },
  { category: "fantasy", a: "be able to shape-shift into any animal", b: "be able to talk to any animal" },
  { category: "fantasy", a: "have unlimited magic but only for one hour a day", b: "have small magic all day, every day, forever" },
  { category: "fantasy", a: "be granted three wishes with strict rules", b: "have one wish with no rules at all" },
  { category: "fantasy", a: "have an invisibility cloak", b: "have a time-turner" },
  { category: "fantasy", a: "be a wizard hidden in the modern world", b: "be an ordinary person in a full fantasy world" },
  { category: "fantasy", a: "ride a dragon once", b: "have a small dragon as a lifelong pet" },
  { category: "fantasy", a: "have the strength of a hundred people", b: "have the wisdom of a hundred elders" },
  { category: "fantasy", a: "know every language ever spoken", b: "know every spell ever cast" },
  { category: "fantasy", a: "be able to see 24 hours into the future", b: "be able to see 24 hours into the past for any place" },
  { category: "fantasy", a: "wield the One Ring but hear its whispers", b: "wield Excalibur but only in defense of others" },
  { category: "fantasy", a: "have the power to heal any wound", b: "have the power to never be wounded" },
];
