/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as ToolsWordToPdfRouteImport } from './routes/tools.word-to-pdf'
import { Route as ToolsVideoToGifRouteImport } from './routes/tools.video-to-gif'
import { Route as ToolsVideoDownloaderRouteImport } from './routes/tools.video-downloader'
import { Route as ToolsTextToSpeechRouteImport } from './routes/tools.text-to-speech'
import { Route as ToolsSpeechToTextRouteImport } from './routes/tools.speech-to-text'
import { Route as ToolsRemoveBgRouteImport } from './routes/tools.remove-bg'
import { Route as ToolsQrReaderRouteImport } from './routes/tools.qr-reader'
import { Route as ToolsQrGeneratorRouteImport } from './routes/tools.qr-generator'
import { Route as ToolsPdfTextExtractorRouteImport } from './routes/tools.pdf-text-extractor'
import { Route as ToolsPasswordGeneratorRouteImport } from './routes/tools.password-generator'
import { Route as ToolsMergePdfRouteImport } from './routes/tools.merge-pdf'
import { Route as ToolsImageUpscalerRouteImport } from './routes/tools.image-upscaler'
import { Route as ToolsImageToTextRouteImport } from './routes/tools.image-to-text'
import { Route as ToolsImageConverterRouteImport } from './routes/tools.image-converter'
import { Route as ToolsImageCompressorRouteImport } from './routes/tools.image-compressor'
import { Route as ToolsBase64RouteImport } from './routes/tools.base64'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsWordToPdfRoute = ToolsWordToPdfRouteImport.update({
  id: '/tools/word-to-pdf',
  path: '/tools/word-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsVideoToGifRoute = ToolsVideoToGifRouteImport.update({
  id: '/tools/video-to-gif',
  path: '/tools/video-to-gif',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsVideoDownloaderRoute = ToolsVideoDownloaderRouteImport.update({
  id: '/tools/video-downloader',
  path: '/tools/video-downloader',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsTextToSpeechRoute = ToolsTextToSpeechRouteImport.update({
  id: '/tools/text-to-speech',
  path: '/tools/text-to-speech',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSpeechToTextRoute = ToolsSpeechToTextRouteImport.update({
  id: '/tools/speech-to-text',
  path: '/tools/speech-to-text',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRemoveBgRoute = ToolsRemoveBgRouteImport.update({
  id: '/tools/remove-bg',
  path: '/tools/remove-bg',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsQrReaderRoute = ToolsQrReaderRouteImport.update({
  id: '/tools/qr-reader',
  path: '/tools/qr-reader',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsQrGeneratorRoute = ToolsQrGeneratorRouteImport.update({
  id: '/tools/qr-generator',
  path: '/tools/qr-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPdfTextExtractorRoute = ToolsPdfTextExtractorRouteImport.update({
  id: '/tools/pdf-text-extractor',
  path: '/tools/pdf-text-extractor',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPasswordGeneratorRoute = ToolsPasswordGeneratorRouteImport.update({
  id: '/tools/password-generator',
  path: '/tools/password-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsMergePdfRoute = ToolsMergePdfRouteImport.update({
  id: '/tools/merge-pdf',
  path: '/tools/merge-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsImageUpscalerRoute = ToolsImageUpscalerRouteImport.update({
  id: '/tools/image-upscaler',
  path: '/tools/image-upscaler',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsImageToTextRoute = ToolsImageToTextRouteImport.update({
  id: '/tools/image-to-text',
  path: '/tools/image-to-text',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsImageConverterRoute = ToolsImageConverterRouteImport.update({
  id: '/tools/image-converter',
  path: '/tools/image-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsImageCompressorRoute = ToolsImageCompressorRouteImport.update({
  id: '/tools/image-compressor',
  path: '/tools/image-compressor',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBase64Route = ToolsBase64RouteImport.update({
  id: '/tools/base64',
  path: '/tools/base64',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tools/base64': typeof ToolsBase64Route
  '/tools/image-compressor': typeof ToolsImageCompressorRoute
  '/tools/image-converter': typeof ToolsImageConverterRoute
  '/tools/image-to-text': typeof ToolsImageToTextRoute
  '/tools/image-upscaler': typeof ToolsImageUpscalerRoute
  '/tools/merge-pdf': typeof ToolsMergePdfRoute
  '/tools/password-generator': typeof ToolsPasswordGeneratorRoute
  '/tools/pdf-text-extractor': typeof ToolsPdfTextExtractorRoute
  '/tools/qr-generator': typeof ToolsQrGeneratorRoute
  '/tools/qr-reader': typeof ToolsQrReaderRoute
  '/tools/remove-bg': typeof ToolsRemoveBgRoute
  '/tools/speech-to-text': typeof ToolsSpeechToTextRoute
  '/tools/text-to-speech': typeof ToolsTextToSpeechRoute
  '/tools/video-downloader': typeof ToolsVideoDownloaderRoute
  '/tools/video-to-gif': typeof ToolsVideoToGifRoute
  '/tools/word-to-pdf': typeof ToolsWordToPdfRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tools/base64': typeof ToolsBase64Route
  '/tools/image-compressor': typeof ToolsImageCompressorRoute
  '/tools/image-converter': typeof ToolsImageConverterRoute
  '/tools/image-to-text': typeof ToolsImageToTextRoute
  '/tools/image-upscaler': typeof ToolsImageUpscalerRoute
  '/tools/merge-pdf': typeof ToolsMergePdfRoute
  '/tools/password-generator': typeof ToolsPasswordGeneratorRoute
  '/tools/pdf-text-extractor': typeof ToolsPdfTextExtractorRoute
  '/tools/qr-generator': typeof ToolsQrGeneratorRoute
  '/tools/qr-reader': typeof ToolsQrReaderRoute
  '/tools/remove-bg': typeof ToolsRemoveBgRoute
  '/tools/speech-to-text': typeof ToolsSpeechToTextRoute
  '/tools/text-to-speech': typeof ToolsTextToSpeechRoute
  '/tools/video-downloader': typeof ToolsVideoDownloaderRoute
  '/tools/video-to-gif': typeof ToolsVideoToGifRoute
  '/tools/word-to-pdf': typeof ToolsWordToPdfRoute
  '/tools': typeof ToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tools/base64': typeof ToolsBase64Route
  '/tools/image-compressor': typeof ToolsImageCompressorRoute
  '/tools/image-converter': typeof ToolsImageConverterRoute
  '/tools/image-to-text': typeof ToolsImageToTextRoute
  '/tools/image-upscaler': typeof ToolsImageUpscalerRoute
  '/tools/merge-pdf': typeof ToolsMergePdfRoute
  '/tools/password-generator': typeof ToolsPasswordGeneratorRoute
  '/tools/pdf-text-extractor': typeof ToolsPdfTextExtractorRoute
  '/tools/qr-generator': typeof ToolsQrGeneratorRoute
  '/tools/qr-reader': typeof ToolsQrReaderRoute
  '/tools/remove-bg': typeof ToolsRemoveBgRoute
  '/tools/speech-to-text': typeof ToolsSpeechToTextRoute
  '/tools/text-to-speech': typeof ToolsTextToSpeechRoute
  '/tools/video-downloader': typeof ToolsVideoDownloaderRoute
  '/tools/video-to-gif': typeof ToolsVideoToGifRoute
  '/tools/word-to-pdf': typeof ToolsWordToPdfRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/tools/base64'
    | '/tools/image-compressor'
    | '/tools/image-converter'
    | '/tools/image-to-text'
    | '/tools/image-upscaler'
    | '/tools/merge-pdf'
    | '/tools/password-generator'
    | '/tools/pdf-text-extractor'
    | '/tools/qr-generator'
    | '/tools/qr-reader'
    | '/tools/remove-bg'
    | '/tools/speech-to-text'
    | '/tools/text-to-speech'
    | '/tools/video-downloader'
    | '/tools/video-to-gif'
    | '/tools/word-to-pdf'
    | '/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/tools/base64'
    | '/tools/image-compressor'
    | '/tools/image-converter'
    | '/tools/image-to-text'
    | '/tools/image-upscaler'
    | '/tools/merge-pdf'
    | '/tools/password-generator'
    | '/tools/pdf-text-extractor'
    | '/tools/qr-generator'
    | '/tools/qr-reader'
    | '/tools/remove-bg'
    | '/tools/speech-to-text'
    | '/tools/text-to-speech'
    | '/tools/video-downloader'
    | '/tools/video-to-gif'
    | '/tools/word-to-pdf'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/tools/base64'
    | '/tools/image-compressor'
    | '/tools/image-converter'
    | '/tools/image-to-text'
    | '/tools/image-upscaler'
    | '/tools/merge-pdf'
    | '/tools/password-generator'
    | '/tools/pdf-text-extractor'
    | '/tools/qr-generator'
    | '/tools/qr-reader'
    | '/tools/remove-bg'
    | '/tools/speech-to-text'
    | '/tools/text-to-speech'
    | '/tools/video-downloader'
    | '/tools/video-to-gif'
    | '/tools/word-to-pdf'
    | '/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ToolsBase64Route: typeof ToolsBase64Route
  ToolsImageCompressorRoute: typeof ToolsImageCompressorRoute
  ToolsImageConverterRoute: typeof ToolsImageConverterRoute
  ToolsImageToTextRoute: typeof ToolsImageToTextRoute
  ToolsImageUpscalerRoute: typeof ToolsImageUpscalerRoute
  ToolsMergePdfRoute: typeof ToolsMergePdfRoute
  ToolsPasswordGeneratorRoute: typeof ToolsPasswordGeneratorRoute
  ToolsPdfTextExtractorRoute: typeof ToolsPdfTextExtractorRoute
  ToolsQrGeneratorRoute: typeof ToolsQrGeneratorRoute
  ToolsQrReaderRoute: typeof ToolsQrReaderRoute
  ToolsRemoveBgRoute: typeof ToolsRemoveBgRoute
  ToolsSpeechToTextRoute: typeof ToolsSpeechToTextRoute
  ToolsTextToSpeechRoute: typeof ToolsTextToSpeechRoute
  ToolsVideoDownloaderRoute: typeof ToolsVideoDownloaderRoute
  ToolsVideoToGifRoute: typeof ToolsVideoToGifRoute
  ToolsWordToPdfRoute: typeof ToolsWordToPdfRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/word-to-pdf': {
      id: '/tools/word-to-pdf'
      path: '/tools/word-to-pdf'
      fullPath: '/tools/word-to-pdf'
      preLoaderRoute: typeof ToolsWordToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/video-to-gif': {
      id: '/tools/video-to-gif'
      path: '/tools/video-to-gif'
      fullPath: '/tools/video-to-gif'
      preLoaderRoute: typeof ToolsVideoToGifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/video-downloader': {
      id: '/tools/video-downloader'
      path: '/tools/video-downloader'
      fullPath: '/tools/video-downloader'
      preLoaderRoute: typeof ToolsVideoDownloaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/text-to-speech': {
      id: '/tools/text-to-speech'
      path: '/tools/text-to-speech'
      fullPath: '/tools/text-to-speech'
      preLoaderRoute: typeof ToolsTextToSpeechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/speech-to-text': {
      id: '/tools/speech-to-text'
      path: '/tools/speech-to-text'
      fullPath: '/tools/speech-to-text'
      preLoaderRoute: typeof ToolsSpeechToTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/remove-bg': {
      id: '/tools/remove-bg'
      path: '/tools/remove-bg'
      fullPath: '/tools/remove-bg'
      preLoaderRoute: typeof ToolsRemoveBgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/qr-reader': {
      id: '/tools/qr-reader'
      path: '/tools/qr-reader'
      fullPath: '/tools/qr-reader'
      preLoaderRoute: typeof ToolsQrReaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/qr-generator': {
      id: '/tools/qr-generator'
      path: '/tools/qr-generator'
      fullPath: '/tools/qr-generator'
      preLoaderRoute: typeof ToolsQrGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/pdf-text-extractor': {
      id: '/tools/pdf-text-extractor'
      path: '/tools/pdf-text-extractor'
      fullPath: '/tools/pdf-text-extractor'
      preLoaderRoute: typeof ToolsPdfTextExtractorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/password-generator': {
      id: '/tools/password-generator'
      path: '/tools/password-generator'
      fullPath: '/tools/password-generator'
      preLoaderRoute: typeof ToolsPasswordGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/merge-pdf': {
      id: '/tools/merge-pdf'
      path: '/tools/merge-pdf'
      fullPath: '/tools/merge-pdf'
      preLoaderRoute: typeof ToolsMergePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/image-upscaler': {
      id: '/tools/image-upscaler'
      path: '/tools/image-upscaler'
      fullPath: '/tools/image-upscaler'
      preLoaderRoute: typeof ToolsImageUpscalerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/image-to-text': {
      id: '/tools/image-to-text'
      path: '/tools/image-to-text'
      fullPath: '/tools/image-to-text'
      preLoaderRoute: typeof ToolsImageToTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/image-converter': {
      id: '/tools/image-converter'
      path: '/tools/image-converter'
      fullPath: '/tools/image-converter'
      preLoaderRoute: typeof ToolsImageConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/image-compressor': {
      id: '/tools/image-compressor'
      path: '/tools/image-compressor'
      fullPath: '/tools/image-compressor'
      preLoaderRoute: typeof ToolsImageCompressorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/base64': {
      id: '/tools/base64'
      path: '/tools/base64'
      fullPath: '/tools/base64'
      preLoaderRoute: typeof ToolsBase64RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ToolsBase64Route: ToolsBase64Route,
  ToolsImageCompressorRoute: ToolsImageCompressorRoute,
  ToolsImageConverterRoute: ToolsImageConverterRoute,
  ToolsImageToTextRoute: ToolsImageToTextRoute,
  ToolsImageUpscalerRoute: ToolsImageUpscalerRoute,
  ToolsMergePdfRoute: ToolsMergePdfRoute,
  ToolsPasswordGeneratorRoute: ToolsPasswordGeneratorRoute,
  ToolsPdfTextExtractorRoute: ToolsPdfTextExtractorRoute,
  ToolsQrGeneratorRoute: ToolsQrGeneratorRoute,
  ToolsQrReaderRoute: ToolsQrReaderRoute,
  ToolsRemoveBgRoute: ToolsRemoveBgRoute,
  ToolsSpeechToTextRoute: ToolsSpeechToTextRoute,
  ToolsTextToSpeechRoute: ToolsTextToSpeechRoute,
  ToolsVideoDownloaderRoute: ToolsVideoDownloaderRoute,
  ToolsVideoToGifRoute: ToolsVideoToGifRoute,
  ToolsWordToPdfRoute: ToolsWordToPdfRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
