export interface Statement {
  id: number;
  category: string;
  text: string;
}

export const CATEGORIES = [
  "Social & Nightlife",
  "Travel & Adventure",
  "Relationships",
  "Small Vices & Habits",
  "Mischief & Rule-Breaking",
  "Growing Up",
  "Quirky & Embarrassing",
] as const;

export type Category = (typeof CATEGORIES)[number];

const RAW: Record<Category, string[]> = {
  "Social & Nightlife": [
    "Stayed up all night talking to someone",
    "Skipped school or work just because you didn't feel like it",
    "Been to a party that got shut down",
    "Danced on a table",
    "Gone to a concert or festival",
    "Snuck out of the house at night",
    "Been the last one to leave a party",
    "Lied about where you were going",
    "Been to a costume party",
    "Sung karaoke in front of strangers",
    "Been kicked out of somewhere",
    "Made a new friend during a night out",
    "Stayed at a party where you didn't know anyone",
    "Turned a study session into something else entirely",
  ],
  "Travel & Adventure": [
    "Traveled to another country alone",
    "Missed a flight",
    "Slept in an airport",
    "Gone camping without the right gear",
    "Accepted a ride from someone you'd just met",
    "Gotten lost somewhere with no phone service",
    "Jumped into open water you'd never swum in before",
    "Gone on a road trip with no fixed plan",
    "Tried a food you couldn't identify",
    "Talked your way past a rule that should've stopped you",
    "Slept somewhere that wasn't a bed",
    "Crossed a border without knowing the local language",
  ],
  Relationships: [
    "Had your heart broken",
    "Broken someone else's heart",
    "Said 'I love you' and meant it",
    "Said 'I love you' and didn't quite mean it",
    "Been in a relationship that lasted over a year",
    "Kept in touch with almost every ex",
    "Been on a blind date",
    "Been set up by a friend",
    "Been in a long-distance relationship",
    "Gotten back together with an ex",
    "Been ghosted",
    "Ghosted someone else",
    "Fallen for a friend",
    "Had a crush you never told anyone about",
    "Been proposed to, or proposed yourself",
  ],
  "Small Vices & Habits": [
    "Had a hangover",
    "Tried a cigarette",
    "Had more than one drink in a night",
    "Pulled an all-nighter for no good reason",
    "Eaten an entire meal meant for two",
    "Gone a full day without checking your phone",
    "Skipped a meal to save money for something else",
    "Pulled an all-nighter for work or school",
    "Had caffeine after midnight just to keep going",
    "Gone through a phase you're embarrassed about now",
    "Quit a habit cold turkey",
    "Broken a promise you made to yourself",
  ],
  "Mischief & Rule-Breaking": [
    "Told a small lie that got out of hand",
    "Cheated on a test or assignment",
    "Snuck into somewhere you weren't supposed to be",
    "Used a fake ID or someone else's ID",
    "Jaywalked right in front of a police officer",
    "Returned something you'd already used",
    "Taken credit for someone else's idea",
    "Pretended to be sick to get out of something",
    "Broken a rule you actually agreed with",
    "Talked your way out of a fine or ticket",
    "Forged a signature, even a small one",
    "Kept money you found that wasn't yours",
    "Snooped through someone's phone or messages",
    "Eavesdropped on a conversation not meant for you",
    "Blamed someone else for your own mistake",
  ],
  "Growing Up": [
    "Lived on your own for the first time",
    "Paid your own rent or bills",
    "Cooked a full meal from scratch",
    "Made a big decision without asking anyone for advice",
    "Moved to a new city where you knew no one",
    "Quit a job without having another one lined up",
    "Started your own project or small business",
    "Learned a skill entirely on your own",
    "Made a mistake that cost you real money",
    "Had to ask for help when you really didn't want to",
    "Supported yourself financially for at least a year",
    "Made a five-year plan and completely abandoned it",
    "Given advice you didn't actually follow yourself",
  ],
  "Quirky & Embarrassing": [
    "Tripped or fallen in public",
    "Sent a text to the wrong person",
    "Called someone by the wrong name",
    "Laughed so hard you cried",
    "Cried during a movie or show",
    "Talked to yourself out loud in public",
    "Gotten caught singing when you thought no one was listening",
    "Walked straight into a glass door",
    "Forgotten someone's name right after being introduced",
    "Worn something inside out all day without noticing",
    "Hit 'reply all' by accident",
    "Left the house with mismatched shoes or socks",
    "Accidentally liked an old photo while browsing someone's profile",
    "Been caught talking about someone right as they walked in",
    "Waved back at someone who wasn't waving at you",
    "Kept a secret for someone else that was hard to keep",
    "Changed your mind about something you were once completely sure of",
    "Done something out of character just to see how it felt",
    "Surprised yourself with how you handled a hard situation",
  ],
};

let counter = 0;
export const STATEMENTS: Statement[] = CATEGORIES.flatMap((category) =>
  RAW[category].map((text) => ({ id: ++counter, category, text })),
);

export const TOTAL_STATEMENTS = STATEMENTS.length; // 100
